### ISSUE TITLE
Can't download 2.0.0

### ISSUE THREAD

**Issue by mseroczynski** [chrisjenx/Calligraphy#105]
Hey there. It's always good to see that something big is going on but, well, is there any possibility of repairing 2.0.0 hosting before the end of the day? I've got an app to ship by tomorrow morning and... 

http://search.maven.org/remotecontent?filepath=uk/co/chrisjenx/calligraphy/2.0.0/calligraphy-2.0.0.aar

...as well as...

dependencies {
    compile 'uk.co.chrisjenx:calligraphy:2.0.0'
}

...isn't working :) Thank you for any reply.

**Comment by nekofar** [comment]
```
repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    compile 'uk.co.chrisjenx:calligraphy:2.0.0-SNAPSHOT'
}
```

**Comment by mseroczynski** [comment]
That's a nice tip, but shouldn't that info be on the main README.md (instead of not working 'compile 'uk.co.chrisjenx:calligraphy:2.0.0')? #justaskin

**Comment by chrisjenx** [comment]
thanks @nekofar. @mseroczynski was a premature update to the readme.

**Comment by jpozo20** [comment]
Stil not working for me after adding the sonatype repository.

**Comment by chrisjenx** [comment]
@jpozo20 you might need to call `./gradlew --refresh-dependencies` common problem.

**Comment by jpozo20** [comment]
That wasn't the problem though, seems in the new versions of gradle they changed the location of the repositories settings and had it in the wrong place. 
Thanks for replying, now everything is working :D

**Comment by chrisjenx** [comment]
Ahh interesting. Haven't noticed that before.

**Comment by squeeish** [comment]
@nekofar 's solution worked for me.

**Comment by neokree** [comment]
@chrisjenx Calligraphy seems not updated to the last release on maven.
![schermata 2015-01-10 alle 22 33 38](https://cloud.githubusercontent.com/assets/9344184/5693357/f0dfa682-9918-11e4-9e52-f5dc7b8662f2.png)

We should use the SNAPSHOT version?

**Comment by chrisjenx** [comment]
As mentioned in other issues, yes. The changelog also states it's still WIP.

**Comment by dongseok0** [comment]
Uh oh

Still fail getting lib with below message

Error:Failed to find: uk.co.chrisjenx:calligraphy:2.0.0-SNAPSHOT

I tried --refresh-dependencies

**Comment by chrisjenx** [comment]
You added the snapshot URL under repositories?

**Comment by dongseok0** [comment]
Ah, I missed that. Thank you!

**Comment by chrisjenx** [comment]
Just pushed out 2.0.0 release.
