### ISSUE TITLE
It doesnt work with fragment

### ISSUE THREAD

**Issue by darshan1** [chrisjenx/Calligraphy#108]
Right now you have mentioned that while inflating layout in onCreateView() use
getActivity().getLayoutInflator(),

But in this case I am unable to find my fragment in the layout using getChildFragmentManager(),
Which returns NullPointerException.

Let me know if you have solution for this also.

Thanks

**Comment by chrisjenx** [comment]
No support for `getChildFragmentManager()` 
1. Because it's really evil and a horrible implimentation on Google's behalf. 
2. It has been fixed in the upcoming 2.x version. Which the latest snapshot can be tested.
