### ISSUE TITLE
Error:(22, 0) Cannot get property 'versionCodeInt' on extra properties extension as it does not exist

### ISSUE THREAD

**Issue by Kazn** [chrisjenx/Calligraphy#110]
I added this library and build in Android Studio .I got this error " Error:(22, 0) Cannot get property 'versionCodeInt' on extra properties extension as it does not exist ". Error come from libs/calligraphy/build.gradle .
What should I do now

**Comment by chrisjenx** [comment]
Not sure how you added it, but my guess would be you added it as a module incorrectly. The `build.gradle` paths might not be relative to be honest. 

Add it via gradle, if you want to have your own version, fork it and run the project and deploy to your local maven repository.

**Comment by RassProjects** [comment]
Even i have same problem
when i add it via gradel it suddenly miss appcompat-v7

Error:Failed to find: com.android.support:appcompat-v7:22.1.1
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>

and if i add it via module dependance
Error:(22, 0) Cannot get property 'versionCodeInt' on extra properties extension as it does not exist.

guide me..
