### ISSUE TITLE
Font won't set?!

### ISSUE THREAD

**Issue by tbremer19** [chrisjenx/Calligraphy#115]
Hello, it's me again :smile: 
I have a problem, I use the 2.0.0-SNAPSHOT version and I did anything like in the README but the font in the app is still roboto regular... 
Here are my files: https://gist.github.com/tbremer19/bf24c2621f61a04815a6

I don't know what I've done wrong or what I forgot to do...

Thanks for your help again!

**Comment by chrisjenx** [comment]
@tbremer19 maybe its not clear enough but it is described in the README. The CalligraphyConfig needs to be called in the Application Class. `attachBaseContext()` is called way before `onCreate()` is.
Currently you are setting the config after the LayoutInflater has been created.

**Comment by tbremer19** [comment]
@chrisjenx Sorry but I still don't get it... I called CalligraphyConfig in my main activity under `super.onCreate(savedInstanceState);` just like you did. Now I put `attachBaseContext()` above `onCreate` is that right? 

I tried it but the font still won't set... What am I doing wrong again?

**Comment by chrisjenx** [comment]
@tbremer19 
```
 CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                        .setDefaultFontPath("fonts/RobotoCondensed-Light.ttf")
                        .setFontAttrId(R.attr.fontPath)
                        .build()
        );
```

Must be in you Application class *not* your Activity class.

If you are getting that error it signifies that it can't find the font. I would carefully check the name of your font in the assets/fonts and in your config. possibly a typo.

**Comment by tbremer19** [comment]
I did... I have the config in my application class (`... extends Application`)
And I also checked the name, anything is fine :disappointed:

**Comment by tbremer19** [comment]
@chrisjenx Got it... The TTF was somehow corrupted :disappointed: 
But thanks for your help :wink:
