### ISSUE TITLE
Resets to system font

### ISSUE THREAD

**Issue by Alkimisticus** [chrisjenx/Calligraphy#117]
I'm using Calligraphy 2.0.0.  it works great. But if I switch from myapp to another or I simply go out of my app (I don't close it) for couple of minutes. My Calligraphy specified font is replaced with default system font.

**Comment by chrisjenx** [comment]
@Alkimisticus where do you define your CalligraphyConfig? Make sure its in your `Application` class _not_ the `Activity` class.

**Comment by Alkimisticus** [comment]
Thank you :+1:  and sorry for bothering you with RTFM issue.
