### ISSUE TITLE
ActionMode appcompat-v7 (icon and text colors problem after setting up Calligraphy)

### ISSUE THREAD

**Issue by ferrannp** [chrisjenx/Calligraphy#120]
Hello!

I have a Toolbar set up and I am also using an action mode with my color accent as a background.

Toolbar:
```
<android.support.v7.widget.Toolbar xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/toolbar"
    android:layout_width="match_parent"
    android:layout_height="?attr/actionBarSize"
    android:background="?attr/colorPrimary"
    app:contentInsetEnd="0dp"
    app:contentInsetLeft="72dp"
    app:contentInsetRight="0dp"
    app:contentInsetStart="72dp"
    android:elevation="4dp"
    app:navigationIcon="?attr/homeAsUpIndicator"
    app:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
    app:popupTheme="@style/ThemeOverlay.AppCompat.Light">
</android.support.v7.widget.Toolbar>
```
Theme:
```
<style name="AppBaseThemeMaterial" parent="Theme.AppCompat.Light">
...
    <item name="actionModeStyle">@style/AppBaseThemeMaterial.ActionMode</item>
</style>

<style name="AppBaseThemeMaterial.ActionMode" parent="@style/Widget.AppCompat.ActionMode">
    <item name="background">@color/colorAccent</item>
 </style>
```

What I used to see is:

![screenshot_2015-01-26-00-48-07 2](https://cloud.githubusercontent.com/assets/774577/5893894/811c77c4-a4f5-11e4-8ea1-a373fca068ab.jpg)

But after setting up Calligraphy and using this into my main activity:

    @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
    }

I see it in this way:

![screenshot_2015-01-26-00-44-55 2]
(https://cloud.githubusercontent.com/assets/774577/5893903/9b0e9716-a4f5-11e4-8fc3-9f7a069e1c19.jpg)

Text is black instead of white... And I only see the back arrow when pressing on it (it is the same color as the bar now!). Any ideas on why is this happening? Thank you!

**Comment by chrisjenx** [comment]
@ferrannp Shot in the dark here: I am going to assume this is related to:
```xml
 app:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
    app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
```

Can you add a but more code to complete the example, I think I know what this is but if I can replicate it that always helps!

Thanks,
Chris

**Comment by ferrannp** [comment]
Hello!  I'll try to write an example when I have time... yes basically I added those lines you quoted to do something like:

https://chris.banes.me/2014/10/17/appcompat-v21/
```
<android.support.v7.widget.Toolbar
    android:layout_height="wrap_content"
    android:layout_width="match_parent"
    android:minHeight="@dimen/triple_height_toolbar"
    app:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
    app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />
```

I have a simple listview that uses CHOICE_MODE_MULTIPLE_MODAL. Unfortunately, there is no much information on how to style that text & icon of the Action Mode.

**Comment by chrisjenx** [comment]
@ferrannp yeah that is correct, this is to do with theme context, which isn't generated. I was suspicious this might happen but couldn't reproduce. So if you have a simple example that would be great :)

**Comment by castrojr913** [comment]
The same problem. I try to set the custom font and nothing: with all views is possible except for toolbar widget. The ideal way is to do it through styles.xml not by hard code, it's an ugly workaround. If i want to change the font for the app, so i have to change it on styles.xml and per each java class too, I think that's not the idea.

**Comment by chrisjenx** [comment]
@ferrannp try:

```
<android.support.v7.widget.Toolbar
    android:layout_height="wrap_content"
    android:layout_width="match_parent"
    android:minHeight="@dimen/triple_height_toolbar"
    app:theme="@style/ThemeOverlay.AppCompat.Dark"
    app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />
```

Seem's defining `app:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"` is wrong. Removing the ActionBar works fine.

**Comment by chrisjenx** [comment]
@castrojr913 the TextView's in the Toolbar get added progmatically, If you define the titleStyle and subtitleStyle as per the old action bar impl, those will work. I am get to fully overhaul the deeplinking into styles for Menus etc.. It's safe to say its a bit of a pain as they are not inflated traditionally.

**Comment by ferrannp** [comment]
Hi @chrisjenx, your solution didn't work for me. What I see changing Dark.ActionBar for Dark is:

![screenshot_2015-02-03-23-41-24 2](https://cloud.githubusercontent.com/assets/774577/6031378/0b2319c2-abff-11e4-92c6-4b4c0894888d.jpg)

So now I can see the arrow but style neither the title or the arrow are white.

**Comment by chrisjenx** [comment]
Very odd, as it works fine for me, I'll have to investigate more.

**Comment by chrisjenx** [comment]
@ferrannp are you able to pull out a broken sample into here?
I use this in a few apps now without issue, I can only guess its an Impli misunderstanding.

**Comment by ferrannp** [comment]
A part from the code I posted, I set up the ActionMode using:            

    listView.setMultiChoiceModeListener(multiChoiceModeListener);

And start it using:             

    getListView().setItemChecked(position, !checkedItems.get(position));

(When there is some long click in some button inside the list).

Can I see some sample when this is working? Maybe will be faster :)

**Comment by chrisjenx** [comment]
Sorry have you tried setting the popup Theme to dark?

**Comment by chrisjenx** [comment]
@ferrannp I identified an issue tonight, I might of solved your issue. I'm about to push a snapshot.

**Comment by ferrannp** [comment]
Hello! I tried version 2.0.2 and the issue is not happening anymore. Thank you! You're doing a great job here.

**Comment by roygwsidev** [comment]
Hello!
I getting issue on pre api 19 devices and using appcompat-v7:22.1.1.
Thanks

**Comment by chrisjenx** [comment]
@roygwsidev and are you using the latest version of `Calligraphy`?

**Comment by drakgoku1** [comment]
You can solve with this code : 

toolbar.setTitleTextColor(0xFFFFFFFF);

http://stackoverflow.com/questions/26852108/how-do-you-set-the-title-color-for-the-new-toolbar

I found here
