### ISSUE TITLE
Calligraphy 2.0 breaks RecyclerView theme's colorEdgeEffect

### ISSUE THREAD

**Issue by schainan** [chrisjenx/Calligraphy#123]
Hi,

We're using a RecyclerView in our app with a custom colorEdgeEffect that is different from the main app's colorPrimary. When I upgrade our app from Calligraphy 1.1.0 to version 2.0.0, the colorEdgeEffect reverts to the old color and not the custom one we have in the theme. Is this reproducible from your end?

**Comment by chrisjenx** [comment]
It is not, this works for me on my main project.
