### ISSUE TITLE
Can your project support Chinese or Japanese ？

### ISSUE THREAD

**Issue by xiaomeixw** [chrisjenx/Calligraphy#124]
Can your project support Chinese or Japanese？

**Comment by intrications** [comment]
Yes, it can. You can see an example of Calligraphy being used to display Chinese in a custom font here:

https://github.com/asm-products/kanshu-android/blob/master/app/src/main/res/layout/activity_development.xml#L81

**Comment by Sasure** [comment]
I had tried.It can't support Chinese

**Comment by intrications** [comment]
@Sasure Are you sure? What font are you trying to use?

Does the screenshot on this page not show it being used for Chinese? 
https://assembly.com/kanshu/bounties/119

**Comment by chrisjenx** [comment]
@Sasure, the support for language lies with the Font you use. Calligraphy is a glorified Type face wrapper (`Typeface.createFromAsset(getAsset(),"font/NameOfFont.ttf");`), If what you are trying does not work I would suggest it's an issue with your font/setup.

**Comment by intrications** [comment]
@Sasure @xiaomeixw Have you checked the logcat when running your app?

**Comment by Sasure** [comment]
@intrications @chrisjenx I just use the Sample and change the string,like this
![](https://raw.githubusercontent.com/Sasure/ToDoList/master/screenshot/Screenshot.png)

**Comment by Sasure** [comment]
have i add some fonts which support chinese?

**Comment by chrisjenx** [comment]
I'm not sure what the end goal is here?
It looks like Chinese/Japanese works fine?

**Comment by chrisjenx** [comment]
Not sure if there was an issue? Question? Closing, please reopen if there is something I can hopefully answer.
