### ISSUE TITLE
ActionBar TabText typeface ?

### ISSUE THREAD

**Issue by DJafari** [chrisjenx/Calligraphy#126]
how can change tab text typeface ?

using this, but not working

```java
CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                .setDefaultFontPath("FD.ttf")
                .setFontAttrId(R.attr.fontPath)
                .build());
```

**Comment by chrisjenx** [comment]
@DJafari which Tab, there are a couple in the SDK? 
The very simple rule is, anything created pragmatically will not have a typeface applied. 
You're `TextView` needs to run through the `Inflater` for `Calligraphy` to be able to inject automatically.

**Comment by DJafari** [comment]
thanks for your reply
i want change actionbar tab text like actionbar title automatically, can be done ?

**Comment by chrisjenx** [comment]
I think these follow the same problem as the action bar title styles. They are special cases which need work arounds. I am unlikely to implement them now as they are depreciated.

**Comment by chrisjenx** [comment]
Not going to support Old TabText inside action bar as they are deprecated. Feel free to Fix and PR if required. Thanks.
