### ISSUE TITLE
Spannables do not work

### ISSUE THREAD

**Issue by inktomi** [chrisjenx/Calligraphy#128]
I'm not sure if this is related to #52 or not, however I have tried fixes referenced in that thread to no avail using v2.0.1. I'm assuming that we have conflicting or overlapping spans set via Calligraphy's text change watcher and my code (which runs in a fragment inside onActivityCreated).

The following code does not seem to work:

    final CharSequence textString = getResources().getString(R.string.string);
    SpannableString endText = new SpannableString(textString);
    endText.setSpan(new UnderlineSpan(), 21, textString.length(), Spanned.SPAN_INCLUSIVE_INCLUSIVE);
    endText.setSpan(new ForegroundColorSpan(getResources().getColor(R.color.red)), 21, textString.length(), Spanned.SPAN_INCLUSIVE_INCLUSIVE);
    mTextView.setText(endText);

We are setting up Calligraphy in our application as shown on the getting started page, and injecting the context wrapper in our activities. **I would expect that the text view above is shown in our font (it is), and that it ends with red, underlined text (it does not)**. 

Our text view is set up as such;

    <TextView
        android:id="@+id/text_view"
        style="?textAppearanceXLarge"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="8dp"
        android:layout_marginRight="8dp"
        android:layout_marginTop="?innerVerticalPadding"
        android:layout_marginBottom="?innerVerticalPadding"
        android:layout_above="@+id/linear_layout"
        android:gravity="center_horizontal"
        android:textAllCaps="true"/>

And the style referenced is only setting android:textSize - nothing strange or unique.

**Comment by chrisjenx** [comment]
I'm assuming this `Spannable` works when Calligraphy is not enabled? The only place spannables are used are on the Toolbar/ActionBar, they should work everywhere apart from that.

**Comment by chrisjenx** [comment]
@inktomi what I would note if you haven't fixed this is that `textAllCaps` applies a Spannable to the Text which messes up what we apply to the TextView see #42

**Comment by inktomi** [comment]
Ah, good point. I'll close this issue. Thank you!
