### ISSUE TITLE
Gradle: attribute fontPath already exists

### ISSUE THREAD

**Issue by Florent1510** [chrisjenx/Calligraphy#129]
Currently, there is a conflict with an other library which does also have a fontPath attribute, what stops the build process.

I copied the project (before I tried to build it) and stopped my network connection: The same issue happened. This means that no third-party library has been updated and that one of the Google libraries produces this issue.

**Comment by Florent1510** [comment]
Sorry, I forgot that it was in a library I programmed myself. Don't know why Gradle says that just now...

**Comment by chrisjenx** [comment]
That is odd, guess its a Android Gradle Tool bug. Thanx
