### ISSUE TITLE
Problem with custom view styles and Calligraphy?

### ISSUE THREAD

**Issue by abergenw** [chrisjenx/Calligraphy#130]
I'm having a hard time getting custom views (classes extending TextView) with styles working correctly with Calligraphy. The problem is that Calligraphy seems to ignore fontPath set in style definitions for these views.

A brief look at Android (API level 21) and Calligraphy (2.0.0) source code indicates that CalligraphyLayoutInflater may not apply the font if the view class is not in one of the following packages: android.widget, android.webkit and android.view. Is this correct?

**Comment by chrisjenx** [comment]
@abergenw that is incorrect. CustomView's do work.
They are routed slighlty differently, I actually wrote about the complexities of the LayoutInflater [here](http://chrisjenx.co.uk/calligraphy-2-0-0/).
Check the fontPath you have defined in the style has no namespace. The example works for you does it not? My personal project heavily uses custom views (and we exclusively apply attributes from styles).

**Comment by abergenw** [comment]
@chrisjenx thanks for the quick reply. I had a closer look at this now and I see what you mean.

However, I am still not able to get this working correctly and I am not sure why. Any help would be most appreciated. Here is what I have:

- A theme which is set for my activity
- A style extending the default style for EditText, providing (among other things) the fontPath
- A reference attribute which in my theme points to the style
- A custom view subclassing EditText, using the reference attribute as its style attribute (passing it to the parent constructor)
- A Fragment inflating a layout in its onCreateView(), the layout contains the custom view

What happens here is that all other style attributes (such as padding etc.) get set correctly from the custom style but not fontPath. Instead the default fontPath I have set when initing Calligraphy is used. If I don't use the custom view and use EditText directly, pointing android:editTextStyle in my theme to the custom style, then fontPath is applied correctly.

Another thing worth mentioning is that if I use my custom view and explicitly set the style in XML, then it works like expected.

**Comment by chrisjenx** [comment]
Ahh you are setting the style on the theme.

Can you post an excerpt of your styles. XML?

**Comment by abergenw** [comment]
The layout XML doesn't contain anything special:
```
<com.my.package.TextField
      android:id="@+id/email"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:layout_marginBottom="10dp"
      android:gravity="center"
      android:hint="@string/welcome_email_hint"
      android:inputType="textEmailAddress"
      android:imeOptions="actionGo" />
```

The reference attribute is declared as:

```
<attr name="textFieldStyle"
    format="reference" />
```

The theme is declared as:

```
<style name="ApplicationTheme"
    parent="android:Theme.Black.NoTitleBar">
    <item name="textFieldStyle">@style/TextField</item>
    ...
</style>
```

And then finally the style as:

```
<style name="TextField"
    parent="android:Widget.EditText">
    <item name="fontPath">@string/font_path_bold</item>
    <item name="android:textColor">@color/textfield_text_color</item>
    <item name="android:background">@drawable/textfield</item>

    <item name="android:paddingLeft">5dp</item>
    <item name="android:paddingTop">5dp</item>
    <item name="android:paddingRight">5dp</item>
    <item name="android:paddingBottom">5dp</item>
  </style>
```

**Comment by chrisjenx** [comment]
I'm not sure what `<item name="textFieldStyle">@style/TextField</item>` is. 
It should be `android:textViewStyle`.

**Comment by abergenw** [comment]
Setting `<item name="android:textViewStyle">@style/TextField</item>` is different from what I am trying to achieve. The TextField class I have (extending EditText) is set to use `textFieldStyle` as its default style attribute. This is why I link this reference attribute with the style definition, and as I want every instance of TextField to use a bold font I'm trying to set the fontPath in the style definition - without success.

**Comment by chrisjenx** [comment]
Ok @abergenw, I'm not sure how styles are being applied to your TextFields.
But Calligraphy will only be able to pick up `theme` styles from the `android:textViewStyle`.
E.g. `<item name="android:textViewStyle">@style/TextViewV3</item>`

Are you able to try using the built in attribute just to confirm?

**Comment by chrisjenx** [comment]
@abergenw I think I understand what you are doing now. You pass the style attr reference inside your `TextField` class. So that your `TextField` looks up against `textFieldStyle` for its default. 

Doing that will not work. We pull the parent styles based on what we know. See https://github.com/chrisjenx/Calligraphy/blob/master/calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyFactory.java#L28-L40.

We look up the direct `fontPath` on the View, then look for the Class type of that View. For you that would be `EditText.class` = `android.R.attr.editTextStyle`. For `textFieldStyle` as you're parent style we would need to inject `put(TextField.class, R.attr.textFieldStyle);` into that `Map` for style look ups.

If you still need this as a solution let me know and I can expand the calligraphy builder to take custom style attributes.

**Comment by abergenw** [comment]
@chrisjenx Yes this is what I'm doing. I thought that Calligraphy was somehow able to automatically find the style attributes used by views. I realize now that this is not how it works and probably View doesn't store the style attribute passed to its constructor so this would be impossible?

Anyhow, I think being able to pass custom View / style attribute mappings to CalligraphyConfig would be a nice-to-have feature. For my particular case it is ok to just set the font manually in the constructor of my custom views.

**Comment by chrisjenx** [comment]
OK I'll change it to a TODO then! :)

**Comment by mgrzechocinski** [comment]
Hey, do we have any update on this? I'm facing exactly the same issue and wondering what's the estimated time of implementing this?

**Comment by chrisjenx** [comment]
@mgrzechocinski not yet, I'll hopefully do it today.

**Comment by mgrzechocinski** [comment]
Cool! I'd appreciate :)

**Comment by chrisjenx** [comment]
I just pushed out a snapshot that should solve your problems. (2.1.0-SNAPSHOT).

Use as @abergenw above is. Add your custom class to the builder like:

```java
builder.addCustomStyle(TextField.class, R.attr.textFieldStyle)
//--
```

See the example in the PR too.

**Comment by mgrzechocinski** [comment]
Great. Will give it a try! :)

**Comment by flavioarfaria** [comment]
Hi guys,

I'm having exactly the same problem as @abergenw, with a small difference: I'm not using a custom view, I'm using a Button. Things work as expected on Android 5.1 but on 4.3 the *fontPath* attribute is completely ignored. I'm using the latest version of Calligraphy (2.0.2). This issue did not happen on 1.2.0.

It's also relevant to point out that adding `style="@style/Widget.MyApp.Button"` to the button fixes the issue.

###### my_layout.xml

    <Button
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:layout_margin="@dimen/view_margin"
            android:textAllCaps="true"
            android:text="@string/button_text"/>


###### themes.xml

    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:buttonStyle">@style/Widget.MyApp.Button</item>
    </style>

###### styles.xml

    <style
        name="Widget.MyApp.Button"
        parent="android:Widget.Button">

        <item name="android:minHeight">36dip</item>
        <item name="android:minWidth">64dip</item>
        <item name="android:paddingLeft">8dip</item>
        <item name="android:paddingRight">8dip</item>
        <item name="android:textColor">@color/btn_text</item>
        <item name="android:textSize">24sp</item>
        <item name="android:textAllCaps">true</item>
        <item name="fontPath">@string/the_hand_extra_black</item>
        <item name="android:background">@drawable/btn_primary</item>
    </style>

My layout file is being inflated into an Activity using `setContentView(int resId)`.

I'm not providing alternative resources for different Android versions, so I guess it's related to the library.

Thanks,
Flávio Faria

**Comment by chrisjenx** [comment]
@flavioarfaria hard to say without showing how you instantiate Calligraphy into you project. It sounds like a platform bug if it works fine on 5.1 but not on 4.3. Also worth noting, are you using `multidex` as that was breaking loads of libraries.

**Comment by flavioarfaria** [comment]
Thank you for your response @chrisjenx. Here is how I do it:

    final CalligraphyConfig config = new CalligraphyConfig.Builder()
                .setDefaultFontPath(defaultFontPath)
                .setFontAttrId(R.attr.fontPath)
                .build();

At first, I had the attribute `fontPath`declared in my `attrs.xml` (it was required in v1.x, if I'm not mistaken) and I thought it could be conflicting with the one currently included in the lib, but I removed my own attribute and it didn't help.

Regarding `multidex`, no, I'm not using it.

**Comment by chrisjenx** [comment]
You you shouldn't need your own `R.attr.fontPath` use the included ones
(unless you want to use a different name).

I am then assuming you are setting that using `CalligraphyConfig.
initDefault()`?

**Comment by flavioarfaria** [comment]
Yes, I am. Now I'm debugging into the lib to check what can be going on. My button is being inflated as a `TintButton`. I guess that the appcompat layout factory may be messing things up.

**Comment by flavioarfaria** [comment]
I guess I found the problem. CalligraphyFactory, line 60:

    styleIds[0] = sStyles.containsKey(view.getClass())
                        ? sStyles.get(view.getClass())
                        : android.R.attr.textAppearance;

Since my button is a TintButton, this code won't find an entry for it in the HashMap and it will pick the textAppearance attribute.

You should consider adding to the HashMap an entry for every tint view provided in the support library. All of them use the theme attributes of their parents, so that will be easy. :)

**Comment by flavioarfaria** [comment]
I was right, I just added the following entry to the map:

    put(TintButton.class, android.R.attr.buttonStyle);

Now it works as expected.

**Comment by chrisjenx** [comment]
Yeah that's cool you can add it manually using the builder whist I work on
adding them.

**Comment by paul-turner** [comment]
With #191 I think both issues raised here are now fixed (custom style attributes are available in 2.1) there is a 2.1.1 snapshot If you'd like to check @flavioarfaria

**Comment by flavioarfaria** [comment]
Yep, that indeed fixes it. Thanks @paul-turner!

**Comment by chrisjenx** [comment]
@flavioarfaria thanks for confirming, now closing.
