### ISSUE TITLE
Incorrect Ellipsis placement for multiline TextView

### ISSUE THREAD

**Issue by nathanielwolf** [chrisjenx/Calligraphy#132]
When ellipsizing multiline TextView's that use Calligraphy, the results look like the following about 20% of the time:

![screen shot 2015-02-06 at 8 19 35 am](https://cloud.githubusercontent.com/assets/1278688/6082826/f1a3bf2a-add8-11e4-8752-db17508949f0.png)

The xml used is:

```
  <TextView
      android:id="@+id/text"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:maxLines="4"
      android:ellipsize="end"
      fontPath="fonts/Lato-Light.ttf"
      tools:ignore="MissingPrefix"/>
```

Using solutions like Micah's here results in the TextView loosing it's custom font. 
http://stackoverflow.com/questions/2160619/android-ellipsize-multiline-textview

Any suggestions?

**Comment by chrisjenx** [comment]
Interesting. There was an issue with ellipsize on the ActionBar as we use Spans to set typeface on those, everywhere else we use native methods.

Calligraphy won't cause the above effect, we just call `setTypeface` on `TextView`s which in turn calls `setTypeface()` on `mTextPaint` in the `TextView`.

Looking at the linked solution, it's hard to decipher what is going on let alone what could potentially cause the issue. I would assume something like calling the `StaticLayout` is clearing (or overriding) the TextViews `Paint` object.

Someone else here might be able to spread some more light on the issue. As per usual this feels like an Android bug (although can't confirm that yet).

**Comment by nathanielwolf** [comment]
I agree ellipsizing multiline text in Android is buggy, hence the stackoverflow question and solution, so perhaps the issue is not with Calligraphy here.

Perhaps the reason why the EllipsizingTextView does not have the specified custom font is because we call 'builder.disableCustomViewInflation();` when initializing Calligraphy. Without calling this we get a crash in [Mortar](https://github.com/square/mortar)

The documentation of 'disableCustomViewInflation' states:
>But if you want Calligraphy to inject the correct typeface then you will need to make sure your CustomView's are created before reaching the LayoutInflater onViewCreated.

How can we insure a view is created before onViewCreated is reached?

**Comment by chrisjenx** [comment]
Have a look at the `ActionBarActivity#onCreateView`for an example.

Not sure why you need to disable it? I use mortar and calligraphy fine.

Create an issue with that stack trace so I can compare with my setup.

**Comment by nathanielwolf** [comment]
New issue for Mortar crash #132

**Comment by nathanielwolf** [comment]
Mortar crash issue created: #135

**Comment by chrisjenx** [comment]
So @nathanielwolf, If you enable `disableCustomViewInflation()` You'll need to inflate your custom views manually otherwise `Calligraphy` can not apply the `Typeface` to it.

e.g. `MyActivity`

```java
@Override
    public View onCreateView(final String name, @NonNull final Context context, @NonNull final AttributeSet attrs) {
        switch (name) {
            case "EllipsizeTextView":
                return new EllipsizeTextView(this, attrs);
        }
        return super.onCreateView(name, context, attrs);
    }
```
