### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by finneapps** [chrisjenx/Calligraphy#137]
I am getting this error from Crashlytics:

CalligraphyLayoutInflater.java line 162
uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView

Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.myapp.app.demo/com.myapp.ui.DetailsActivity}: android.view.InflateException: Binary XML file line #55: Error inflating class <unknown>

Caused by android.view.InflateException
android.view.LayoutInflater.createView (LayoutInflater.java:606)
uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView (CalligraphyLayoutInflater.java:162)
android.view.LayoutInflater.onCreateView (LayoutInflater.java:653)
uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView (CalligraphyLayoutInflater.java:146)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:678)
android.view.LayoutInflater.rInflate (LayoutInflater.java:739)
android.view.LayoutInflater.parseInclude (LayoutInflater.java:823)
android.view.LayoutInflater.rInflate (LayoutInflater.java:729)
android.view.LayoutInflater.rInflate (LayoutInflater.java:742)
android.view.LayoutInflater.inflate (LayoutInflater.java:489)
uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate (CalligraphyLayoutInflater.java:60)
android.view.LayoutInflater.inflate (LayoutInflater.java:396)
com.myapp.ui.DetailsFragment.onCreateView (DetailsFragment.java:319)
android.support.v4.app.Fragment.performCreateView (Fragment.java:1786)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:947)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1126)
android.support.v4.app.BackStackRecord.run (BackStackRecord.java:739)
android.support.v4.app.FragmentManagerImpl.execPendingActions (FragmentManager.java:1489)
android.support.v4.app.FragmentActivity.onStart (FragmentActivity.java:548)
com.myapp.ui.BaseActivity.onStart (BaseActivity.java:90)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1136)
android.app.Activity.performStart (Activity.java:4479)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:1941)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:1993)
android.app.ActivityThread.access$600 (ActivityThread.java:127)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1159)
android.os.Looper.loop (Looper.java:137)
android.app.ActivityThread.main (ActivityThread.java:4507)
java.lang.reflect.Method.invokeNative (Method.java)
dalvik.system.NativeStart.main (NativeStart.java)

From Device Name: GT-P7510
running Android 4.0.4

I guess the error is comming from Calligraphy?

**Comment by chrisjenx** [comment]
@finneapps doubtful. We try to inflate it. The class that is trying to be inflated fails. I would check the Line/View trying to be inflated. The fact that `android.view.LayoutInflater.createView (LayoutInflater.java:606)` is the line that throw's tells me it's unlikely to be `Calligraphy`. 

Some of the other issues have come down to `OOM` when trying to inflate. The fact that it's a samsung device also suggests that it is device specific. See #136 #131
