### ISSUE TITLE
Documentation: Fonts Path

### ISSUE THREAD

**Issue by akohout** [chrisjenx/Calligraphy#140]
This is just a small issue but I think it is not precise. In your Readme you write

"Add your custom fonts to assets/fonts/ all font definitions are relative to this path."

In all your examples and in your example project, this isn't the case. The library looks relative to the assets folder, not the assets/fonts folder.

But if you have plans on this to make this the default folder, I support that :) It's nasty to write fonts/*.ttf all the time.

**Comment by chrisjenx** [comment]
Appologies. I thought I changed that.. Must of got merged out at some point. I'll do it in a sec. Sorry about that.

**Comment by akohout** [comment]
No problem, it's a great library and your examples helped to figure out that this information is wrong :)

**Comment by chrisjenx** [comment]
Fixed this. Cheers.
