### ISSUE TITLE
Custom font in list item not working although I configure it in my application class?

### ISSUE THREAD

**Issue by mradlmaier** [chrisjenx/Calligraphy#143]
I am using application class to set a app-wide default font. This works nicely in most parts of the app, however in ListView's list item, the custom font is not applied. Here is what I have:

     public class XXXXXApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                        .setDefaultFontPath("fonts/Roboto-Thin.ttf")
                        .setFontAttrId(R.attr.fontPath)
                        .build()
        );
    }
    }

Because this is not working for my list items, I set it in the list item's layout, too, but it is not working:

    <?xml version="1.0" encoding="utf-8"?>
    <TextView xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:id="@+id/title"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:padding="6dp"
        android:textColor="@color/brown"
        android:textSize="24dp"
        fontPath="fonts/Roboto-Light.ttf"
        tools:ignore="MissingPrefix" />

Any suggestions?

**Comment by chrisjenx** [comment]
How do you inflate your `ListView` items. Can you paste your adapter code in? (Also check you are using 2.0.2).

**Comment by mradlmaier** [comment]
This is my adapter code:


        String[] uiBindFrom = { HundContract.Columns.NAME };
        int[] uiBindTo = { R.id.title };

        getLoaderManager().initLoader(HUND_LIST_LOADER, null, this);

        adapter = new SimpleCursorAdapter(
                getActivity().getApplicationContext(), R.layout.list_item,
                null, uiBindFrom, uiBindTo,
                CursorAdapter.FLAG_REGISTER_CONTENT_OBSERVER);

        setListAdapter(adapter);

And yes, I am using Version 2.0.2, with Android Studio and Gradle by including this in the dependencies:

        compile 'uk.co.chrisjenx:calligraphy:2.0.1'

**Comment by chrisjenx** [comment]
I'm assuming you meant?
```
 compile 'uk.co.chrisjenx:calligraphy:2.0.2'
```

Also, pass in `getActivity()` NOT `getActivity().getApplicationContext()`.
Always pass in the highest context available.

```java
 adapter = new SimpleCursorAdapter(
            getActivity(), R.layout.list_item,
            null, uiBindFrom, uiBindTo,
            CursorAdapter.FLAG_REGISTER_CONTENT_OBSERVER);
```

**Comment by mradlmaier** [comment]
Cool, this fixed it! Thanks!
