### ISSUE TITLE
How to use it in Paint while Drawing text In Bitmap

### ISSUE THREAD

**Issue by LOG-TAG** [chrisjenx/Calligraphy#144]
```
Paint textPain=new Paint();
textPaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
textPaint.setTextSize(fontSize2);
canvas.drawText(........................); 
```

**Comment by chrisjenx** [comment]
Is this a question? An example? Can you elaborate?

**Comment by luserdroid** [comment]
Hi, 

interesting. Is there a solution ?

**Comment by chrisjenx** [comment]
I have no idea what is being asked? So a solution will be tricky.

**Comment by luserdroid** [comment]
I think the initial question by LOG-TAG was, if there is a way by Calligraphy for adding a typeface in Canvas into drawText automatically.

**Comment by chrisjenx** [comment]
Right. OK. No way automatically. You will need to set the typeface on the
paint object. You can use the `TypefaceUtils` to make it a bit easier.

Calligraphy is designed to call `TextView.setTypeface()` by reading the
styled xml attributes during layout inflation.

If you are drawing inside TextView class you could call `getTypeface` and
use the typeface attributed to the TextView.

I am working on a typeface drawable that will work closely with calligraphy
that will do something similar.

**Comment by chrisjenx** [comment]
I do this internally:
```java
paint.setTypeface(TypefaceUtils.load(mContext.getAssets(), "fonts/AssetFont.ttf"));
```

**Comment by luserdroid** [comment]
Thanks for the answer +1 ;-)

**Comment by LOG-TAG** [comment]
Sorry for not responding !! @chrisjenx  thanks for the solution!!  and thanks for @luserdroid  to pointing out the question !!
