### ISSUE TITLE
Why is my custom action bar item font not displaying?

### ISSUE THREAD

**Issue by mradlmaier** [chrisjenx/Calligraphy#146]
In one of my activities the action bar item font is not displaying correctly. I had a similiar problem already, but the way I fixed it last time doesn't work.

So, what I have now:

    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_gewicht_activity, menu);
        return true;
    }

And here is my menu xml file:

    <?xml version="1.0" encoding="utf-8"?>
    <menu xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools">
        <item android:id="@+id/item_done"
            android:title="@string/done"
            fontPath="fonts/Roboto-Light.ttf"
            tools:ignore="MissingPrefix"
            app:showAsAction="always"></item>
    </menu>

I am using the version 2.0.2.

**Comment by mradlmaier** [comment]
This fixed it, I forget to add this method to my activity:

@Override
protected void attachBaseContext(Context newBase) {
    super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
}

**Comment by chrisjenx** [comment]
@mradlmaier OK cool, good to know :+1:
