### ISSUE TITLE
building calligraphy

### ISSUE THREAD

**Issue by to-kra** [chrisjenx/Calligraphy#150]
I was trying to build calligraphy over gradle but I am getting these errors:
DEBUG BUILD 2.0.2-SNAPSHOT

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':CalligraphySample'.
> A problem occurred configuring project ':calligraphy'.
   > Failed to notify project evaluation listener.
      > Could not resolve all dependencies for configuration ':calligraphy:_debugCompile'.
         > Could not find com.android.support:appcompat-v7:21.0.3.
           Searched in the following locations:
               https://repo1.maven.org/maven2/com/android/support/appcompat-v7/21.0.3/appcompat-v7-21.0.3.pom
               https://repo1.maven.org/maven2/com/android/support/appcompat-v7/21.0.3/appcompat-v7-21.0.3.jar
           Required by:
               Calligraphy:calligraphy:2.0.2-SNAPSHOT

**Comment by chrisjenx** [comment]
You have the Android Repository installed via the SDK manager right?

**Comment by to-kra** [comment]
I am using latest android-sdk_r24.1.2-windows SDK, what excatly should be downloaded via SDK Manager ? I mean there are lot of packages, some of them I got, but dont know which one is missing for Calligraphy ..

**Comment by to-kra** [comment]
I downloaded more things via SDK manager, and build is now successful, thx

**Comment by chrisjenx** [comment]
OK great, that was what I was going to suggest. I'll update Calligraphy
master to point at new build tools soon.
