### ISSUE TITLE
Arabic font being cut off (4.1.1/2)

### ISSUE THREAD

**Issue by khalid-hussain** [chrisjenx/Calligraphy#154]
Hi there,

I'm making an app purely and Arabic and have come to enjoy your library for changing fonts. You can see the app [here](https://github.com/khalid-hussain/MatnAjrumiyyah).

I'm getting some issues (besides the layout mirroring) when using Calligraphy (I'm not certain as to whether I'm doing something wrong of whether this library has some limitations I'm unaware of). The Arabic text seems to be cut off when using Calligraphy to change the font (XML in this case, haven't tried other methods). I've seen this on Android 4.1.1 and 4.1.2 (SDK v16). SDK v17 and above is fine.

Please see the screenshots (They get cut off in the second screenshot):
![](http://s25.postimg.org/piv97se8f/device_2015_04_01_123105.png)
![](http://s25.postimg.org/o3omly6tr/device_2015_04_01_123233.png)

Thanks for your time.

**Comment by chrisjenx** [comment]
@khalid-hussain very unlikely to be `Calligraphy`, All we do is call `setTypeface` on the `TextView`. I would probably guess is more to do with your font possibly?

**Comment by chrisjenx** [comment]
Any more info you can provide? Does this happen if you set the typeface not using `Calligraphy`?

**Comment by amorenew** [comment]
i think if you need to post your xml file

**Comment by khalid-hussain** [comment]
Sorry it took a while, was busy with a few other things.

@chrisjenx, my other [app](https://github.com/khalid-hussain/HisnulMuslim) changes font the regular way, I don't see any problems there, even though the layout there is different.

@amorenew, I've hosted the app on GitHub, [here](https://github.com/khalid-hussain/MatnAjrumiyyah/blob/master/app/src/main/res/layout/chapter_list_item.xml) is the layout.

**Comment by chrisjenx** [comment]
Not sure how well supported the .otf If this happens if you call `setTypeface()` manually, reopen.

**Comment by MohammadAftal** [comment]
I am  sorry I don't understand how this problem got solved I am facing the same thing.
I also noticed that in some text views setting an Arabic font is causing the  text to compress into a little space of the text view and the letters to overlap.
PS: this is true for all android versions below 5.x
