### ISSUE TITLE
Error: Could not find class 'android.support.v7.widget.Toolbar'

### ISSUE THREAD

**Issue by jjoseba** [chrisjenx/Calligraphy#156]
It happens at the startup of the app. After that, it works nicely, but this error always shows up.

This is the complete log related to this issue that appears in logcat:

	Could not find class 'android.support.v7.widget.Toolbar', referenced from method uk.co.chrisjenx.calligraphy.CalligraphyFactory.isActionBarSubTitle
	VFY: unable to resolve check-cast 998 (Landroid/support/v7/widget/Toolbar;) in Luk/co/chrisjenx/calligraphy/CalligraphyFactory;
	Could not find class 'android.support.v7.widget.Toolbar', referenced from method uk.co.chrisjenx.calligraphy.CalligraphyFactory.isActionBarTitle
	VFY: unable to resolve check-cast 998 (Landroid/support/v7/widget/Toolbar;) in Luk/co/chrisjenx/calligraphy/CalligraphyFactory;
	Could not find class 'android.support.v7.widget.Toolbar', referenced from method uk.co.chrisjenx.calligraphy.CalligraphyFactory.parentIsToolbarV7
	VFY: unable to resolve instanceof 998 (Landroid/support/v7/widget/Toolbar;) in Luk/co/chrisjenx/calligraphy/CalligraphyFactory;
	Could not find class 'android.support.v7.widget.Toolbar', referenced from method uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreatedInternal
	VFY: unable to resolve instanceof 998 (Landroid/support/v7/widget/Toolbar;) in Luk/co/chrisjenx/calligraphy/CalligraphyFactory;
	Could not find method java.lang.ReflectiveOperationException.printStackTrace, referenced from method uk.co.chrisjenx.calligraphy.ReflectionUtils.invokeMethod

**Comment by chrisjenx** [comment]
You are not using v7 support library, the Dalvik/ART VM's do this as they can't find that class. Don't worry about it.
