### ISSUE TITLE
Robolectric will not work with XML annotated fontPath declarations 

### ISSUE THREAD

**Issue by AdamMTGreenberg** [chrisjenx/Calligraphy#157]
In the method `getAttributeResourceValue(String namespace, String attribute, int defaultValue)` in Robolectric, it will go to fetch the name of the attribute, and then find it, but because there is no '@' prefixing the name, the part of the method
```
if (attr.startsWith("@")) {
        return getResourceId(attr.substring(1), packageName, null);
      }
```
which would normally get the resource ID fails. 

Thus I am unable to run unit tests on classes that inflate XML files that use Caligraphy

**Comment by chrisjenx** [comment]
This is an issue with Robolectric. You could probably get around this by putting your fonts in your `strings.xml` file though. 

Personally I stopped using Robolectric for UI, only and only for pure java. I would move to Espresso for UI tests.
