### ISSUE TITLE
Enable only for specific View's with a default font set

### ISSUE THREAD

**Issue by cbodin** [chrisjenx/Calligraphy#163]
Is there any way to make Calligraphy apply the default font on specific View classes or by manually filter it out? I'm using one custom font in my app which should be applied to all my Button's and TextView's, but i don't want it applied on Dialog's, Spinner's, Toast's etc.

A really neat way would be to add a config option to set what classes the default font would be applied to.

And thumbs up for a really great library!

**Comment by chrisjenx** [comment]
Just do this through styles and then set them on the theme.

If you are not sure what I mean let me know and I'll add an example.
