### ISSUE TITLE
Moto X Android 4.4.4 sudden Italic font in Action Bar

### ISSUE THREAD

**Issue by n-belokopytov** [chrisjenx/Calligraphy#166]
For some reason on Moto X on API 19 and on Motorola Droid the font in the Action bar gets all Italic, but the spacing for it remains as if it was regular. It leads to the text being cutoff in the end. Can be reproduced on Genymotion'x Moto X. These are the only devices so far that have that issue.
Any thoughts?

![screenshot_2015-05-05-11-34-00](https://cloud.githubusercontent.com/assets/6979232/7521590/4c7714e4-f4ef-11e4-8f24-04a94f6a5c23.png)

![img_07052015_190827](https://cloud.githubusercontent.com/assets/6979232/7521545/f0666902-f4ee-11e4-9632-b0b6a989c298.png)

**Comment by chrisjenx** [comment]
That is rather bizarre, There was an issue with Arabic fonts too relating to sizing. The only thing I can guess is that the wrong context is being passed to it.
But the fact that this happens on specific devices makes things odder. 

Does removing `fontPath` fix the issue? Or does just having Calligraphy in at all cause this.

**Comment by n-belokopytov** [comment]
Ok, so the issue is the bug with interpreting a certain style on Motorola devices - nevermind, there nothing we can do.

**Comment by chrisjenx** [comment]
Do you have a link to the issue? I'm interested.
