### ISSUE TITLE
Attribute have already defined

### ISSUE THREAD

**Issue by whmsysu** [chrisjenx/Calligraphy#169]
I used Gradle to import calligraphy, but It seems conflict with actionbar sherlock I used in the project.Could you tell me how to solve the conflict. This conflict only happens when I using the 2.1.0.

**Comment by chrisjenx** [comment]
I only have time to support the v7 `AppCompat` and `Toolbar`. If you find out what the cause is, feel free to send a PR, otherwise closing.
