### ISSUE TITLE
Custom view inflated in code doesn't get custom font

### ISSUE THREAD

**Issue by csdodd** [chrisjenx/Calligraphy#170]
I have a custom view with TextViews. Those TextViews have a custom font. If I include an instance of my custom view in XML as part of an activity the custom font will render correctly.

However, if I dynamically create an instance of my custom view the custom font is not applied.

    CustomView customView = new CustomView(context);
    this.addView(customView);

Inside of my custom view I am inflating the XML:

    LayoutInflater.from(context).inflate(R.layout.custom_view, this, true);

As I say, it works correctly unless I create the view dynamically at runtime. Is this a genuine issue or am I overlooking something?

**Comment by chrisjenx** [comment]
This is not an issue but an impossibility.
We set the Typeface through the `LayoutInflater`, if you do not _inflate_ your view the `LayoutInflater` is never executed.

No style gets set on the View instantiated pragmatically. **Always** Inflate views.

**Comment by csdodd** [comment]
I am slightly confused, and perhaps my initial explanation wasn't clear. When I instantiate my View programatically I inflate the view from XML inside the constructor of my custom View. Is this incorrect?

**Comment by fernandocosta** [comment]
has there been any progress on the issue?

**Comment by chrisjenx** [comment]
@csdodd OK can you send a full example through. The inflated views should get styles applied if the right context is passed to the LayoutInflater.

If you are able to provide example layout and code that would be helpful.

**Comment by csdodd** [comment]
Sure thing Chris, I will get a small example together. I will try and get it to you this evening.

**Comment by csdodd** [comment]
I just created a simple test case to showcase the problem and, of course, Calligraphy worked as expected! If I get the time I will try and see why I am seeing the problem in my other codebase. If anyone else is experiencing this problem they are welcome to try and create a reproducing case.

**Comment by chrisjenx** [comment]
OK Colin, I thought this sounded odd. It might be related to AppCompat.
They do weird things to the Inflater too. Maybe check you are inflating the
views at the same a depth. e.g. AppCompat -> SupportFragment -> CustomView
-> Inflate.

**Comment by csdodd** [comment]
I will check it out, but to be honest this issue should be closed because whatever problem I am seeing it is unrelated to the original description. If I do find an issue I'll open it seperately.

**Comment by chrisjenx** [comment]
OK thanks Colin, let me know when I can help.

**Comment by TarekkMA** [comment]
I had this issue if i set the `Context` to `getApplicationContext()` .
But I fixed it with `this` as context

**Comment by chrisjenx** [comment]
Yeah, that would make perfect sense. There should be a lint check for that.
