### ISSUE TITLE
Support for PagerTitleStrip

### ISSUE THREAD

**Issue by ciskeboekelo** [chrisjenx/Calligraphy#171]
Hi,

It would be nice if Calligraphy supported the android.support.v4.view.PagerTitleStrip

Right now I'm doing this:

        PagerTitleStrip pagerTitleStrip = (PagerTitleStrip) findViewById(R.id.pager_title_strip);
        for (int i = 0; i < pagerTitleStrip.getChildCount(); ++i) {
            View nextChild = pagerTitleStrip.getChildAt(i);
            if (nextChild instanceof TextView) {
                TextView textViewToConvert = (TextView) nextChild;
                textViewToConvert.setTypeface(myTypeFace);
            }
        }

**Comment by chrisjenx** [comment]
Ahh yes, The `TabStrip`'s pragmatically create `TextView`s. That is problematic. There are lots of edge cases like this which I really don't want to maintain.

Let me have a think, I'm glad the work around is working at least.

**Comment by chrisjenx** [comment]
Yeah I know why they haven't inflated these, because the v4 lib isn't an AAR.
