### ISSUE TITLE
Android 4.0.3, appcompat-v7:22.1.1 and calligraphy 2.1.0

### ISSUE THREAD

**Issue by jpop32** [chrisjenx/Calligraphy#172]
I managed to get snagged on a rather specific problem, but could be indicative of other issues. On Android 4.0.3 (and not on 4.0.4, which is also API level 15), when app is compiled with appcompat-v7 22.1.1 and calligraphy 2.1.0, onOptionsItemSelected() doesn't get called on child fragmetns (so app ends up without any icons in action bar (which is android.support.v7.widget.Toolbar set with setSupportActionBar()). I'll post more info as I gather it.

I rolled back to appcompat 22.0.0. and calligraphy 2.0.2 which works fine (but prevents me from enjoying the goodies in 22.1.1).

**Comment by chrisjenx** [comment]
That is very interesting. I'm guessing that 22.1.1 and no Calligraphy works as intended?

**Comment by chrisjenx** [comment]
Might sound like a stupid question. But you are inflating the child Fragments using the `getChildFragmentManager()`?

I have never tried Calligraphy with Child fragments.

**Comment by jpop32** [comment]
Nope, regular support fragment manager. Here's one example:

```java
        FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
        ft.add(R.id.desnaLadica, new RightDrawerFragment(), RightDrawerFragment.TAG);
        ft.commit();
```

Where RightDrawerFragment extends android.support.v4.app.Fragment, desnaLadica is LinearLayout as a drawer in v4 DrawerLayout. But it behaves similarly in other configurations too.

I don't have the device handy right now (home for the weekend), I'll test without calligraphy on Monday. Honestly, didn't occur to me to try, I came to consider calligraphy as an essential part of the platform. :-)

**Comment by chrisjenx** [comment]
Ha, yeah. I should add a troubleshooting guide. "Try without calligraphy
before posting an issue"

**Comment by jpop32** [comment]
Well, turns out you're right. After commenting out attachBaseContext override (so calligraphy doesn't get to do its magic) and using appcompat v22.1.1 the error is still there - no onOptionsItemSelected() call on 4.0.3.

Ok, I'm off to bother guys at Google, excuse my intrustion. :-)

**Comment by chrisjenx** [comment]
Heh, no worries. Thanks!
