### ISSUE TITLE
Toolbar subtitle isn't inflated right away

### ISSUE THREAD

**Issue by NSSJP** [chrisjenx/Calligraphy#173]
I ran into an issue where rarely the subtitle of my fragments wouldn't be using the correct font.

The issue seems to be that since I was using fragment transactions and since the first fragment in the activity didn't have a subtitle, the subtitle view was never added to the toolbar. (At least I think this is why since the Toolbar will only have one child in the callback from onGlobalLayout of CalligraphyFactory line 162) Then when I later switch in a fragment that has a subtitle the textview for it is created and Calligraphy doesn't catch it. A workaround I found for it is commenting out the following from CalligraphyFactory

`````
// Our dark deed is done
if (Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN) {
//noinspection deprecation
parent.getViewTreeObserver().removeGlobalOnLayoutListener(this);
} else {
parent.getViewTreeObserver().removeOnGlobalLayoutListener(this);
}
`````

But that goes back to #121 and #102 which isn't ideal. Is there a better way to accomplish this? I could potentially get the toolbar view, find the textview and set the font in these rare cases but I was hoping there would be an easy fix I just hadn't found yet that will allow Calligraphy to pick it up automatically

Other info:
This only started happening after switching from appCompat 19 to 22, I don't know if it happens on 21 but I can confirm if you think that'll help.
I'm using AppCompatActivity and I'm NOT setting the Toolbar and just letting the default one happen. I can try it the other way as well if you think that'll help

**Comment by chrisjenx** [comment]
You could probably work around this by setting the Subtitle to an empty string (`" "`), I need to check the impli but that should instantiate the subtitle and let the listener apply the typeface.

Let me know if that doesn't work.

**Comment by NSSJP** [comment]
If I set subtitle to an empty string it will be inflated but I then need to set it back to null or it'll be shown (i.e. shifting my title up to display nothing). The onGlobalLayout doesn't get called until after onResume of the activity so I'm still looking into whether I can set it back in my fragment onResume or something. I'll let you know if that works out

**Comment by chrisjenx** [comment]
Ahh yes, I forgot it does that. The global layout listener is called after the layout pass has finished. (onResume is approximately where its called as that is where the view is shown back to the user).

Of course your alternative is to use `Toolbar` and put titles inside that.

**Comment by NSSJP** [comment]
I'll probably move to use a Toolbar in the future but have a work around currently where the subtitle is set to an empty string initially and in the onGlobalLayout it'll set it to null if the subtitle is empty after setting up the view. Seems to be working well and I don't hate it as a temp fix until I get setup the toolbar everywhere.

**Comment by chrisjenx** [comment]
OK thanks. Yeah I wish there was a more elegant way to handle it. Wonder if there is a default way to build in your work around

**Comment by chrisjenx** [comment]
There is a new way of doing this in 2.1.1-SNAPSHOT, can you try and let me know.
