### ISSUE TITLE
MissingPrefix error no longer displays

### ISSUE THREAD

**Issue by dkozel** [chrisjenx/Calligraphy#174]
It appears that the erroneous Missing Prefix error has been fixed in Android Studio 1.2.1.1. Can anyone else confirm?

https://code.google.com/p/android/issues/detail?id=162884

**Comment by chrisjenx** [comment]
Still shows a warning for me. Anyone else?

**Comment by chrisjenx** [comment]
Not sure if this is an issue anymore?
