### ISSUE TITLE
Doesn't support the latest android.support.design.widget.NavigationView class

### ISSUE THREAD

**Issue by kevintanhongann** [chrisjenx/Calligraphy#175]
Here's the stacktrace that I got.

/AndroidRuntime(14264): Caused by: android.view.InflateException: Binary XML file line #42: Error inflating class android.support.design.widget.NavigationView
E/AndroidRuntime(14264): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
E/AndroidRuntime(14264): 	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
E/AndroidRuntime(14264): 	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
E/AndroidRuntime(14264): 	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
E/AndroidRuntime(14264): 	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
E/AndroidRuntime(14264): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
E/AndroidRuntime(14264): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
E/AndroidRuntime(14264): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
E/AndroidRuntime(14264): 	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
E/AndroidRuntime(14264): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/AndroidRuntime(14264): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
E/AndroidRuntime(14264): 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
E/AndroidRuntime(14264): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
E/AndroidRuntime(14264): 	at com.cardo.android.MainActivity.onCreate(MainActivity.java:34)
E/AndroidRuntime(14264): 	at android.app.Activity.performCreate(Activity.java:5937)
E/AndroidRuntime(14264): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
E/AndroidRuntime(14264): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
E/AndroidRuntime(14264): 	... 10 more
E/AndroidRuntime(14264): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(14264): 	at java.lang.reflect.Constructor.newInstance(Native Method)
E/AndroidRuntime(14264): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/AndroidRuntime(14264): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
E/AndroidRuntime(14264): 	... 26 more
E/AndroidRuntime(14264): Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
E/AndroidRuntime(14264): 	at android.content.res.Resources.getValue(Resources.java:1233)
E/AndroidRuntime(14264): 	at android.content.res.Resources.getColorStateList(Resources.java:931)
E/AndroidRuntime(14264): 	at android.support.design.widget.NavigationView.createDefaultColorStateList(NavigationView.java:338)
E/AndroidRuntime(14264): 	at android.support.design.widget.NavigationView.<init>(NavigationView.java:117)
E/AndroidRuntime(14264): 	at android.support.design.widget.NavigationView.<init>(NavigationView.java:88)
E/AndroidRuntime(14264): 	... 29 more

**Comment by ened** [comment]
What happens if you remove the context wrapper:
```
//    @Override
//    protected void attachBaseContext(Context newBase) {
//        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
//    }
```

Does the error still come up?

**Comment by ened** [comment]
@kevintanhongann I had the same problem, and solved it by adding the **app:itemTextColor** attribute to the view:

``` xml
<android.support.design.widget.NavigationView
    android:id="@+id/navigationView"
    android:layout_width="wrap_content"
    android:layout_height="match_parent"
    android:layout_gravity="start"
    app:headerLayout="@layout/menu_banner"
    app:menu="@menu/drawer"
    app:itemTextColor="@color/primary"/>
```

**Comment by chrisjenx** [comment]
Thanks @ened

**Comment by kevintanhongann** [comment]
@ened thanks man.

**Comment by squeeish** [comment]
@ened it was driving me crazy until I looked more closely at the stacktrace and came here. Thanks!

**Comment by ened** [comment]
@chrisjenx maybe close the issue now? :-) It doesn't have anything to do with Calligraphy, but because it pops up in the stacktrace, people naturally think it's related.

**Comment by Summonerrk** [comment]
it does not helps

**Comment by dwlrathod** [comment]
it doesn't help 
any other solution ?

**Comment by jzeferino** [comment]
Still getting this problem:

`Android.Views.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class android.support.design.internal.NavigationMenuItemView ---> Android.Views.InflateException: Binary XML file line #17: Error inflating class android.support.design.internal.NavigationMenuItemView ---> Java.Lang.Reflect.InvocationTargetException:  ---> Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.CheckedTextView.setDuplicateParentStateEnabled(boolean)' on a null object reference`

Any update on this @chrisjenx

**Comment by bhaktanishant** [comment]
Not worked for me

**Comment by PascalLzx** [comment]
Not worked for, I need help

**Comment by budhaayer** [comment]
not worked for me
