### ISSUE TITLE
Not working for new Support Design class TabLayout

### ISSUE THREAD

**Issue by raylee4204** [chrisjenx/Calligraphy#176]

**Comment by chrisjenx** [comment]
When you give more info I'll reopen.

**Comment by raylee4204** [comment]
Updated

**Comment by chrisjenx** [comment]
@raylee4204, just looked at the `TabLayout` impl, Tab's are added pragmatically. It is impossible to get a Inflation hook when creating `View`'s programmatically. This is unrelated to the `TabLayout`. Sorry I can't be more helpful. Looking at the API I can't see an exposed `setTypeface()`. Arg! Thanks Goog!

**Comment by kevintanhongann** [comment]
Actually, according to this article,
https://guides.codepath.com/android/Google-Play-Style-Tabs-using-TabLayout

Add Custom View to TabLayout section,

you can use getTabView and inflate your custom layout in it. Tried putting the fontPath attribute inside the custom view xml layout, but it didnt work. 

In the end I have to do something like this. Here's an example snippet.

public View getTabView(int position) {
            // Given you have a custom layout in `res/layout/custom_tab.xml` with a TextView and ImageView
            View v = LayoutInflater.from(getApplicationContext()).inflate(R.layout.layout_tabitem, null);
            TextView tv = (TextView) v.findViewById(R.id.textview_tabitem);
            switch (position){
                case 0:
                    tv.setText(mFeedTitleStr);
                    break;
                case 1:
                    tv.setText(mShopTitleStr);
                    break;
            }
            Typeface type = Typeface.createFromAsset(getAssets(),"fonts/AvenirNextCondensed-Medium.ttf");
            tv.setTypeface(type);
            return v;
        }

**Comment by iad24** [comment]
i found this one from stackoverflow:

private void changeTabsFont(TabLayout tabLayout) {
        ViewGroup vg = (ViewGroup) tabLayout.getChildAt(0);
        int tabsCount = vg.getChildCount();
        for (int j = 0; j < tabsCount; j++) {
            ViewGroup vgTab = (ViewGroup) vg.getChildAt(j);
            int tabChildsCount = vgTab.getChildCount();
            for (int k = 0; k < tabChildsCount; k++) {
                View tabViewChild = vgTab.getChildAt(k);
                if (tabViewChild instanceof TextView) {
                    ((TextView) tabViewChild).setTypeface(FontManager.getInstance().getCustomFont(), Typeface.NORMAL);
                }
            }
        }
    }

**Comment by chrisjenx** [comment]
Easy way to fix this, just inflate your own view and it works. There are
other tickets about this on here.

**Comment by iad24** [comment]
@chrisjenx yeah I tried other above. They got some side effects like font color disappearing, then gravity changed to left (instead of center). And got difficult time fixing them @_@
