### ISSUE TITLE
Issues when updating project to API 22 

### ISSUE THREAD

**Issue by zsperske** [chrisjenx/Calligraphy#177]
I know this is pretty open ended but I just want to start a discussion. First off, we found issues with an older version of this library after updating our google play services version, text stopped bolding properly when we applied a custom bold font. I updated the library, and our project to target API 22, and now I'm seeing words that we apply the bold font to being all caps.

**Comment by chrisjenx** [comment]
That's very open ended. 

Firstly "textStyle" doesn't actually work on some custom fonts it actually does a fake bold which renders horribly.

I'm not sure what else I can say without reproducible examples

**Comment by zsperske** [comment]
Yeah we don't use text style, in order to bold, we swap out the typeface for a bold typeface. I'll gather more data and try and get an example.

**Comment by zsperske** [comment]
Alright turns out that the button attribute textAllCaps defaults to true, so I don't think there's any issue here. Thanks for your hard work, great library!

**Comment by chrisjenx** [comment]
Ahh yeah part of Lollipop, Buttons are caps by default. Thanks!
