### ISSUE TITLE
Font not applied to child fragments?

### ISSUE THREAD

**Issue by MarsVard** [chrisjenx/Calligraphy#183]
I've been using this library and have been very happy with the way it works.

But I noticed that child fragments, fragments loaded using childfragmentmanager are not being "themed"

no default font and no custom fonts are being applied.

is this normal?

**Comment by chrisjenx** [comment]
@MarsVard, I'm not sure, I don't use child Fragments as they are pretty buggy. Not sure if someone else can help.

**Comment by balachandarlinks** [comment]
I used this lib with child fragments and everything looks fine !

**Comment by chrisjenx** [comment]
Thanks for checking :)
