### ISSUE TITLE
Facebook (SDK 4.1.x) login issue with Calligraphy

### ISSUE THREAD

**Issue by egurudutt** [chrisjenx/Calligraphy#184]
We were already using Calligraphy library without any problem,

BUT,

I just upgraded Facebook SDK to 4.1.0, 
It required me to upgrade Calligraphy to 2.0.2 version.

but it crashes and give different errors and does not allow to login , looks like most of time it is getting OOM issue.
My few crash logs are : 

http://pastie.org/private/hzchxttuf7ocrxqush1ya
http://pastie.org/private/4ahe8mtxovcihg4ml8zxow
http://pastie.org/private/5zbr6ifr6wy4jzy7qdxzba
http://pastie.org/private/5zbr6ifr6wy4jzy7qdxzba

If I down grade Calligraphy library to 1.0.x then Facebook login works fine but then all fonts are lost from all views :(
An if I upgrade Calligraphy then I get above errors :(

Any suggestion ?

Thank you,
--
Best Regards,
Gurudutt

**Comment by chrisjenx** [comment]
@egurudutt have you tried using the latest version?

**Comment by egurudutt** [comment]
Hi @chrisjenx 
Thank you for quick response.

yes I have tried latest version  2.1.0

same issue :(

**Comment by chrisjenx** [comment]
@egurudutt have you tried without Calligraphy? Also are you using MultiDex. These errors look unrelated to Calligraphy but more a Facebook/Dex issue?

**Comment by egurudutt** [comment]
@chrisjenx  I had sex issue last week but I removed couple library (.jars) and and issue was resolved.
but at current I am not using MultiDex ....... hmm... may be Facebook have some Dex support automatically ?

Calligraphy library to 1.0.x works without error but fonts are applied :(

I am checking Facebook Dex issue ....

**Comment by chrisjenx** [comment]
If you are hitting method limits then the newer version of calligraphy has
more methods.

None of the errors point at Calligraphy, I use the Facebook SDK with no
issues as well.

Maybe try multi dex and see if it goes away.

Cheers

**Comment by egurudutt** [comment]
Thank you @chrisjenx for quick response.

Just figured it out that issue was with calling AppsFlyerLib at wrong place.

All works so this issue can be discarded :)
sorry for hitting here , but I got idea to fix it though :)

**Comment by chrisjenx** [comment]
Ahh yeah I've heard that breaks the layout inflater. Sigh. No worries!
