### ISSUE TITLE
Fonts are not applied when using AppCompat and a theme

### ISSUE THREAD

**Issue by bherbst** [chrisjenx/Calligraphy#185]
When using Calligraphy with AppCompat, by default you cannot apply a font to some widgets such as `Button` and `EditText` using a theme.

For example, if you define the following theme, your `Button`s will use the default font:

```xml
<style name="Theme.FancyTheme" parent="Theme.FancyTheme">>
    <item name="android:buttonStyle">@style/Widget.Fancy.Button</item>
</style>

<style name="Widget.Fancy.Button" parent="android:Widget">
    <item name="fontPath">font/fancy_font.otf</item>
</style>
````

This is because AppCompat injects itself in the layout inflation process and replaces some components such as `Button` with AppCompat versions (e.g. `AppCompatButton`).

As a workaround, you can register the AppCompat versions of these widgets as having "custom styles" in Calligraphy like so:

```java
CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                        .setDefaultFontPath("fonts/fancy_font_default.otf")
                        .setFontAttrId(R.attr.fontPath)
                        .addCustomStyle(AppCompatButton.class, android.R.attr.buttonStyle)
                        .build()
);
````

Since this isn't an immediately obvious problem or solution, I believe that Calligraphy should register these by default, as it does with the framework `Button` classes and such.

This also doesn't work with text appearances for theme styles. For example, if I reference a text appearance style with a custom font  from `Widget.Fancy.Button`, the above workaround does not work- the button will still have the default font.

**Comment by chrisjenx** [comment]
Well the latter issue is separate I would raise that as a separate issue. As for the former. No. That would create a dependency in the project that would require checking if the `AppCompat` lib is available when not everyone would include it.
I will take a PR mentioning it in the docs though.

**Comment by bherbst** [comment]
You are [already including AppCompat](https://github.com/chrisjenx/Calligraphy/blob/e8fd3264a4a4b8ee5976d7c5d7ae9cc846a1a088/calligraphy/build.gradle#L34) in the project and [are checking if the user is using it](https://github.com/chrisjenx/Calligraphy/blob/e8fd3264a4a4b8ee5976d7c5d7ae9cc846a1a088/calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyFactory.java#L157).

I can add documentation surrounding this a little later though if that is the preferred method.

**Comment by hongzhou85** [comment]
@bherbst Where do you register the "initDefault" function? Is it in the overwriting Application class?

**Comment by bherbst** [comment]
@hongzhou85 Yes, I registered it in my Application class.

**Comment by paul-turner** [comment]
should be fixed now in #191 there is a 2.1.1 snapshot with those changes for you to check.

**Comment by Nammari** [comment]
Guy How can i get the snapshot for 2.1.1

**Comment by chrisjenx** [comment]
@Nammari  add:
```
maven {
            url "https://oss.sonatype.org/content/repositories/snapshots"
        }
```
to your gradle `buildScripts{`repositories{` closure.
