### ISSUE TITLE
Is there a way to define another path to load fonts, different from assets?

### ISSUE THREAD

**Issue by denebchorny** [chrisjenx/Calligraphy#188]
I had been reading the CALLIGRAPHY issues but I didn't found yet an answer for this kind of feature. Maybe could be my bad english to understand and find the correct keys for look up the answer. Sorry if this was answered before. 

Then, Is there a way to define another path to load fonts, different from assets? XD.

The Idea is to make and QUOTE APP where the user can select their own font. Then, I can make that the user select a font from his/her sd and QUOTE APP will copy it to a path where CALLIGRAPHY could load it.

Thanks in advance.

**Comment by chrisjenx** [comment]
Dup #100 #96
