### ISSUE TITLE
OutOfMemory on multiple orientation changes

### ISSUE THREAD

**Issue by sergthedeveloper** [chrisjenx/Calligraphy#196]
It seems that Calligraphy prevents drawables or layouts from being garbage-collected.
I have some heavy layout with many drawables in my activity.
When I added Calligraphy to the project, I faced memory leak and crash, caused by device rotation.

If I comment out this override
```
protected void attachBaseContext(Context newBase) {
    super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
}
```
all works just fine.

Any advice?

**Comment by chrisjenx** [comment]
Interesting, might be a memory leak somewhere. If you install https://github.com/square/leakcanary, does that catch it?

**Comment by sergthedeveloper** [comment]
I'll try
I think you can also reproduce it.
Just create view, that draws large bitmap on canvas (even no need to recreate that bitmap on orientation change, you can cache it)
I have almost similar activity and on my low end device (i test on LG Optimus L7 P705) it crashes every time after 5-10 rotations.
Without CalligraphyContextWrapper it doesn't :)

**Comment by chrisjenx** [comment]
Sure, it's just leak canary will let me know what is being held onto. :)

**Comment by chrisjenx** [comment]
I've tried with the sample. At a guess, this would be caused by the additional typefaces being loaded into memory which will push you into OOM sooner. I've checked for leaks (not saying there aren't any) but nothing immediate has come up.
