### ISSUE TITLE
Problem with colors in version 2.0.2

### ISSUE THREAD

**Issue by icsd** [chrisjenx/Calligraphy#197]
When I use Calligraphy 2.0.2 the colors of my Application are ok, but since I have updated to Calligraphy 2.1.0, the following happens :
1) In API 19 the following elements become white -> TextViews, EditTexts, simple_list_items, AlertDialog titles.
2) In API 21 the previously mentioned elements, become black.

I use AppCompat.Light theme in my App.

**Comment by chrisjenx** [comment]
Can you provide a full example?

**Comment by icsd** [comment]
In my application i use MaterialNavigationDrawer library: https://github.com/neokree/MaterialNavigationDrawer/wiki/Moving-to-MaterialNavigationDrawer

which uses Theme.AppCompat.Light theme.
With Calligraphy 2.0.2 my application looks like this in both 19 and 21 APIs:

![screenshot_2015-08-03-10-35-37](https://cloud.githubusercontent.com/assets/7528533/9032959/10c1d80e-39cc-11e5-8b2e-80b42781ea25.png)

![screenshot_2015-08-03-10-35-31](https://cloud.githubusercontent.com/assets/7528533/9032963/1597d37e-39cc-11e5-804a-9a9209ac4bab.png)


![screenshot_2015-08-03-10-35-17](https://cloud.githubusercontent.com/assets/7528533/9032964/189811ba-39cc-11e5-9c01-5faceaed91f2.png)

With Calligraphy 2.1.0 my app looks like this in API 19:

![screenshot alert dialog](https://cloud.githubusercontent.com/assets/7528533/9033235/fdac7722-39cd-11e5-9c76-5382398d5bd6.png)

![screenshot dialog](https://cloud.githubusercontent.com/assets/7528533/9033236/01623636-39ce-11e5-845a-b8d771065b53.png)

![screenshot_2015-08-03-10-35-31](https://cloud.githubusercontent.com/assets/7528533/9033239/063fd21c-39ce-11e5-8442-072c1d5ac0b7.png)


With Calligraphy 2.1.0 my app looks like this in API 21:

![screenshot_2015-08-03-10-56-00](https://cloud.githubusercontent.com/assets/7528533/9033350/ecc86730-39ce-11e5-97e4-edd4f9961d9e.png)

![screenshot_2015-08-03-10-56-07](https://cloud.githubusercontent.com/assets/7528533/9033351/f03023b8-39ce-11e5-8a99-adfbbde64d45.png)

![screenshot_2015-08-03-10-57-30](https://cloud.githubusercontent.com/assets/7528533/9033356/f37a7564-39ce-11e5-93a9-c0c7d751c462.png)

**Comment by chrisjenx** [comment]
Mmm. You'll need to paste more code. Worth noting I don't support that
library. And that appcompat has a few bugs in it with theming pre 21.
