### ISSUE TITLE
sample import to Android Studio 1.2.1.1

### ISSUE THREAD

**Issue by bayboraoren** [chrisjenx/Calligraphy#198]
Error:(1, 0) 
                    Plugin is too old, please update to a more recent version,
                    or set ANDROID_DAILY_OVERRIDE environment variable to
                    "c533e0b849e7c0c3babdd339b730c6b1ead4edd4"

**Comment by chrisjenx** [comment]
You probably need to Android Studio to 1.2+ the master branch works with AS 1.3, BuildTools 1.3 and Gradle 2.5.

**Comment by bayboraoren** [comment]
thank you
