### ISSUE TITLE
Error:(9) No resource identifier found for attribute 'fontPath' in package 'android'

### ISSUE THREAD

**Issue by roshu10** [chrisjenx/Calligraphy#207]
I added tools:ignore prefix. still i'm getting the error

This is my code:

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools" android:layout_width="match_parent"
    android:layout_height="match_parent" android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:ignore="MissingPrefix"
    android:paddingBottom="@dimen/activity_vertical_margin" tools:context=".MainActivity">

    <TextView android:text="@string/hello_world" android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:fontPath="fonts/Roboto-Bold.ttf"/>

</RelativeLayout>

**Comment by chrisjenx** [comment]
@roshu10 if you look at the example. `android:` is never prefixed to the `fontPath` attribute. 

It should be `fontPath="MyFont.ttf". Adding the Android prefix will mean it gets ignored by the LayoutInflater.
