### ISSUE TITLE
Release a new .aar file with the latest changes

### ISSUE THREAD

**Issue by Morji** [chrisjenx/Calligraphy#209]

**Comment by chrisjenx** [comment]
The latest changes are not concrete and are experimental thus not a solid release. The Toolbar fixes still present some issues.

**Comment by hzsweers** [comment]
Any update on this? The alternate workaround for toolbar fonts with handling `TintTypedArray` yourself isn't possible anymore with the latest support library since they've hidden it.

**Comment by chrisjenx** [comment]
Done, (Sorry for the delay) 2.2.0
