### ISSUE TITLE
Error when using Broadcast receiver

### ISSUE THREAD

**Issue by aditya2592** [chrisjenx/Calligraphy#211]
Hi,

I am getting a **uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper cannot be cast to android.app.ContextImpl** Runtime exception when trying to use a Broadcast receiver to listen to change in Network connectivity status. Can you help me with this?
Stacktrace is -

java.lang.RuntimeException: Unable to start receiver com.amazonaws.cognito.sync.demo.NetworkChangeReceiver: java.lang.ClassCastException: **uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper cannot be cast to android.app.ContextImpl**
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2452)
	at android.app.ActivityThread.access$1600(ActivityThread.java:150)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5283)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by chrisjenx** [comment]
Not without code, but sounds like you are using the wrong context. I'm getting blamed just because I am the top level context you are using.

**Comment by aditya2592** [comment]
This is the NetworkChangeReceiver Class - 

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.widget.Toast;

public class NetworkChangeReceiver extends BroadcastReceiver {

    @Override
    public void onReceive(final Context context, final Intent intent) {

        String status = NetworkUtil.getConnectivityStatusString(context);

        Toast.makeText(context, status, Toast.LENGTH_LONG).show();
    }
}

And I am putting this in my Activity as mentioned in the Instructions:
@Override
protected void attachBaseContext(Context newBase) {
    super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
}

**Comment by chrisjenx** [comment]
No idea, I'm using network and WiFi state listeners in multiple apps with no problems.

I would suggest you check how you start your broad cast receiver.

**Comment by chrisjenx** [comment]
Any more info on this, as I'm almost certain this is not related to Calligraphy.

**Comment by aditya2592** [comment]
I was registering the receiver in my Android manifest.xml file. Instead of doing that, declared and registered it in the custom Application class. That solved the problem

**Comment by chrisjenx** [comment]
OK that is weird as I never register receivers in the application class.
Thanks for letting me know.

**Comment by dallasgutauckis** [comment]
@chrisjenx I also came across this issue, but not directly via Calligraphy… a bug has been filed w/ the platform: https://code.google.com/p/android/issues/detail?id=200832

**Comment by dallasgutauckis** [comment]
FWIW, the difference is that a receiver registered in the manifest can be triggered by the platform even while the application isn't running. Registering the receiver at runtime is only useful while the process is running and the receiver is still registered

**Comment by aditya2592** [comment]
I received another Class cast exception. This time in an app where I am not using any broadcast receivers. Crash occurs for a particular device type only it seems as it has been reported by only 1 user so far. Refer to #249. 

@dallasgutauckis It seems to be similar to the platform bug you have referenced above

**Comment by chrisjenx** [comment]
@dallasgutauckis so is this a framework bug? and if so, is there a way I can work around this?

**Comment by dallasgutauckis** [comment]
@chrisjenx the way I got around it was implementing getSystemService() on Application itself instead of wrapping the base context…

**Comment by chrisjenx** [comment]
@aditya2592 Can I confirm you are setting 
```
@Override
protected void attachBaseContext(Context newBase) {
    super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
}
```
On your `Activity` NOT your `Application`?

**Comment by jamesddube** [comment]
Was having the same crash problem
 (CalligraphyContextWrapper cannot be cast to android.app.ContextImpl)
So i removed 
`@Override
protected void attachBaseContext(Context newBase) {
    super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
}`
from my application . It now works fine

**Comment by Nazmul56** [comment]
Thanks Crisjenx . Your answer solved my problem too.

**Comment by mimoccc** [comment]
This may help:
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/app/ContextImpl.java

**Comment by ivanboltyshev** [comment]
I found a solution, someone has already talked about it before.
Choose your App class that extends from Application.
And remove from there
`@Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
    }`
Next, your class should look like this

> public class App extends Application {

 >   @Override
>    public void onCreate() {
>       super.onCreate();
 >       CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
 >               .setDefaultFontPath("fonts/MM.ttf")
>                .setFontAttrId(R.attr.fontPath)
>                .addCustomViewWithSetTypeface(CustomViewWithTypefaceSupport.class)
>                .build()
>        );
>    }
>}
And declare it in manifest
`<application
android:name=".App"
......
</application>`
