### ISSUE TITLE
Calligraphy setup

### ISSUE THREAD

**Issue by rohanmahale** [chrisjenx/Calligraphy#215]
Using the builder class, we are able to set the default font type using 

    CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                        .setDefaultFontPath("fonts/Montserrat-Regular.otf")
                        .setFontAttrId(R.attr.fontPath)
                        .build()
        );

Is there a way,using the builder, to set different fonts for the different text styles. For example,  I need to use Montserrat-Regular.otf in the general case, and Montserrat-Bold.otf for textviews and other widgets which require bold text. Instead of directly setting attributes for individual views, can I use the builder to do this for me?

**Comment by chrisjenx** [comment]
No but if you read the readme, it supports `styles` & `textappearance`. Also look at the example code.

**Comment by rohanmahale** [comment]
Thanks Chris!
