### ISSUE TITLE
App crash on LG phones

### ISSUE THREAD

**Issue by aradetegen** [chrisjenx/Calligraphy#217]
The app crash on this LG phones
Optimus F6 (f6), LG Optimus G (geehrc4g), LG Lucid 2 (l1v)	, LG Optimus G Pro (geefhd)

Error log is 

10-09 18:39:42.358: E/AndroidRuntime(1244): FATAL EXCEPTION: main
10-09 18:39:42.358: E/AndroidRuntime(1244): java.lang.RuntimeException: Unable to start activity ComponentInfo{…..SplashActivity}: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.app.ActivityThread.access$600(ActivityThread.java:130)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.os.Looper.loop(Looper.java:137)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at java.lang.reflect.Method.invoke(Method.java:511)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at dalvik.system.NativeStart.main(Native Method)
10-09 18:39:42.358: E/AndroidRuntime(1244): Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:5612)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1809)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1721)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:58)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:748)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2784)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2844)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1542)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:148)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at ……MMAbstractActivity.onCreate(MMAbstractActivity.java:67)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at …….SplashActivity.onCreate(SplashActivity.java:43)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.app.Activity.performCreate(Activity.java:5008)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
10-09 18:39:42.358: E/AndroidRuntime(1244): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)

**Comment by fingertricks** [comment]
I doubt this is a Calligraphy issue. Are you sure you aren't using a margin or padding attribute that's not available on a particular SDK version? See http://stackoverflow.com/questions/14454024/android-app-crashes-on-htc-and-sony-ericsson-phone I suspect the crash reports are coming from a limited subset of Android versions?

**Comment by chrisjenx** [comment]
As @fingertricks mentioned @aradetegen, this is a device/view issue, Calligraphy just gets blamed as thats the "known" class in the stack trace.
