### ISSUE TITLE
Font not set in some activities while setting text in TextView programatically

### ISSUE THREAD

**Issue by juan-pvb** [chrisjenx/Calligraphy#218]
Hi,

I found a problem using the last release 2.1.0 that, however, it's not occurring in 2.0.2.

Basically, I have two activities, let's call them "main" and "secondary", on the main activity, all the fonts are set properly, however, on the secondary, the fonts that are set with tv.setText("bla, bla"), for instance,  are wrong. If the text is set on the XML directly, it works fine.

Regards,

Juan

**Comment by chrisjenx** [comment]
Calligraphy calls `setTypeface` on the `TextView` what I would suggest is that you check you have the correct `fontPath` applied to the xml in the Second Activity. 

And when you say `tv.setText` are you talking about Views you have inflated or the Toolbar/ActionBar?

**Comment by sjyeyifan** [comment]
Hi,the same problem.the code ↓
// -------------- The BaseActivity.java ------------------
    @Override
    public void setContentView(int layoutResID) {
        View view = mLayoutInflater.inflate(layoutResID, null);
        view.setLayoutParams(new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT));
        
        mContentLayoutView.addView(view);
        super.setContentView(mBaseLayoutView);
    }
// ---------------------------------------------------------------
↑ not work.

**Comment by chrisjenx** [comment]
Where is `mLayoutInflater` coming from? If the LayoutInflater is not from your activity and you haven't wrapped the base context then it will not work. 

Just remember you need to wrap every activites base context. Not just the first one.

Post complete examples as that is still very unclear what you are doing.

**Comment by sjyeyifan** [comment]
Thanks,The problem has been solved.
before:
mLayoutInflater = LayoutInflater.from(this.getApplicationContext()); → not work
now:
mLayoutInflater = LayoutInflater.from(this); → ok

thank you again.

**Comment by chrisjenx** [comment]
Yes that would do the trick :)
