### ISSUE TITLE
Font not set properly in Dialogs

### ISSUE THREAD

**Issue by juan-pvb** [chrisjenx/Calligraphy#219]
Hello,

I'm using a separate class to make custom dialogs which uses internally the Dialog class.
This is called from an activity and the context is passed with the "this", for instance:
        mDialog = new AlertDialog();
        mDialog.showOKActionDialog(this, getResources().getString(R.string.warning), getResources().getString(R.string.server_error), this) 

The fonts are not set as stated in the XML for the dialog. 
I also tried to set the font programmatically like:

TextView tv = (TextView) findViewById(R.id.appname);
Typeface face = Typeface.createFromAsset(getAssets(),
            "fonts/epimodem.ttf");
tv.setTypeface(face);

but it didn't work either.

Any idea how to get the font on the dialog using Calligraphy?

Thanks!

**Comment by chrisjenx** [comment]
I would make sure you are passing the correct context though to your dialog.
