### ISSUE TITLE
missing xml namespace

### ISSUE THREAD

**Issue by gabriel-fortin** [chrisjenx/Calligraphy#221]
When using the `fontPath` attribute in xml files many IDEs will mark it as incorrect. It's caused by a missing namespace prefix. Currently, the recommended workaround is to add the `tools:ignore="MissingPrefix"` attribute to suppress the error.

It would be better to create a namespace for the `fontPath` attribute. The following article may be of much help to achieve that: http://kevindion.com/2011/01/custom-xml-attributes-for-android-widgets/

**Comment by chrisjenx** [comment]
@gabriel-fortin that won't work in this case, Those Custom XML attributes are for CustomViews, we are injecting an attribute with already existing views (in most cases). So the fontPath isn't really associated with any `View` we can usually resolve it.

Thanks for taking the time to look tho.

**Comment by hannesstruss** [comment]
@chrisjenx FWIW, adding a custom namespace (e.g. `app`, defined like `xmlns:app="http://schemas.android.com/apk/res-auto"`) to the `fontPath` attribute removes the lint error *and* still replaces the font. Could this explode somewhere/in some cases?
