### ISSUE TITLE
Attribute 'color' has already been defined

### ISSUE THREAD

**Issue by anirvan-majumdar** [chrisjenx/Calligraphy#222]
Hello,

I was trying to include the calligraphy dependencies (`uk.co.chrisjenx:calligraphy:2.1.0`) into my project, when I encountered this particular error. 

It appears that somewhere in the Calligraphy dependency, the attribute `color` is being defined, and this causes a conflict later in the build stage. The tag in question looks to be:

```
<declare-styleable name="DrawerArrowToggle">
    <attr format="color" name="color"/>
    <attr format="boolean" name="spinBars"/>
    <attr format="dimension" name="drawableSize"/>
    <attr format="dimension" name="gapBetweenBars"/>
    <attr format="dimension" name="topBottomBarArrowSize"/>
    <attr format="dimension" name="middleBarArrowSize"/>
    <attr format="dimension" name="barSize"/>
    <attr format="dimension" name="thickness"/>
</declare-styleable>
```

I'm using the following config in my build file:

```
compileSdkVersion 22
buildToolsVersion '23.0.1'

compile 'com.google.android.gms:play-services:8.1.0'
compile 'com.android.support:support-v4:23.1.0'
compile 'uk.co.chrisjenx:calligraphy:2.1.0'
```

If I try to build by removing the `calligraphy` dependency, everything works just fine.

Is there something I can do to fix this issue?

Thanks so much,
Anirban

**Comment by chrisjenx** [comment]
I don't define the `color` attribute, I only mark the support lib stuff as provided in the lib. 

The output of the arr is like so:
```
<resources>
    <!-- From: file:/Users/chris/Git/chrisjenx/Calligraphy/calligraphy/src/main/res/values/attrs.xml -->
    <eat-comment/>
    <attr format="string" name="fontPath"/>
    <!-- From: file:/Users/chris/Git/chrisjenx/Calligraphy/calligraphy/src/main/res/values/ids.xml -->
    <eat-comment/>
    <item name="calligraphy_tag_id" type="id"/>
</resources>
```
I would guess you have a dependency conflict. I would "force" your play services and support-v4.

**Comment by anirvan-majumdar** [comment]
@chrisjenx — my deepest apologies, but I've been able to resolve this issue, and it is NOT related to **Calligraphy**. The actual issue was triggered by incorporating the `app-compat-v7` library (surprisingly `support-v4` had no issues with it!).

I've detailed out the solution in [this StackOverflow post](http://stackoverflow.com/questions/33551324/android-migration-to-appcompat-v7-causes-error-attribute-color-has-already-be).

Once again, my apologies for needlessly taking up your mindspace.

**Comment by chrisjenx** [comment]
Haha, no worries glad you fixed it :)

**Comment by arashsammak** [comment]
compile('uk.co.chrisjenx:calligraphy:2.1.0') {
        exclude module: 'appcompat-v7'
    }

appcompat-v7 or DesignLibrary or ....

**Comment by chrisjenx** [comment]
I thought it would be along those lines.
