### ISSUE TITLE
Wrap dialog boxes called from activity, But should be manual

### ISSUE THREAD

**Issue by mchenani** [chrisjenx/Calligraphy#223]
I have an activity and wrapped the context with the way directed in documents of whit great project. in this activity I call another dialogFragment that has another specific font but same font of parent activity is set to dialog. Please help me to fix this.

**Comment by chrisjenx** [comment]
You'd need to pass the wrapped context to the LayoutInflater as the activity context gets wrapped. Otherwise the LayoutInflater is passed the wrong context.

You're going to need to provide a clearer explanation and code if you want any help as the above question makes no sense.
