### ISSUE TITLE
NoClassDefFoundError while loading my activity

### ISSUE THREAD

**Issue by mSobhy90** [chrisjenx/Calligraphy#224]
Awesome library, makes custom fonts a breathe.
Work fine on my testing device (Nexus 5 running M) but crashed with the following stack trace on a Samsung (no surprise there) device (GT S7272 running 4.2.2)
Any ideas?
```
Fatal Exception: java.lang.NoClassDefFoundError: uk.co.chrisjenx.calligraphy.R$attr
       at uk.co.chrisjenx.calligraphy.CalligraphyConfig$Builder.<init>(CalligraphyConfig.java:150)
       at net.sarmady.contactcarswithtabs.ContactCarsApplication.onCreate(ContactCarsApplication.java:145)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4552)
       at android.app.ActivityThread.access$1400(ActivityThread.java:150)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5279)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by chrisjenx** [comment]
Going to need to give me a bit more than that! 

This is probably a multidex or packaging issue. Using gradle? Latest build tools? etc..

**Comment by Mathbl** [comment]
Happens to me a bit randomly on a Samsung (Galaxy Nexus) Device running 4.2.1.

I'm using MultiDex. I have two flavors. One that is minSdkVersion 21 and another minSdkVersion 15.

When I develop on my Nexus 5 I use the first one for faster multidex build. Sometimes, I give a go at the Galaxy Nexus to check whether everything still works fine on it. So I switch to the second flavor. I usually do a clean project and launch the app.

The app crashes on start on the Galaxy Nexus with `java.lang.NoClassDefFoundError: uk.co.chrisjenx.calligraphy.CalligraphyConfig$Builder`

If I try to launch the app multiple times, it randomly works after multiple try.

**Comment by fingertricks** [comment]
Sounds like a multidex issue.

What build tools, gradle & android studio versions are you using?

**Comment by fingertricks** [comment]
And are you using proguard?

**Comment by Mathbl** [comment]
Yes I agree it seems to have something to do with Multidex. I'm still new to it, and do not know everything it does in the background.

I'm not using proguard.
```
buildToolsVersion "23.0.2"
com.android.tools.build:gradle:2.0.0-alpha2
Android Studio 2.0 Preview 3b 
```
All the latest versions actually.

**Comment by fingertricks** [comment]
Android Studio preview is in Beta. I'd hedge my bets that's the source of your problems

**Comment by fingertricks** [comment]
Try turning off incremental builds in AS.

**Comment by Mathbl** [comment]
Yes, with Instant run and all the new things, there's possibly a conflict with that (though it's not supposed to be running on device under Lollipop).

I just turned off instant run, switched to my second flavor, cleaned project, started on my Galaxy Nexus 4.2.1, and it worked first shot. 

So you potentially tracked down the issue. I'll try to give update when Studio 2.0 launches as RC. Thanks

**Comment by fingertricks** [comment]
You're welcome Mathbl. A good rule of thumb with previews is try reverting back to stable versions and disable experimental features.

**Comment by chrisjenx** [comment]
There is an alpha3 and an alpha4 around the corner I would give those a
shot when you have a min.

**Comment by Mathbl** [comment]
I didn't realize there was a newer version. With instant run activated, it still crashes on alpha 3.

At least, now that I know the possible culprit, I'm alright with that.

**Comment by chrisjenx** [comment]
OK, thats good to know, not sure what the issue is, when it hits beta I'll
raise a bug report to the tools team.

**Comment by Pedramrn** [comment]
I have same issue with multidex but with gradle build tools 1.5.1 and AS 1.5.1

**Comment by chrisjenx** [comment]
Check you are innit multi dex correctly.

I use multi dex and Calligraphy and have no problems.
Also check your build tools version. They did a multidex fix a while back.

**Comment by rajashripawar11** [comment]
I am facing same issue on Android device 4.0
I use both multi dex and Calligraphy.
Min sdk version is 15, buildToolsVersion "23.0.1"

![error_log](https://cloud.githubusercontent.com/assets/7781035/14666318/89d58d56-06f6-11e6-99eb-3965769d5ff1.png)

**Comment by chrisjenx** [comment]
Again turn off instant run, check multidex 1.0.1 is in use and check that you are calling MultiDex.init() _Before_ Calligraphy config.

**Comment by rajashripawar11** [comment]
Checked... 1) Not using Android studio 2.0 so no instant run
2) Multidex 1.0.1 is in use
3) Calling Multidex.init() in attachBaseContext method of Application class & Calligraphy config calling in onCreate of Application class.
Still facing issue.

**Comment by chrisjenx** [comment]
Build tools 23.0.3 ?

**Comment by rajashripawar11** [comment]
No... It's  23.0.1

**Comment by chrisjenx** [comment]
Sure, have you tried updating to 23.0.3!

**Comment by zy1301529626** [comment]
when i use calligraphy in eclipse , always show java.lang.NoClassDefFoundError: uk.co.chrisjenx.calligraphy.R$attr, and the  sdk is API17(4.2.2) 
 can you tell me how to solve it ?

**Comment by voidstarfire** [comment]
Getting the same problem. NoClassDefFoundError on 4.4.4
Tried all the solutions.

**Comment by chrisjenx** [comment]
@voidstarfire Check you are using the latest build tools, platform tools, version of gradle, multi dex etc...

**Comment by voidstarfire** [comment]
Here are my settings
App Module:
compileSdkVersion 25
buildToolsVersion '25.0.0'
minSdkVersion 15
targetSdkVersion 25

compile 'com.android.support:multidex:1.0.1'
compile 'uk.co.chrisjenx:calligraphy:2.2.0'

Error:
```
java.lang.NoClassDefFoundError: uk.co.chrisjenx.calligraphy.CalligraphyConfig
at uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper.<init> (CalligraphyContextWrapper.java:86)
at uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper.wrap(CalligraphyContextWrapper.java:31)
at itslearning.app.common.BaseApplication.attachBaseContext(BaseApplication.java:56)
```

My base application context is attached like so (Because I use Roboelectic for testing)

```
protected void multidexInit() {
        try {
            MultiDex.install(this);

        } catch (RuntimeException multiDexException) {
            // Work around Robolectric causing multi dex installation to fail, see
            // https://code.google.com/p/android/issues/detail?id=82007.
            boolean isUnderUnitTest;

            try {
                Class<?> robolectric = Class.forName("org.robolectric.Robolectric");
                isUnderUnitTest = (robolectric != null);
            } catch (ClassNotFoundException e) {
                isUnderUnitTest = false;
            }

            if (!isUnderUnitTest) {
                // Re-throw if this does not seem to be triggered by Robolectric.
                throw multiDexException;
            }
        }
    }
```

**Comment by chrisjenx** [comment]
And do you call multi dex before anything else? You seem to be missing your
application class.

**Comment by voidstarfire** [comment]
Still an issue. I've also noticed that this utility is missing some text fields (ViewPagers, Certain spannables). I went though the source code and I see you're using Reflection. Maybe a mixture of the build tools deprecating a class is causing this.

**Comment by chrisjenx** [comment]
@voidstarfire and where is `MultidexInit()` called?

You have to have a strict order when calling `Multidex`.

```
@Override protected void attachBaseContext(Context base) {
    super.attachBaseContext(base);
    initMultiDex();
  }
```

```
@Override public void onCreate() {
    super.onCreate();
    initCrashlytics();
    initStrictMode();
    buildGraph();
    // -- etc
    initCalligraphy();
    //--- etc

  }
```

You also need to call Multidex in the App Module not in a library module.
Also check your platform and sdk tools are up-to-date. The build tools are gradle specific, platform tools include aapt and the dexer etc..

There is a proguard config in the library, but worst case add this to your end proguard config.

**Comment by voidstarfire** [comment]
I was calling them as expected except I was calling `super.attachBaseContext(base);` with the Calligraphy initializer.

This only seems to crash on old devices running 4.4.4 (Samsung's we have in our test lab)

**Comment by brandall76** [comment]
Same here on an old test device - Samsung Galaxy S3 4.4.4. It is running a CyanogenMod though, so can't rule out an issue with the build....

Treble checked setup and working fine on other devices.

**Comment by chrisjenx** [comment]
I'll see if I can get access to any data from other companies using it see if they have seen anything similar, personally we have 600k+ users and have never seen this - it could be that we don't have that specific model and device running the App... but that would be statistically slim - something I will check.

**Comment by brandall76** [comment]
@chrisjenx thank you; I agree it's unlikely.... Thank you also for publishing such a useful library!
