### ISSUE TITLE
Switch view setSwitchTypeface

### ISSUE THREAD

**Issue by revaultch** [chrisjenx/Calligraphy#225]
The Switch view has two type faces one for the label text and one for the text displayed in the switch itself. I wonder if Calligraphy should set both, currently it only sets the label text, but this can be wanted behaviour, but unfortunately doesn't seem documented. 
Any hints, ideas on this?

**Comment by chrisjenx** [comment]
The platform one has a separate method called `setSwitchTypeface`, We only look for `setTypeface` as that is a method defined by the `TextView` class. 

This would be one of those "special cases" which I am trying to avoid at the moment otherwise the project will be full of these little hacks.

**Comment by revaultch** [comment]
Ok. Thank you. Is there a list of those cases somewhere? I could add it to the FAQ via pull-request, but this is the only one I encountered as of now.

**Comment by chrisjenx** [comment]
No list, there is an open issue for text style on the text layout tho.
Would appreciate the exceptions list :)
