### ISSUE TITLE
fontPath not working after upgrading the android studio to 2.0 and build tools to 23.0.2

### ISSUE THREAD

**Issue by bhagyalakshmi** [chrisjenx/Calligraphy#226]
I set up Calligraphy in my application class and then calling attachBaseContext in the activity and using custom fonts for TextView by using fontPath attribute. It worked till today. 

I have upgraded to latest version of android studio and build tools, then Calligraphy approach of setting custom font is not working.

**Comment by chrisjenx** [comment]
> `attachBase` the first of my views

I'm not sure what you mean by that?

**Comment by chrisjenx** [comment]
Oh FYI, I'm using the new build tools `2.0.0-alpha1` too, and it works fine. I would suggest its a config issue. Look at the sample project more carefully.

**Comment by bhagyalakshmi** [comment]
Thanks for your help
Default font path is getting applied, even we set our custom font by using fontPath attribute.

Here I am providing my code snippets
In Application class: 
CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
						.setDefaultFontPath("fonts/Roboto-Bold.ttf")
						.setFontAttrId(R.attr.fontPath).build()
Injecting context in activity:
@Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
    }
In XML: 
 <TextView
                    android:id="@+id/correct_icon"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginRight="2dp"
                    android:layout_marginLeft="15dp"
                    android:text="@string/fa_check"
                    fontPath="fonts/fontawesome-webfont.ttf"
                    android:textSize="30dp"
                    android:textColor="@color/green"
                    android:layout_gravity="center_vertical" />

**Comment by chrisjenx** [comment]
How does your application class look, need to see where you create the
config. Thanks.

**Comment by bhagyalakshmi** [comment]
I am creating the config inside onCreate() of Application class.

@Override
	public void onCreate() {
		super.onCreate();
        CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                .setDefaultFontPath("fonts/fontawesome-webfont.ttf")
                .setFontAttrId(R.attr.fontPath)
                .build()
        );
analytics = GoogleAnalytics.getInstance(getApplicationContext());
PolaEventManager.init(this);
RequestQueueManager.initRequestQueue(getApplicationContext());
}

**Comment by chrisjenx** [comment]
OK, might be an issue with instant run on pre lollipop devices.

1. Try turning off instant run
2. Use a newer emulator API 21+

**Comment by bhagyalakshmi** [comment]
With instant run turned on/off and using an emulator API 22 also not working.
Tried CalligraphyConfig.initDefault in an activity, then also the default font is getting applied to that activity but not the custom one.

Not sure what to do If I need two different fonts in an activity.

Is there any config do I need to set?, looks like this issue is similar to #71 

FYI tried sample app with latest version of build tools and grade:
 1. it worked properly.  
 2. I have removed .setFontAttrId(R.attr.fontPath) in application class, then also custom fonts are getting rendered properly.

Not really sure what's happening in my application.

**Comment by bhagyalakshmi** [comment]
Looks like attachBaseContext(CalligraphyContextWrapper.wrap(newBase)); is not working

**Comment by chrisjenx** [comment]
This must be a weird issue with your project then. Or potentially the
packager. As 2.0.0 is an alpha right now. If it's not fixed going forwards
let me know and we can investigate.

Just odd as it works fine for me. :/

**Comment by bhagyalakshmi** [comment]
Finally I found like it's not working with proguard, it worked with debug build and release build without proguard.

Can we get proguard config for calligraphy?

**Comment by chrisjenx** [comment]
Interesting, OK. I'll give this a go today. It should just work™ but I
haven't tried. I guess it might be striping out the reflection stuff.

**Comment by chrisjenx** [comment]
@bhagyalakshmi I've just updated the sample to enable proguard, Calligraphy still works as intended. Any more info about your setup? Also you upgraded to 2.0.0-alpha2?

**Comment by migore** [comment]
Hey, I got the same issue.


I made a example project here:
https://github.com/migore/CalligraphyExample
My steps were:
1. Created a new project
2. Added calligraphy dependency in build.gradle
3. Create another TextView in content_main.xml
4. Added same rules from CalligraphySample in proguard-rules.pro

**Comment by chrisjenx** [comment]
That sample never would work, you're missing the attachBaseContext override.

**Comment by migore** [comment]
Argh. You are totally correct. My bad not properly reading the readme. Thanks!

**Comment by chrisjenx** [comment]
@migore does it work as intended after adding the override?

**Comment by chrisjenx** [comment]
Actually @bhagyalakshmi if you are able create a sample project that highlights the issue you are having that would be tremendously helpful. Most apps have a variety of moving parts so it could be a number of things.

**Comment by migore** [comment]
@chrisjenx Yes. Works like a charm!

**Comment by aya-salama1989** [comment]
@bhagyalakshmi ,
clarify the path of your font class as the new application name in the manifest like so;

  <application
        android:name=".Utilities.Font"
../>
