### ISSUE TITLE
Memory leak found using LeakCanary

### ISSUE THREAD

**Issue by ShkurtiA** [chrisjenx/Calligraphy#227]
Hello I am using calligraphy:2.1.0 and I am using LeakCanary to detect memory leaks. This is the log for the leak:

In com.liburnia.classroom:1.0:1.
* com.liburnia.classroom.activity.ClassRoomActivity has leaked:
* GC ROOT uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper.mBase
* references android.app.ContextImpl.mOuterContext
* leaks com.liburnia.classroom.activity.ClassRoomActivity instance

* Reference Key: 64463d35-1331-4e93-941e-5f97dad55a0b
* Device: LGE lge LG-D855 g3_global_com
* Android Version: 5.0 API: 21 LeakCanary: 1.3.1
* Durations: watch=5261ms, gc=144ms, heap dump=4838ms, analysis=46572ms

* Details:
* Instance of uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper
|   mInflater = uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater [id=0x32f2c0c0]
|   mAttributeId = 2130771969
|   mBase = android.app.ContextImpl [id=0x32cb12c0]
* Instance of android.app.ContextImpl
|   static $staticOverhead = byte[] [id=0x6ff9b6a1;length=56;size=72]
|   static EMPTY_FILE_LIST = java.lang.String[] [id=0x7619f3d8;length=0]
|   static SYSTEM_SERVICE_MAP = java.util.HashMap [id=0x7619f3e8]
|   static TAG = java.lang.String [id=0x6fe5b130]
|   static WALLPAPER_FETCHER = android.app.ContextImpl$1 [id=0x7619f418]
|   static sSharedPrefs = android.util.ArrayMap [id=0x32d49c80]
|   static DEBUG = false
|   static sNextPerContextServiceCacheIndex = 58
|   mActivityToken = android.os.BinderProxy [id=0x32d957e0]
|   mBasePackageName = java.lang.String [id=0x32e0f780]
|   mCacheDir = null
|   mCodeCacheDir = null
|   mContentResolver = android.app.ContextImpl$ApplicationContentResolver [id=0x32f2b760]
|   mDatabasesDir = java.io.File [id=0x32ef4b80]
|   mDisplay = null
|   mDisplayAdjustments = android.view.DisplayAdjustments [id=0x32ef4b90]
|   mExternalCacheDirs = null
|   mExternalFilesDirs = null
|   mExternalMediaDirs = null
|   mExternalObbDirs = null
|   mFilesDir = null
|   mMainThread = android.app.ActivityThread [id=0x32c03170]
|   mNoBackupFilesDir = null
|   mOpPackageName = java.lang.String [id=0x32e0f780]
|   mOuterContext = com.liburnia.classroom.activity.ClassRoomActivity [id=0x32df9180]
|   mOverrideConfiguration = null
|   mPackageInfo = android.app.LoadedApk [id=0x32e23350]
|   mPackageManager = android.app.ApplicationPackageManager [id=0x32f2b780]
|   mPreferencesDir = null
|   mReceiverRestrictedContext = null
|   mResources = android.content.res.Resources [id=0x32de8200]
|   mResourcesManager = android.app.ResourcesManager [id=0x32d49ca0]
|   mServiceCache = java.util.ArrayList [id=0x32f2b7a0]
|   mSimCardAuthenticationManager = null
|   mSync = java.lang.Object [id=0x32ef4ba0]
|   mTheme = android.content.res.Resources$Theme [id=0x32f2b7c0]
|   mUser = android.os.UserHandle [id=0x32ef4bb0]
|   mRestricted = false
|   mThemeResource = 16974120
* Instance of com.liburnia.classroom.activity.ClassRoomActivity
|   static $staticOverhead = byte[] [id=0x32c97001;length=56;size=72]
|   static CLASS_JOIN_STATUS = java.lang.String [id=0x32c5c200]
|   static CODE_CHECK = java.lang.String [id=0x32c5c1c0]
|   static CODE_KEY = java.lang.String [id=0x6fee0088]
|   static PEER_CONNECTED = java.lang.String [id=0x32c5f600]
|   static PEER_LOST = java.lang.String [id=0x32c5f7c0]
|   static RTC_SIGNALING = java.lang.String [id=0x32c5b6c0]
|   static SOCKET_DATA = java.lang.String [id=0x6fee64d8]
|   chatArrayList = java.util.ArrayList [id=0x32e27dc0]
|   downloadManagerPro = com.liburnia.classroom.util.filedownloader.core.DownloadManagerPro [id=0x32e2a070]
|   fileGlobalPath = java.lang.String [id=0x32e27de0]
|   fragmentContainer = android.widget.FrameLayout [id=0x32d22400]
|   mSocket = null
|   onClassJoinStatus = com.liburnia.classroom.activity.ClassRoomActivity$2 [id=0x32e10d70]
|   onDataReceived = com.liburnia.classroom.activity.ClassRoomActivity$6 [id=0x32e10d80]
|   onPeerConnected = com.liburnia.classroom.activity.ClassRoomActivity$4 [id=0x32e10d90]
|   onPeerLost = com.liburnia.classroom.activity.ClassRoomActivity$5 [id=0x32e10da0]
|   onRTCSignaling = com.liburnia.classroom.activity.ClassRoomActivity$3 [id=0x32e10db0]
|   uploadResponseCallback = com.liburnia.classroom.activity.ClassRoomActivity$1 [id=0x32e10dc0]
|   userArrayList = java.util.ArrayList [id=0x32e27e00]
|   mDelegate = android.support.v7.app.AppCompatDelegateImplV14 [id=0x32c8a900]
|   mFragments = android.support.v4.app.FragmentController [id=0x32e10dd0]
|   mHandler = android.support.v4.app.FragmentActivity$1 [id=0x32e27e20]
|   mMediaController = null
|   mCreated = true
|   mOptionsMenuInvalidated = false
|   mReallyStopped = true
|   mRequestedPermissionsFromFragment = false
|   mResumed = false
|   mRetaining = false
|   mStopped = true
|   mActionBar = null
|   mActivityInfo = android.content.pm.ActivityInfo [id=0x32de6400]
|   mActivityTransitionState = android.app.ActivityTransitionState [id=0x32e2b1c0]
|   mAllLoaderManagers = android.util.ArrayMap [id=0x32e27e40]
|   mApplication = com.liburnia.classroom.LiburniaClassroomApplication [id=0x32d49d20]
|   mComponent = android.content.ComponentName [id=0x32e10de0]
|   mContainer = android.app.Activity$1 [id=0x32e10df0]
|   mCurrentConfig = android.content.res.Configuration [id=0x32e22c50]
|   mDecor = null
|   mDefaultKeySsb = null
|   mEmbeddedID = null
|   mEnterTransitionListener = android.app.SharedElementCallback$1 [id=0x708e28e0]
|   mExitTransitionListener = android.app.SharedElementCallback$1 [id=0x708e28e0]
|   mFragments = android.app.FragmentManagerImpl [id=0x32e22cc0]
|   mHandler = android.os.Handler [id=0x32e27e60]
|   mInstanceTracker = android.os.StrictMode$InstanceTracker [id=0x32e10e00]
|   mInstrumentation = android.app.Instrumentation [id=0x32e28340]
|   mIntent = android.content.Intent [id=0x32e2b200]
|   mLastNonConfigurationInstances = null
|   mLoaderManager = null
|   mMainThread = android.app.ActivityThread [id=0x32c03170]
|   mManagedCursors = java.util.ArrayList [id=0x32e27e80]
|   mManagedDialogs = null
|   mMenuInflater = null
|   mParent = null
|   mResultData = null
|   mSearchManager = null
|   mTitle = java.lang.String [id=0x32df4060]
|   mToken = android.os.BinderProxy [id=0x32d957e0]
|   mTranslucentCallback = null
|   mUiThread = java.lang.Thread [id=0x74ddffa0]
|   mVoiceInteractor = null
|   mWindow = com.android.internal.policy.impl.PhoneWindowEx [id=0x32d39e60]
|   mWindowManager = android.view.WindowManagerImpl [id=0x32e0f880]
|   viewAgent = null
|   mCalled = true
|   mChangeCanvasToTranslucent = false
|   mChangingConfigurations = false
|   mCheckedForLoaderManager = true
|   mConfigChangeFlags = 0
|   mDefaultKeyMode = 0
|   mDestroyed = true
|   mDoReportFullyDrawn = false
|   mEnableDefaultActionBarUp = false
|   mFinished = true
|   mIdent = 980167678
|   mLoadersStarted = false
|   mResultCode = 0
|   mResumed = false
|   mStartedActivity = false
|   mStopped = true
|   mTemporaryPause = false
|   mTitleColor = 0
|   mTitleReady = true
|   mVisibleBehind = false
|   mVisibleFromClient = true
|   mVisibleFromServer = true
|   mWindowAdded = true
|   mInflater = uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater [id=0x32e0bd00]
|   mOverrideConfiguration = null
|   mResources = android.content.res.Resources [id=0x32de8200]
|   mTheme = android.content.res.Resources$Theme [id=0x32e0f8a0]
|   mThemeResource = 2131296513
|   mBase = uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper [id=0x32c02820]

Any help is appreciated.
Thanks for your great work :)

**Comment by chrisjenx** [comment]
Does this happen every time you finish an activity or very rarely.

**Comment by ShkurtiA** [comment]
This happens lets say 20 seconds after I start the activity. My app has only one activity for the moment.

**Comment by chrisjenx** [comment]
That sounds very odd. LeakCanary tracks memory reference after an item has been "finished" with.
The memory tracker is started when the activity/fragment is destroyed, so this doesn't make any sense. 

Are you doing device rotation or closing the app?

**Comment by ShkurtiA** [comment]
I have one activity but the first fragment is in portrait then in the second fragment I go in landscape mode. The problem here is that I add custom font only in the third fragment, and the leak happens without calling that fragment

**Comment by chrisjenx** [comment]
Can you post how you implement Calligraphy into your app?

**Comment by ShkurtiA** [comment]
This is the oncreate of Application class: 

    @Override
    public void onCreate() {
        super.onCreate();

        CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                        .setFontAttrId(R.attr.fontPath)
                        .build()
        );
.....


I have this in my BaseActivity which extends AppCompatActivity:

   @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
    }

And I use it like this in xml:

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:ignore="MissingPrefix">

    <TextView
        android:id="@+id/text"
        fontPath="fonts/helvetica-neue-bold.ttf"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
....

**Comment by ShkurtiA** [comment]
I tried another thing. I removed all rotations and moving from one fragment to another causes the same problem even without any activity recreation.

**Comment by chrisjenx** [comment]
OK, thanks, I'll see if I can reproduce in the example. Seems odd.

**Comment by ShkurtiA** [comment]
Look I think that maybe this isnt related with your library because I did smth else. I removed the library initialization in BaseActivity and application context and I have another leak: 


In com.liburnia.classroom:1.0:1.
* com.liburnia.classroom.activity.ClassRoomActivity has leaked:
* GC ROOT android.app.ContextImpl.mOuterContext
* leaks com.liburnia.classroom.activity.ClassRoomActivity instance

* Reference Key: f635574d-dfe9-408d-8cdb-de1384ec603a
* Device: LGE lge LG-D855 g3_global_com
* Android Version: 5.0 API: 21 LeakCanary: 1.3.1
* Durations: watch=78912ms, gc=398ms, heap dump=5163ms, analysis=47445ms

* Details:
* Instance of android.app.ContextImpl
|   static $staticOverhead = byte[] [id=0x6ff9b6a1;length=56;size=72]
|   static EMPTY_FILE_LIST = java.lang.String[] [id=0x7619f3d8;length=0]
|   static SYSTEM_SERVICE_MAP = java.util.HashMap [id=0x7619f3e8]
|   static TAG = java.lang.String [id=0x6fe5b130]
|   static WALLPAPER_FETCHER = android.app.ContextImpl$1 [id=0x7619f418]
|   static sSharedPrefs = android.util.ArrayMap [id=0x12ff2ac0]
|   static DEBUG = false
|   static sNextPerContextServiceCacheIndex = 58
|   mActivityToken = android.os.BinderProxy [id=0x12c77240]
|   mBasePackageName = java.lang.String [id=0x12c67120]
|   mCacheDir = null
|   mCodeCacheDir = null
|   mContentResolver = android.app.ContextImpl$ApplicationContentResolver [id=0x12d5ad20]
|   mDatabasesDir = java.io.File [id=0x12da6690]
|   mDisplay = null
|   mDisplayAdjustments = android.view.DisplayAdjustments [id=0x12d59890]
|   mExternalCacheDirs = null
|   mExternalFilesDirs = null
|   mExternalMediaDirs = null
|   mExternalObbDirs = null
|   mFilesDir = null
|   mMainThread = android.app.ActivityThread [id=0x12c3b240]
|   mNoBackupFilesDir = null
|   mOpPackageName = java.lang.String [id=0x12c67120]
|   mOuterContext = com.liburnia.classroom.activity.ClassRoomActivity [id=0x12d77180]
|   mOverrideConfiguration = null
|   mPackageInfo = android.app.LoadedApk [id=0x12c07630]
|   mPackageManager = android.app.ApplicationPackageManager [id=0x12d5adc0]
|   mPreferencesDir = null
|   mReceiverRestrictedContext = null
|   mResources = android.content.res.Resources [id=0x12c27620]
|   mResourcesManager = android.app.ResourcesManager [id=0x12c80120]
|   mServiceCache = java.util.ArrayList [id=0x12d5ace0]
|   mSimCardAuthenticationManager = null
|   mSync = java.lang.Object [id=0x12d598a0]
|   mTheme = android.content.res.Resources$Theme [id=0x12d7f1e0]
|   mUser = android.os.UserHandle [id=0x12d598b0]
|   mRestricted = false
|   mThemeResource = 16974120
* Instance of com.liburnia.classroom.activity.ClassRoomActivity
|   static $staticOverhead = byte[] [id=0x12d76001;length=56;size=72]
|   static CLASS_JOIN_STATUS = java.lang.String [id=0x12d5a820]
|   static CODE_CHECK = java.lang.String [id=0x12d5a860]
|   static CODE_KEY = java.lang.String [id=0x6fee0088]
|   static PEER_CONNECTED = java.lang.String [id=0x12d5a8c0]
|   static PEER_LOST = java.lang.String [id=0x12d5a900]
|   static RTC_SIGNALING = java.lang.String [id=0x12d5a920]
|   static SOCKET_DATA = java.lang.String [id=0x6fee64d8]
|   chatArrayList = java.util.ArrayList [id=0x12daaf60]
|   downloadManagerPro = com.liburnia.classroom.util.filedownloader.core.DownloadManagerPro [id=0x12da98b0]
|   fileGlobalPath = java.lang.String [id=0x12dac080]
|   fragmentContainer = android.widget.FrameLayout [id=0x12c1a000]
|   mSocket = io.socket.client.Socket [id=0x12da9610]
|   onClassJoinStatus = com.liburnia.classroom.activity.ClassRoomActivity$2 [id=0x12d59740]
|   onDataReceived = com.liburnia.classroom.activity.ClassRoomActivity$6 [id=0x12d59880]
|   onPeerConnected = com.liburnia.classroom.activity.ClassRoomActivity$4 [id=0x12d597e0]
|   onPeerLost = com.liburnia.classroom.activity.ClassRoomActivity$5 [id=0x12d59830]
|   onRTCSignaling = com.liburnia.classroom.activity.ClassRoomActivity$3 [id=0x12d59790]
|   uploadResponseCallback = com.liburnia.classroom.activity.ClassRoomActivity$1 [id=0x12d596e0]
|   userArrayList = java.util.ArrayList [id=0x12daaf80]
|   mDelegate = android.support.v7.app.AppCompatDelegateImplV14 [id=0x12d30590]
|   mFragments = android.support.v4.app.FragmentController [id=0x12d596b0]
|   mHandler = android.support.v4.app.FragmentActivity$1 [id=0x12d5aa00]
|   mMediaController = null
|   mCreated = true
|   mOptionsMenuInvalidated = false
|   mReallyStopped = false
|   mRequestedPermissionsFromFragment = false
|   mResumed = true
|   mRetaining = false
|   mStopped = false
|   mActionBar = null
|   mActivityInfo = android.content.pm.ActivityInfo [id=0x12c98080]
|   mActivityTransitionState = android.app.ActivityTransitionState [id=0x12d38980]
|   mAllLoaderManagers = android.util.ArrayMap [id=0x12dac840]
|   mApplication = com.liburnia.classroom.LiburniaClassroomApplication [id=0x12cc17a0]
|   mComponent = android.content.ComponentName [id=0x12c7b0b0]
|   mContainer = android.app.Activity$1 [id=0x12d59580]
|   mCurrentConfig = android.content.res.Configuration [id=0x12f5e200]
|   mDecor = com.android.internal.policy.impl.PhoneWindow$DecorView [id=0x12c19400]
|   mDefaultKeySsb = null
|   mEmbeddedID = null
|   mEnterTransitionListener = android.app.SharedElementCallback$1 [id=0x708e28e0]
|   mExitTransitionListener = android.app.SharedElementCallback$1 [id=0x708e28e0]
|   mFragments = android.app.FragmentManagerImpl [id=0x12d2d270]
|   mHandler = android.os.Handler [id=0x12d5a9e0]
|   mInstanceTracker = android.os.StrictMode$InstanceTracker [id=0x12d59590]
|   mInstrumentation = android.app.Instrumentation [id=0x12c25470]
|   mIntent = android.content.Intent [id=0x12c900c0]
|   mLastNonConfigurationInstances = null
|   mLoaderManager = null
|   mMainThread = android.app.ActivityThread [id=0x12c3b240]
|   mManagedCursors = java.util.ArrayList [id=0x12d5a980]
|   mManagedDialogs = null
|   mMenuInflater = null
|   mParent = null
|   mResultData = null
|   mSearchManager = null
|   mTitle = java.lang.String [id=0x12d5ae20]
|   mToken = android.os.BinderProxy [id=0x12c77240]
|   mTranslucentCallback = null
|   mUiThread = java.lang.Thread [id=0x74ddffa0]
|   mVoiceInteractor = null
|   mWindow = com.android.internal.policy.impl.PhoneWindowEx [id=0x12d231c0]
|   mWindowManager = android.view.WindowManagerImpl [id=0x12d7f160]
|   viewAgent = null
|   mCalled = true
|   mChangeCanvasToTranslucent = false
|   mChangingConfigurations = false
|   mCheckedForLoaderManager = true
|   mConfigChangeFlags = 0
|   mDefaultKeyMode = 0
|   mDestroyed = false
|   mDoReportFullyDrawn = false
|   mEnableDefaultActionBarUp = false
|   mFinished = false
|   mIdent = 964621749
|   mLoadersStarted = true
|   mResultCode = 0
|   mResumed = true
|   mStartedActivity = false
|   mStopped = false
|   mTemporaryPause = false
|   mTitleColor = 0
|   mTitleReady = true
|   mVisibleBehind = false
|   mVisibleFromClient = true
|   mVisibleFromServer = true
|   mWindowAdded = true
|   mInflater = com.android.internal.policy.impl.PhoneLayoutInflater [id=0x12d75460]
|   mOverrideConfiguration = null
|   mResources = android.content.res.Resources [id=0x12c27620]
|   mTheme = android.content.res.Resources$Theme [id=0x12d7f1c0]
|   mThemeResource = 2131296513
|   mBase = android.app.ContextImpl [id=0x12c5f850]


Maybe this means that its my problem and its reflected to the library

**Comment by chrisjenx** [comment]
That would suggest so. It could be a framework bug. Try the 1.4.0 snapshot
of leak canary and see if it goes away.

It looks like your leaking context somewhere. Also try on different
versions of Android/emulators etc.

**Comment by ShkurtiA** [comment]
Ok as soon as I will have an update I will reply to this issue

**Comment by ShkurtiA** [comment]
I think this isnt an issue related with your library. It is just reflected to that context I pass for ContextWrapper. There are a lot of issues like this one https://github.com/square/leakcanary/issues/1. I think this is happens because I watch activity from a class I need activity instance.

Thanks for your support and time.
Cheers!

**Comment by chrisjenx** [comment]
No worries. Hopefully someone else will stumble upon this issue.
