### ISSUE TITLE
How to work in my custom view's TextView?

### ISSUE THREAD

**Issue by xintang22** [chrisjenx/Calligraphy#234]
i have a custom view, in it have a textivew, how to can i use my font with textview?

i mean's , i want to use custom attr, for example:
in custom view:
------------------------------------------------------------
mTitleFamily = ta.getResourceId(R.styleable.TopBar_titleFamily, R.style.custom_font_bold);

 mTitileTextView.setTextAppearance(mContext, mTitleFamily);

those code don't work...

in XML:
<com.ezhongdou.ezhongdouclient.views.custom.TopBar
        android:id="@+id/topbar_login"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        topbar:titleColor="@android:color/white"
        topbar:titleFamily="@style/custom_font_bold"
        topbar:titleText="login" />

    <style name="custom_font_bold">
        <item name="fontPath">fonts/MFYueHei_Noncommercial_Regular.otf</item>
    </style>

**Comment by chrisjenx** [comment]
Calligraphy only works on inflated views. Not through views created in code.

Inflate your view from inside your Custom view e.g. `LayoutInflater.from(getContext()).inflate(R.layout.custom_layout,this,true)`
