### ISSUE TITLE
How to get name of Typeface ?

### ISSUE THREAD

**Issue by korrio** [chrisjenx/Calligraphy#239]
Typeface a = TypefaceUtils.load(getActivity().getAssets(), "fonts/ThaiSansNeue-Black.ttf");
a.getTypeFaceName(); // << something like this ?

At least to know the name font font (PostScript name or Standard name) for further reference in the app.

**Comment by chrisjenx** [comment]
`Typeface` is Android API, check the docs: https://developer.android.com/reference/android/graphics/Typeface.html
