### ISSUE TITLE
Custom font in list item not working although I configure it in my application class?

### ISSUE THREAD

**Issue by RadhikaPatel** [chrisjenx/Calligraphy#245]
Hello, 
It's great library and very useful!
But There's this issue where the calligraphy won't work. I have a adapter class for listview and 
The simple activity will display my custom font correctly but the activity, which have listviews, won't display the font.
Any ideas?
Thank You

**Comment by chrisjenx** [comment]
Please post how you get the LayoutInflater for the list items.

**Comment by chrisjenx** [comment]
Re comment if you want to continue investigation.
