### ISSUE TITLE
Title Font in Support Toolbar

### ISSUE THREAD

**Issue by afathman** [chrisjenx/Calligraphy#246]
I know there have been a few issues on this, however I'm still curious as to how to customize the toolbar title font. I've tried styling it, I've tried reflection and using the asset font loader. Nothing is working for me in release mode when minify is set to true.

**Comment by chrisjenx** [comment]
Have you tried the SNAPSHOT? Also you need to set the font path on the `actionBarTitle` appearance and the `actionBarSubtitle` appearance - as per the Sample.

**Comment by afathman** [comment]
I've tried the 2.1.1-SNAPSHOT with no luck, and I followed your example by using styles.

**Comment by afathman** [comment]
ended up using the following method:

    public static void applyFontForToolbarTitle(Activity context){
        Toolbar toolbar = (Toolbar) context.findViewById(R.id.app_bar);
        for(int i = 0; i < toolbar.getChildCount(); i++){
            View view = toolbar.getChildAt(i);
            if(view instanceof TextView){
                TextView tv = (TextView) view;
                Typeface titleFont = Typeface.
                   createFromAsset(context.getAssets(), "fonts/customFont");
                if(tv.getText().equals(context.getTitle())){
                    tv.setTypeface(titleFont);
                    break;
                }
            }
        }
    }

**Comment by chrisjenx** [comment]
Out of interest, does this work when not in release and minify is off?

**Comment by afathman** [comment]
Yes

**Comment by chrisjenx** [comment]
Ug, are you able to replicate the issue in the Sample?

**Comment by chrisjenx** [comment]
@afathman can you try the latest snapshot. `2.2.0-SNAPSHOT`
