### ISSUE TITLE
2.1.1-SNAPSHOT issue - no Toolbar's title when inflating using Data Binding library.

### ISSUE THREAD

**Issue by Jeevuz** [chrisjenx/Calligraphy#247]
Hi, Chris!
Today I almost killed myself trying figure out what was wrong with my Toolbar's (support) title. And finally I see that this is because of snapshot version fights android data binding library.

Xml:
```
<layout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"">
    <data>
        <variable
            name="title"
            type="String"/>
    </data>
    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <android.support.v7.widget.Toolbar xmlns:android="http://schemas.android.com/apk/res/android"
                                           android:layout_width="match_parent"
                                           android:title="@{title}"
                                           android:layout_height="?attr/actionBarSize"
                                           android:background="@color/primary"/>
    </FrameLayout>
</layout>
```
and in fragment:
```
    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        mBinding = StartFragmentBinding.inflate(inflater);
        mBinding.setTitle("It Works");
        return mBinding.getRoot();
    }
```
And on 2.1.0 all works fine.

**Comment by Jeevuz** [comment]
I back to 2.1.0 and all works fine.

**Comment by chrisjenx** [comment]
can you show me the generated layout file?:
`app/build/intermediates/data-binding-layout-out/dev/debug/layout`

**Comment by Jeevuz** [comment]
Yeah, sure:
```
<?xml version="1.0" encoding="utf-8"?>

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent" android:tag="layout/fragment_login_phone_0" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:app="http://schemas.android.com/apk/res-auto">

        <android.support.v7.widget.Toolbar
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="@color/primary"
            android:theme="@style/ToolbarThemeOverlay"
                                 android:tag="binding_1"/>

        <include layout="@layout/toolbar_shadow"/>

    </FrameLayout>
```
But I don't sure there is something interesting.
Let me know if you need something else.

**Comment by chrisjenx** [comment]
Have you tried executing the pending bindings inside the `onCreate`?

**Comment by Jeevuz** [comment]
Just tried it. Doesn't help. 
I added the execute method to the onCreateView:
```
    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        mBinding = LoginPhoneFragmentBinding.inflate(inflater);
        mBinding.setTitle("Title, please");
        mBinding.executePendingBindings();
        return mBinding.getRoot();
    }
```

But I noted that the binded layout inflates later than onResume called. I was trying to disable the menu item in onResume and it crashes with the NPE. So I had to use Handler#post(Runnable) to get it working.
I think it can be related to the issue.

**Comment by chrisjenx** [comment]
Hey, can you try the latest snapshot? `2.2.0-SNAPSHOT`

**Comment by Jeevuz** [comment]
Hi, Chris! 
Studio can't find the 2.2.0-SNAPSHOT version. I looked up in the snapshot repo and did't find it too.

But I tried to reproduce this issue again on 2.1.1- SNAPSHOT and you know what? With the current android gradle plugin version 2.0.0-beta6 the issue disappeared.

Maybe this is your fix working, but you forgot to change the snapshot name? :)

**Comment by chrisjenx** [comment]
Ha, your right I forgot to change the snapshot name. Doh.

OK glad it's fixed. I'll wrap up a release then.

**Comment by Jeevuz** [comment]
Yea, I'm glad too :) Thanks for fixing!

2016-02-29 21:47 GMT+03:00 Christopher Jenkins <notifications@github.com>:

> Ha, your right I forgot to change the snapshot name. Doh.
>
> OK glad it's fixed. I'll wrap up a release then.
>
> On Mon, 29 Feb 2016, 18:22 Vasili Chyrvon, <notifications@github.com>
> wrote:
>
> > Hi, Chris!
> > Studio can't find the 2.2.0-SNAPSHOT version. I looked up in the snapshot
> > repo and did't find it too.
> >
> > But I tried to reproduce this issue again on 2.1.1- SNAPSHOT and you know
> > what? With the current android gradle plugin version 2.0.0-beta6 the
> issue
> > disappeared.
> >
> > Maybe this is your fix working, but you forgot to change the snapshot
> > name? :)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/chrisjenx/Calligraphy/issues/247#issuecomment-190320134
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrisjenx/Calligraphy/issues/247#issuecomment-190329073>
> .
>



-- 
Vasili "Jeevuz" Chyrvon

**Comment by chrisjenx** [comment]
This has been pushed live with 2.2.0 today.

**Comment by vishnuc156** [comment]
use **app:title="@{title}"**  instead of **android:title="@{title}"** to resolve the issue
