### ISSUE TITLE
Doesn't work on android 5.1 but work nice on 4.4 and 5.0

### ISSUE THREAD

**Issue by AndreyUS** [chrisjenx/Calligraphy#248]
Hi, I'm using this library in my project and got some strange the issue. When I try run app on android 5.1 (Genymotion, nexus 4, android 5.1) custom fonts does not apply for my views. But if I run app on android 5.0 or android 4.4.4 (genymotion, nexus 4, 5) it works fine. My views located in fragment also I'm using android annotations from my fragment.
Do you have any ideas what I do wrong?

**Comment by bossik21** [comment]
Hi @AndreyUS 
Based on my last day fight with android 5.0. Try with a few other fonts.

**Comment by chrisjenx** [comment]
@AndreyUS I have zero idea what AA does to context and fragments. Few guesses.
- The TTF or OTF is not suited for Android 
- Or AndroidAnnotations messes with contexts.

If you run the Calligraphy sample and it works on 5.1 I would suggest its a combination of libraries messing up the Context passed through to the layoutinflater.

**Comment by AndreyUS** [comment]
@bossik21 , @chrisjenx 
It was the problem with fonts. I've changed all fonts in project (ttf -> otf) and now it works.
Thank you guys!

**Comment by chrisjenx** [comment]
Cool, great to hear!

**Comment by mkrasnowski** [comment]
More info on the issue: https://androidbycode.wordpress.com/2015/06/02/help-my-custom-font-does-not-work-on-android-5-0/

**Comment by chrisjenx** [comment]
Thanks for the link. Hopefully this will help others with a similar issue.
