### ISSUE TITLE
Is Calligraphy working with toolbars?

### ISSUE THREAD

**Issue by BoldijarPaul** [chrisjenx/Calligraphy#253]
I want to set the font of all my toolbars in all activities, is possible to do this, without creating another toolbar xml file, and setting a new textview as title?

**Comment by chrisjenx** [comment]
@BoldijarPaul there is a snapshot which should work, but the way `Toolbar`s are inflated is a nightmare.

Give the SNAPSHOT a go, let me know how you get on.

`compile 'uk.co.chrisjenx:calligraphy:2.1.1-SNAPSHOT'`

**Comment by chrisjenx** [comment]
Oh only support the AppCompat Toolbar not the built in one.

**Comment by marcio-granzotto-ckl** [comment]
No final version yet?

**Comment by chrisjenx** [comment]
Sorry yes I keep meaning to push 2.2.0. I'll get it done.

**Comment by chrisjenx** [comment]
2.2.0 released today.

**Comment by marcio-granzotto-ckl** [comment]
Awesome!
