### ISSUE TITLE
Is there any performance concerns if I use this library?

### ISSUE THREAD

**Issue by TonyTangAndroid** [chrisjenx/Calligraphy#260]
This library looks awesome and is very easy to use. But I am just wondering how much the performance will be sacrificed if I choose this library to support customized fonts? Could you please elaborate a little bit more about the implementation?

**Comment by chrisjenx** [comment]
@TonyTangAndroid well you can look for yourself all the code is there.

There is minor memory increase as we are finding attributes at run time and if you have a lot of views then there might be slightly increases GC. (That has been alleviated a little in the snapshot).

Apart from that the largest "performance" hit you are going to see is the use of additional Typefaces. 

Actual execution speed will be negligible, the majority of time is spent inflating and instantiating views which is done by the system anyway.
