### ISSUE TITLE
Font not being applied in Action bar - support library 23.2.1 

### ISSUE THREAD

**Issue by sonavolob** [chrisjenx/Calligraphy#261]
Hi, I have tested new support library 23.2.1 with Caligraphi 2.1.0 and font is not applied in ActionBars
- Title
- SearchView widget

Menu overFlow is ok.

Screenshots: 
support library 23.1.1 http://snag.gy/AVbgn.jpg
support library 23.2.1 http://snag.gy/HvsKr.jpg

Code is here https://github.com/sonavolob/ABIconTest.

**Comment by chrisjenx** [comment]
@sonavolob try the snapshot, that has a fix for Toolbars.

**Comment by sonavolob** [comment]
@chrisjenx Actually I have no experience with Maven so I have downloaded last snapshot from Calli Git repo and compiled it separately. Than I used aar file from "Calligraphy-master\calligraphy\build\outputs\aar" and imported it to ABIconTest project.

Result is the same...

**Comment by staroflead** [comment]
I think you should switch to use Toolbar as recommended by majority of android devs, Calligraphy works fine with toolbar in my case.

**Comment by sonavolob** [comment]
@staroflead Thank you for directing me. Replacing ActionBar for Toolbar did the thing (it messed up some other things, but corrected problems with Caligrhaphy).

**Comment by staroflead** [comment]
@sonavolob you are welcome

**Comment by chrisjenx** [comment]
Closing. 2.2.0 should work with the Toolbar, just to Clarify, I will not be supporting the ActionBar
