### ISSUE TITLE
Using System fonts in unison to custom fonts

### ISSUE THREAD

**Issue by afathman** [chrisjenx/Calligraphy#262]
I am stylizing my views as defined by strings, some being system fonts and others being custom fonts.
<TextView
        fontPath="@string/primary_font"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
This works when I'm using a custom font, however I get a 
"W/Calligraphy: Can't create asset from sans-serif. Make sure you have passed in the correct path and file name. java.lang.RuntimeException: Font asset not found sans-serif" when I try to use sans-serif. I'd like to keep using "fontPath" for all my views as the font I wish to use depends on the flavor I'm building. Is there any way to reference the built-in fonts from XML?

**Comment by staroflead** [comment]
In my opinion, you can omit the CalligraphyConfig.initDefault() so that you can continue to use system font, while declaring fontPath into s style and apply it where you need.
Make sure to use the code for multitypeface per textview if you have to mix the fonts

**Comment by chrisjenx** [comment]
@afathman as @staroflead use the style system to your advantage.
Don't define the default font in the `Config` but use `<style..` etc.. then you can define different styles per build etc..
