### ISSUE TITLE
Fonts not applied (native typeface cannot be made)

### ISSUE THREAD

**Issue by EveryNameTaken** [chrisjenx/Calligraphy#263]
So I've used Calligraphy when I started project just to check some fonts and it worked fine. I delayed all the "design stuff" for later. Now, when I'm back at it, Calligraphy isn't working from some reason.

I have few fonts in assets/. I've called attachBaseContext. I tried using fontPath attribute and as textAppearance style. I also tried using latest SNAPSHOT of library.

This is what i get in logs: 

 Can't create asset from fonts/Paprika.ttf. Make sure you have passed in the correct path and file name.
                                                                  java.lang.RuntimeException: native typeface cannot be made
                                                                      at android.graphics.Typeface.<init>(Typeface.java:175)
                                                                      at android.graphics.Typeface.createFromAsset(Typeface.java:149)
(...)

**Comment by chrisjenx** [comment]
So you have your font in `assets/fonts/Paprika.ttf`? 

If so then your font isn't designed for mobile or corrupt.
