### ISSUE TITLE
Android Support Library > v23.1.1

### ISSUE THREAD

**Issue by meneerraaf** [chrisjenx/Calligraphy#268]
In my app, Calligraphy works fine when using support library `v23.1.1`. However when I upgrade to the latest version (`v23.3.0`), the title font of newly launched `AppCompatActivity`'s is no longer set to a custom font. Note: the title of my MainActivity (launcher, which uses a `CoordinatorLayout`) is displayed correctly though and all other fonts are set to my custom font as well. I'm building with Calligraphy v2.2.0 and I initialise each activity correctly by calling:

```
super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
````

Any thoughts?

**Comment by chrisjenx** [comment]
Thats a little vague, can you post your xml layout?

**Comment by MasoodFallahpoor** [comment]
Same problem here with support library version 23.2.1

**Comment by meneerraaf** [comment]
My MainActivity uses a `CoordinaterLayout` (and works perfectly fine):

`
<?xml version="1.0" encoding="utf-8"?>
<DrawerLayout>
    <CoordinatorLayout>
        <AppBarLayout>
            <Toolbar />
        </AppBarLayout>
        <FrameLayout />
    </CoordinatorLayout>
    <NavigationView />
</DrawerLayout>
`

The other activities extend `AppCompatActivity` and have the following layout:

`
<?xml version="1.0" encoding="utf-8"?>
<ScrollView>
    <LinearLayout>
        < ... />
    </LinearLayout>
</ScrollView>
`

**Comment by bryanstern** [comment]
I'm actually seeing this too. I'm using the 23.3.0 support libs and Calligraphy 2.2.0

**Comment by chrisjenx** [comment]
OK I'll take a look this evening.

**Comment by bryanstern** [comment]
I'm stepping through this now with a debugger, but I'm unfamiliar with the source, so I'm not sure if this is helpful. It appears that `CalligraphyFactory#onViewCreated` is never passed the action bar.

**Comment by chrisjenx** [comment]
You're going to have to put together a sample as I can't reproduce this.

**Comment by chrisjenx** [comment]
Oh do you mean the auto inflated ActionBar doesn't work from the AppCompat Activity?

**Comment by bryanstern** [comment]
Yes, sorry it wasn't clear

**Comment by sebichondo** [comment]
Hi Chris, i seem to have the same problem. I'm currently on 'com.android.support:appcompat-v7:23.3.0' and 
@Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
    }

works for lower version of the support library just fine. I'm using calligraphy:2.2.0

**Comment by chrisjenx** [comment]
I haven't supported the action bar for ages. Not sure why your seeing this
now.

Use the toolbar. My guess is that they changed the underlying
implementation or its another thing they don't inflate.

**Comment by sebichondo** [comment]
Thanks Chris, decided to go with the <TextView fontPath="fonts/MyFont.ttf"/> option for now as i try to figure out what exactly changed

**Comment by gilbertparreno** [comment]
Is there anyone fixed this error?

**Comment by chrisjenx** [comment]
@gilbertparreno don't use ActionBar's, I'm not going to support them.
