### ISSUE TITLE
Change custom font programmatically

### ISSUE THREAD

**Issue by msroid** [chrisjenx/Calligraphy#270]
hi
is there any way to change custom font programmatically...??
i have some custom fonts and user will choose one of them. so, i need to change the custom font when user change his choice.

**Comment by logcat** [comment]
There are public methods in CalligraphyUtils
https://github.com/chrisjenx/Calligraphy/blob/master/calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyUtils.java#L107

**Comment by chrisjenx** [comment]
Effectively the same issue as #96 #100
