### ISSUE TITLE
Handling .otf typefaces ?

### ISSUE THREAD

**Issue by adamstyrc** [chrisjenx/Calligraphy#276]
Hey, I tried to use in `Application.onCreate()` below:

```
        CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                .setDefaultFontPath("font/Cadiz-Bold.otf")
                .setFontAttrId(R.attr.fontPath)
                .build());
```

And hoped to get result that every TextView I create will automatically have specified font. Is it .otf file not working ? Or it's nor library behavior to set default fonts ?

If it's .otf format I get Typeface instance as:

        `Typeface.createFromAsset(context.getAssets(), "font/" + fontName);`

**Comment by chrisjenx** [comment]
Nothing to do with Calligraphy, Android's support of OTF is very poor. It theoretically is supported, but I've never managed to get it to work reliably.

**Comment by chrisjenx** [comment]
If you are able to work out a feature set in the OTF that is supported I would love to be able to tell people how to check if they can use them or not.
