### ISSUE TITLE
How to apply Calligraphy for views created programmatically?

### ISSUE THREAD

**Issue by saqada** [chrisjenx/Calligraphy#279]
As I see from the sample app, all views which use Calligraphy are created in XML. I couldn't see how the library can be applied when we create views programmatically. In my case, when I create TexView then the library doesn't work for it. Is that an intended behaviour?

**Comment by chrisjenx** [comment]
The whole point of Calligraphy was to avoid having to apply typefaces outside of the style system.

If you want to apply Typefaces programmatically, you can do that - programmatically ;)

**Comment by outring** [comment]
Hi, @chrisjenx. I've stumbled upon this problem too, and the solution you suggest here doesn't seem to be as elegant as Calligraphy ought to be ;)

As you said, we have the style system and it's okay to want to create some views programmatically using this style system. Consider the following example:

Activity.java:
```
...
TextView myTextView = new TextView(context, null, R.attr.myTextViewStyle);
...
```

themes.xml
```
...
<item name="myTextViewStyle">@style/Widget.My.TextView</item>
...
```

styles.xml
```
  <style name="Widget.My.TextView" >
    <item name="fontPath">fonts/myFont.ttf</item>
  </style>
```

Now it doesn't work, so it would be great if it would be possible to apply font face in a single additional Calligraphy call here.
