### ISSUE TITLE
Why not find 2.2.0 in jcenter? 

### ISSUE THREAD

**Issue by caik13** [chrisjenx/Calligraphy#296]
I can't gradle the project, because gradle can't download it. Is the jcenter delete it ?

**Comment by chrisjenx** [comment]
well the dep is in maven and jcenter mirrors maven. Not sure. I only include jcenter in my gradle and it works. might just be there site which is out of date...

**Comment by chrisjenx** [comment]
Also no one else has complained about this, reopen if still an issue. (Also might need to refresh your deps).

**Comment by alexsimo** [comment]
```
> Could not find calligraphy.aar (uk.co.chrisjenx:calligraphy:2.2.0).
  Searched in the following locations:
      https://jcenter.bintray.com/uk/co/chrisjenx/calligraphy/2.2.0/calligraphy-2.2.0.aar
```

Same problem here.. @chrisjenx could have been removed from jCenter()?

**Comment by chrisjenx** [comment]
Yeah I'm not sure as https://jcenter.bintray.com/uk/co/chrisjenx/calligraphy/2.2.0/calligraphy-2.2.0.aar this actually resolves for me. I don't push to jcenter, I push to mavenCentral which sync's with jCenter.

**Comment by tohjg** [comment]
alternatively, you can use https://jitpack.io and paste this repo.

**Comment by chrisjenx** [comment]
Nope nope nope nope, that is a horrible broken distribution model. Part of
me publishing a version is a contract that it works and it's built in a
reliable way, jitpack breaks all those things.

**Comment by tohjg** [comment]
noted with thanks. i saw something broken in the [build log](https://jitpack.io/com/github/chrisjenx/Calligraphy/v2.2.0/build.log) yet it still allow to distribute to user.

**Comment by chrisjenx** [comment]
Yeah, there's a divide in the community. You can guess which side I'm on :)
