### ISSUE TITLE
Custom font not working for actionbar title when using setTitle() function

### ISSUE THREAD

**Issue by Sina7312** [chrisjenx/Calligraphy#297]
When you use getSupportActionBar().setTitle() to set a title for a activity, custom font not work.

**Comment by chrisjenx** [comment]
@Sina7312 We only support Toolbar from AppCompat, I would check that you use the Toolbar implementation the same way as the sample code. If you are post example code here.

**Comment by SjoerdvGestel** [comment]
i also cant figure out how to style the font of the appcompat title withouth setting a base font for the app...

**Comment by chrisjenx** [comment]
Check the sample app that works.
