### ISSUE TITLE
Custom font does not work for textview

### ISSUE THREAD

**Issue by Sminu** [chrisjenx/Calligraphy#300]
I used Calligraphy for custom fonts in my application and it works well and hassle free too. But, I need to use different fonts in my application. For eg. Lato regular, lato bold, lato italics etc. And I am able to set the custom font as Lato-Reg.ttf in the application file and it works well. But as you have suggested, I tried using in one of the textviews like below for a different font.

xmlns:tools=" http://schemas.android.com/tools"
tools:ignore="MissingPrefix"

<EditText
    android:layout_width="match_parent"
    android:layout_height="45dp"
    android:hint="Text"
    android:fontPath="fonts/Lato-BlaIta.ttf"

​But the font becomes the default android font. It is not taking the custom font I am providing. Do you have any solution for this? it would be great if you could help me here. I am aware that we can go ahead with custom textview and implement in each and every textviews using typeface. But I am specifically looking for some alternatives that could be done in calligraphy itself. Because it is simple. :)

**Comment by chrisjenx** [comment]
remove `android:`

**Comment by Sminu** [comment]
Wow.. that worked.. I had tried this earlier, but when i saw that this line is shown as error, I dint go ahead with it. Even now, it shows as if this line has some error. Still it works.. !! Thanks..
