### ISSUE TITLE
java.lang.NoClassDefFoundError: uk.co.chrisjenx.calligraphy.CalligraphyConfig$Builder

### ISSUE THREAD

**Issue by oneidc** [chrisjenx/Calligraphy#301]
I Have this error when i execute my activity

**Comment by oneidc** [comment]
I found the solution in this link https://github.com/chrisjenx/Calligraphy/issues/224

**Comment by zy1301529626** [comment]
I do not find this problem when i  use it in android studio,but find this problem in eclipse
