### ISSUE TITLE
Allow setting fake bold/strike/italic (and other Paint flags) via XML attributes

### ISSUE THREAD

**Issue by Alexander--** [chrisjenx/Calligraphy#302]
Note, that this issue has nothing to do with using different fonts or font glyphs, it is strictly about text-related Paint flags.

Right now one have to either use spans or manually set Paint flags in code to accomplish things like cheap fake bolding or strike-through. This makes for very messy code, just like manual management of Typefaces did before Calligraphy came to be. I believe, that this feature is also in scope of this library, and Calligraphy is the best place for implementing it.

I imagine, that implementation could look like

    textPaintFlags="fakeBold|subPixel"

**Comment by chrisjenx** [comment]
This is not in scope for Calligraphy, but there is something else I'm working on which would make this applicable.
