### ISSUE TITLE
Attribute textStyle not work.

### ISSUE THREAD

**Issue by rgarau** [chrisjenx/Calligraphy#303]
Hy, I have a question for you:
 
- When I customize a TextView with a custom font, is not possibile set textStyle attribute? TextStyle not work.
 
How can I use text style attribute with your library?
 
 
<TextView
    android:text="@string/hello_world"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    **android:textStyle=”bold”**
    android:textAppearance="@style/TextAppearance.FontPath"/>
 
The attibute textStyle don't change the style of the text.
Thanks for your support,

**Comment by chrisjenx** [comment]
dup: #46
