### ISSUE TITLE
Allow user to change font 

### ISSUE THREAD

**Issue by nimi8593** [chrisjenx/Calligraphy#307]
The implementation to set font when the app starts is fine. However I have a requirement to allow user to select from a set of fonts and changes reflect at runtime.
Does your library support that ?

**Comment by chrisjenx** [comment]
@nimi8593 It doesn't that's out of scope. If you are letting the user change Typefaces through the UI/Runtime. That would never be possible via inflation. Just call `setTypeface` at runtime. 
Or if you have a few configurations (maybe 3 different fonts to switch between) then define 3 different themes then reload the activity with the different theme.
