### ISSUE TITLE
Use CustomTextView with multiple TypeFaces

### ISSUE THREAD

**Issue by Fosile** [chrisjenx/Calligraphy#314]
Hey this is an awesome Library, but i got a little Problem.

I´m getting all my Text from my Server which can include bold, italic...... I use a CustomTextVIew for that, but in don´t understand how can i achieve that in combination with Calligraphy.

Of Course i never know what Text is coming from my server so i build this CustomTextView, which i use in my whole Project:

    public class CustomTextView extends TextView {

    private static final String ANDROID_SCHEMA = "http://schemas.android.com/apk/res/android";
    private Paint paint = new Paint();

    public CustomTextView(Context context) {
        super(context);

        applyCustomFont(context, null);
    }

    public CustomTextView(Context context, AttributeSet attrs) {
        super(context, attrs);

        applyCustomFont(context, attrs);
    }

    public CustomTextView(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);

        applyCustomFont(context, attrs);
    }

    private void applyCustomFont(Context context, AttributeSet attrs) {

            this.setTypeface(null,Typeface.NORMAL);
    }

    private Typeface selectTypeface(Context context, int textStyle) {
        /*
        * information about the TextView textStyle:
        * http://developer.android.com/reference/android/R.styleable.html#TextView_textStyle
        */
        switch (textStyle) {
            case Typeface.BOLD: // bold
                return FontCache.getTypeface("fonts/OpenSans-Bold.ttf", context);

            case Typeface.ITALIC: // italic
                return FontCache.getTypeface("fonts/OpenSans-Italic.ttf", context);

            case Typeface.BOLD_ITALIC: // bold italic
                return FontCache.getTypeface("fonts/OpenSans-BoldItalic.ttf", context);

            case Typeface.NORMAL: // regular
            default:
                return FontCache.getTypeface("fonts/OpenSans-Regular.ttf", context);
        }
    }

An in my Application Class i tried this:

    public class GFApplication extends android.app.Application {

    @Override
    public void onCreate() {
        super.onCreate();

        initializeCustomFont();
    }

    private void initializeCustomFont() {

        CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                .setDefaultFontPath("fonts/OpenSans-Regular.ttf")
                .setFontAttrId(R.attr.fontPath)
                .addCustomViewWithSetTypeface(CustomTextView.class)
                .build()
        );
    }

I know that i missing something, maybe you have an idea?

**Comment by chrisjenx** [comment]
We have no concept of runtime changing of Typefaces, if you applying Typefaces from your backend that is something you would have to do programatically - which is out of the scope of this project.

**Comment by Fosile** [comment]
Ok i understand, thank you very much for your help!

**Comment by chrisjenx** [comment]
No problem :)
