### ISSUE TITLE
Not Work in My define View

### ISSUE THREAD

**Issue by and0202** [chrisjenx/Calligraphy#315]
Not Work in My define View, how to use calligraphy?

> public class UserProfileDescView extends RelativeLayout {
>     private Context mContext;
>     private TextView titleTv;
> 
>     public UserProfileDescView(Context context) {
>         super(context);
>         initViews(context,null);
>     }
> 
>     public UserProfileDescView(Context context, AttributeSet attrs) {
>         super(context, attrs);
>         initViews(context,attrs);
>     }
> 
>     private void initViews(Context context,AttributeSet attrs) {
>         this.mContext = context;
>         initDesc(context);
>     }
> 
>     private void initDesc(Context context){
>         //Desc
>         descTv = new TextView(mContext);
>         descTv.setText(desc);
>         addView(descTv);
>     }
> }

**Comment by chrisjenx** [comment]
We only intercept inflated views. User `LayoutInflator.from(context,R.id.my_included_view)` or similar.
