### ISSUE TITLE
Font Does not apply for "PagerTabStrip"

### ISSUE THREAD

**Issue by sghazagh** [chrisjenx/Calligraphy#320]
Hi,
It seems that the font does not apply to the "PagerTabStrip" tab texts.
I have applied the Font on Application level, and inject the font in every Activity of my app.
Font of every elements have changed except text for "PagerTabStrip" Tabs!

Is that correct or I missed something?

**Comment by chrisjenx** [comment]
See #171 #180, The PaperTabStrip creates views and doesn't inflate them. Basically don't use it. It's super old and will probably be depreciated anyway. Use the [https://developer.android.com/reference/android/support/design/widget/TabLayout.html](TabLayout) you can set a customViewId on the Tab which will get inflated.

**Comment by elar-systems** [comment]
Hello my friend and thanks for your advise.

I have changed that to TabLayout and I still can see that the Font does not apply!
Do I need to implement anythings or just change it to LayoutTab?

The post #170 1nd #180 are to busy and I don't know which one is the FIX!

**Comment by chrisjenx** [comment]
@elar-systems https://github.com/chrisjenx/Calligraphy/issues/180#issuecomment-198298812
