### ISSUE TITLE
Default font not working

### ISSUE THREAD

**Issue by Ab-Appletic** [chrisjenx/Calligraphy#321]
I don't think I really understood the ReadMe well, because I have this in my code:

     @Override
    public void onCreate() {
        super.onCreate();
        CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                .setDefaultFontPath("fonts/trado.ttf")
                .setFontAttrId(R.attr.fontPath)
                .build());
    }

    @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
    }

And I have *trado.ttf* in my *assets* folder. This is in my `Application` class. This is all I've did, did I miss something?

**Comment by chrisjenx** [comment]
@Ab-Appletic you apply `attachBaseContext` in the `Activity`s not in the `Application` class.
