### ISSUE TITLE
Text Style not working and Layout Inflator Exception Crash

### ISSUE THREAD

**Issue by varunrramani** [chrisjenx/Calligraphy#328]
We have been using this library for a long time now and we just noticed the textStyle="bold" is not being applied to any TextView. After removing the library it applied fine.

Also the other issue is mentioned quite a few times about CalligraphyLayoutInflator crash and we still see the issue.

**Comment by chrisjenx** [comment]
Dup #195 #46 Closing

**Comment by chrisjenx** [comment]
As for the Crash, I doubt it's Calligraphy, we just get blamed because we take over inflation. If you want me to have a look, post the stack trace in a new issue.
