### ISSUE TITLE
apply font to TextInputLayout

### ISSUE THREAD

**Issue by BoldijarPaul** [chrisjenx/Calligraphy#330]
How can I apply TextInputLayout to a TextInputLayout error?
I've tried with

 `           app:errorTextAppearance="@style/FontStyle"`

```
 <style name="FontStyle" parent="@android:style/TextAppearance">
        <item name="fontPath">"fonts/CondensedBold.otf"</item>
    </style>

```
But not working.

**Comment by chrisjenx** [comment]
dup #201

**Comment by chrisjenx** [comment]
The errorText is created and applied in code, not much I do about this (apart from a hacky work around) until they inflate the views.

**Comment by HimanshuNarang** [comment]
Font is applied but color of error text become black
