### ISSUE TITLE
TextInputLayout not working when inputType is textPassword

### ISSUE THREAD

**Issue by DaRolla** [chrisjenx/Calligraphy#339]
Hi there,
thanks a lot for your lib.

I found an issue.

```
    <android.support.design.widget.TextInputLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <EditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="textPassword"/>
    </android.support.design.widget.TextInputLayout>
```

Using the support libraries "appcompat-v7" and "design" in version "25.0.0" the hint has the wrong type face. Filling in some text makes the hint becoming a label, which stays wrong.

Best regards,
DaRolla

**Comment by chrisjenx** [comment]
Known issue related #57 #186 #201

**Comment by chrisjenx** [comment]
Heads up @DaRolla you should be using: https://developer.android.com/reference/android/support/design/widget/TextInputEditText.html
