### ISSUE TITLE
TextInputLayout.setError() not using the font

### ISSUE THREAD

**Issue by muhammad-naderi** [chrisjenx/Calligraphy#343]
Hi, 

Thanks for the super awesome library!

there is a small problem I wanted to report, 
I use library by attaching it to context:

```
@Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
    }
```

but when I set error for TextInputLayouts which are warping either EditText or AppCompatEditText the error textview beneath the Edit text does not use the font I have set to the project

**Comment by chrisjenx** [comment]
Duplicate #201
