### ISSUE TITLE
How to change color of application dynamically like font

### ISSUE THREAD

**Issue by mwshubham** [chrisjenx/Calligraphy#346]
Based on the SO answer http://stackoverflow.com/a/33992017/5028508 i am interested in how we can use Calligraphy library for changing color dynamically. Is it possible. I have read your comment like THEMES ARE IMMUTABLE and all but on the same note i have installed ROOT CHECKER app by jaret rumler and work as per my need.

**Comment by chrisjenx** [comment]
Themes are immutable. If you want dynamic anything, call `setColor`,`setApperance` `setTypeface`
