### ISSUE TITLE
Cut or copy using the Clipboard crashes the app

### ISSUE THREAD

**Issue by jaychang0917** [chrisjenx/Calligraphy#347]
Same problem with #308. But the problem occurs on my Google Nexus x5 6.0.0 and Samsung note 5. The problem can be reproduced by long pressing the EditText to show cut or copy menu, then the app crash.

**Comment by chrisjenx** [comment]
@jaychang0917 does it still happen after turning Calligraphy off?

**Comment by jaychang0917** [comment]
@chrisjenx sorry for my late reply. No, the problem doesn't happen after turning Calligraphy off.

**Comment by jaychang0917** [comment]
@chrisjenx I found the problem is due to `TextInputLayout`'s theme style. If someone have similar issue, can refer [http://stackoverflow.com/questions/39609740/fatal-exception-android-view-inflateexception-binary-xml-file-line-20](this SO)

**Comment by chrisjenx** [comment]
Great thanks for the update Jay!

**Comment by nemani1** [comment]
We are facing the same issue.
