### ISSUE TITLE
Allowing optional interception of the resolved font

### ISSUE THREAD

**Issue by jbarr21** [chrisjenx/Calligraphy#350]
We are currently using Calligraphy for applying our fonts, but would like the option to experiment with and safely roll out the fonts that we use. The idea behind this would be to have a default font name applied via a theme, style, text appearance, or on the view, but when the font is resolved, provide a hook to allow for interception of the font name and to optionally return a different font name to actually use. What would you think of an additional API like this?

Suggested implementation:

Define an interface for the interceptor:
```java
public interface ResolvedFontInterceptor {
    String onFontResolved(String textViewFont);
}
```

Set the optional interceptor via the CalligraphyConfig.Builder and add to the CalligraphyConfig:
```java
public Builder addResolvedFontInterceptor(ResolvedFontInterceptor interceptor) {
      this.resolvedFontInterceptor = interceptor;
      return this;
}

mResolvedFontInterceptor = builder.resolvedFontInterceptor;

@Nullable
public ResolvedFontInterceptor getResolvedFontInterceptor() {
    return mResolvedFontInterceptor;
}
```

In CalligraphyFactory#resolveFontPath, before returning the resolved `textViewFont`, add the interceptor:
```java
ResolvedFontInterceptor interceptor = CalligraphyConfig.get().getResolvedFontInterceptor();
if (interceptor != null) {
      textViewFont = interceptor.onFontPathResIdResolved(textViewFont);
}
```

**Comment by chrisjenx** [comment]
@jbarr21 lets get this into InflationX repos when possible.
This would solve #354 and possibly #362

**Comment by apkelly** [comment]
@jbarr21 is there a branch/fork where I can try this out? I need to switch font when the user switches locale inside the app I'm working on.

**Comment by chrisjenx** [comment]
Check out the v3 version. GitHub.com/InflationX
