### ISSUE TITLE
Feature request: a 'test' mode

### ISSUE THREAD

**Issue by njwandroid** [chrisjenx/Calligraphy#354]
How hard would it be to have a 'test' mode in the configuration builder that sets your whole app to Dancing Cursive or something built in that would enable you to more easily see if fonts are applied in case the differences are subtle as they often are?

**Comment by chrisjenx** [comment]
Mmmm, we are exploring a `FontMapper` which means during testing you could map ALL fonts to `Windings` if you desired!

**Comment by chrisjenx** [comment]
Will close, track through #350
