### ISSUE TITLE
Question: How do we use builtin font when we have default font enabled 

### ISSUE THREAD

**Issue by njwandroid** [chrisjenx/Calligraphy#355]
@chrisjenx  If we use setDefaultFontPath("/font/whatever.ttf") how do we use a built-in font such as Noto or DancingCursive? 

http://stackoverflow.com/questions/19691530/valid-values-for-androidfontfamily-and-what-they-map-to

**Comment by chrisjenx** [comment]
You don't, just ship them yourselves. The reason this library exists is because system fonts are not garrenteed.
