### ISSUE TITLE
Class cast exception android.app.ContextImpl when using with Firebase

### ISSUE THREAD

**Issue by amitkaira87** [chrisjenx/Calligraphy#357]
**The Issue is during FCM integration**

```
Exception java.lang.RuntimeException: Unable to start receiver com.google.firebase.iid.FirebaseInstanceIdInternalReceiver: java.lang.ClassCastException: uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper cannot be cast to android.app.ContextImpl
android.app.ActivityThread.handleReceiver (ActivityThread.java:2750)
android.app.ActivityThread.access$1800 (ActivityThread.java:154)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1431)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5443)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:728)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:618)
arrow_drop_down
Caused by java.lang.ClassCastException: uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper cannot be cast to android.app.ContextImpl
```

**When i comment the below ApplicationController code, it works fine** 
```
 @Override
    public void onCreate() {
        super.onCreate();
        CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                .setDefaultFontPath("fonts/RobotoCondensedLight.ttf")
                .setFontAttrId(R.attr.fontPath)
                .build()
        );
    }


    @Override
    protected void attachBaseContext(Context base) {
        MultiDex.install(this);
        super.attachBaseContext(CalligraphyContextWrapper.wrap(base));
    }
```

FirebaseInstanceIdInternalReceiver is not created by me so i could't manage the context there. 

**I tried solutions of your different lib at below url but didn't found any solution** 
https://github.com/mikepenz/Android-Iconics/issues/180

**Comment by chrisjenx** [comment]
@amitkaira87 see #211 

Wrap the **`Activity`** Context:
```
@Override
protected void attachBaseContext(Context newBase) {
    super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
}
```

**Comment by sodiqOladeni** [comment]
Hi there,
I'm using the library with firebase notification.
seems this issue has been resolved but still don't know what i'm doing wrong, can you please give a detailed explanation, have checked other link as well. 

below is my code for the App Font,

public class AppFont extends AcraReport {

    @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
    }

    @Override
    public void onCreate() {
        super.onCreate();

        CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                .setDefaultFontPath("fonts/helveticaneue.ttf")
                .setFontAttrId(R.attr.fontPath)
                .build()
        );
    }
}

and the Acra class

public class AcraReport extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        // The following line triggers the initialization of ACRA
        ACRA.init(this);
    }
My AppFont declaration in the manifest
<application
        android:name=".allClass.AppFont"
        android:allowBackup="true"
        android:hardwareAccelerated="false"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

...
</application>

Kindly help check

**Comment by sodiqOladeni** [comment]
<application
        android:name=".allClass.AppFont"
        android:allowBackup="true"
        android:hardwareAccelerated="false"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

**Comment by chrisjenx** [comment]
You init in the application class, then attack in your activity classes.
Not all in the activity class

**Comment by mimoccc** [comment]
Solution (app or activity)

   @Override
    public Intent registerReceiver(BroadcastReceiver receiver, IntentFilter filter) {
        try {
            return getRealBaseContext().registerReceiver(receiver, filter);
        } catch (Exception e) {
            e.printStackTrace();

            return null;
        }
    }

    @Override
    public Intent registerReceiver(BroadcastReceiver receiver, IntentFilter filter, String broadcastPermission, Handler scheduler) {
        try {
            return getRealBaseContext().registerReceiver(receiver, filter, broadcastPermission, scheduler);
        } catch (Exception e) {
            e.printStackTrace();

            return null;
        }
    }

    @RequiresApi(api = Build.VERSION_CODES.O)
    @Override
    public Intent registerReceiver(BroadcastReceiver receiver, IntentFilter filter, int flags) {
        try {
            return getRealBaseContext().registerReceiver(receiver, filter, flags);
        } catch (Exception e) {
            e.printStackTrace();

            return null;
        }
    }

    @RequiresApi(api = Build.VERSION_CODES.O)
    @Override
    public Intent registerReceiver(BroadcastReceiver receiver, IntentFilter filter, String broadcastPermission, Handler scheduler, int flags) {
        try {
            return getRealBaseContext().registerReceiver(receiver, filter, broadcastPermission, scheduler, flags);
        } catch (Exception e) {
            e.printStackTrace();

            return null;
        }
    }

    @Override
    public void unregisterReceiver(BroadcastReceiver receiver) {
        try {
            getRealBaseContext().unregisterReceiver(receiver);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Initialize custom libraries & code for debug
     */
    protected void initDebug() {
        if (BuildConfig.DEBUG) {
            try {
                Class<?> cls = Class.forName("no.telia.bedriftsnett.debug.Debug");

                Method m = cls.getMethod("init", Application.class);

                m.invoke(null, this);
            } catch (Exception e) {
            }
        }
    }

    protected Context getRealBaseContext() {
        Context c = getBaseContext();

        while ((c != null) && (c instanceof ContextWrapper)) {
            try {
                c = ((ContextWrapper) c).getBaseContext();
            } catch (Exception e) {
                e.printStackTrace();

                c = null;
            }
        }

        return c;
    }

**Comment by mimoccc** [comment]
remove initDebug. sorry :)

**Comment by ivanboltyshev** [comment]
I found a solution, someone has already talked about it before.
Choose your App class that extends from Application.
And remove from there
`@Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
    }`
Next, your class should look like this

> public class App extends Application {

 >   @Override
>    public void onCreate() {
>       super.onCreate();
 >       CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
 >               .setDefaultFontPath("fonts/MM.ttf")
>                .setFontAttrId(R.attr.fontPath)
>                .addCustomViewWithSetTypeface(CustomViewWithTypefaceSupport.class)
>                .build()
>        );
>    }
>}
And declare it in manifest
`<application
android:name=".App"
......
</application>`

**Comment by samuelowino** [comment]
CalligraphyConfig.initDefault} Is no longer available. is this solution still relevant ?

**Comment by chrisjenx** [comment]
We Deprecated this lib in favor of https://github.com/InflationX/Calligraphy about 3ish years ago. It's a pretty easy migration.
