### ISSUE TITLE
How to make font sizes in app to not get effected by changing Settings Font size

### ISSUE THREAD

**Issue by denebchorny** [chrisjenx/Calligraphy#358]
Hi, when I change font size and font type on a Samsung phone (changing font size and type is an option on these phones) my app looks uggly. 

1) Is there a way to always use the font defined by me ?

2) Is there a way to prevent the OS change the font size inside my app?

Thanks in advance.

**Comment by chrisjenx** [comment]
Use DP instead of SP? This is not really related to Calligraphy. StackOverflow would be a much better place to ask that.
