### ISSUE TITLE
Can you add the interface to set the font path as external or internal file path instead of assets?

### ISSUE THREAD

**Issue by LiuLei030504** [chrisjenx/Calligraphy#359]
Hello,

Its very fantastic library I have ever used. Thanks for your hard works.
I am going to create the solution to replace the font in the application and this font will be downloaded from the server. Unfortunately, there is only interface to set the font path based on  assets folder. I think there is a way to load the font from the storage in Android SDK. I am guessing Typeface.createFromFile is the interface to use it.

Do you have plan to add such interface at this library? It will be so appreciated if you have the plan to add such useful interface. Please let me know your thoughts.

Thanks
LiuLei

**Comment by chrisjenx** [comment]
dup #96
