### ISSUE TITLE
I use this library in style and fonts changed after once orientation changed!

### ISSUE THREAD

**Issue by mhmoafi** [chrisjenx/Calligraphy#371]
How to fix this problem?

**Comment by chrisjenx** [comment]
Post code of your implementation.

**Comment by mhmoafi** [comment]
style code:
`<resources>

    
    <style name="AppTheme" parent="AppTheme.Base">
        <item name="fontPath">fonts/helta.ttf</item>
        

    </style>

    <style name="AppTheme.Base" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:windowBackground">@color/windowBackground</item>
        <item name="android:navigationBarColor">@color/navigationBarColor</item>
        <item name="android:colorControlHighlight">@color/colorHighlight</item>

    </style>

    <style name="noAnimTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowAnimationStyle">@null</item>
    </style>

    <style name="AppTheme.AppBarOverlay" parent="ThemeOverlay.AppCompat.Dark.ActionBar" />

    <style name="AppTheme.PopupOverlay" parent="ThemeOverlay.AppCompat.Light" />


</resources>
`

manifests code:
`<application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <activity android:name=".MainActivity" android:theme="@style/noAnimTheme">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>`
activity java code:
` //font
    @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //setContentView(R.layout.activity_main_appbar);
        setContentView(R.layout.activity_main_today);
        myToolbar = (Toolbar) findViewById(R.id.app_bar);
        setSupportActionBar(myToolbar);

        //Font
        CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                .setDefaultFontPath("fonts/helta.ttf")
                .addCustomStyle(AppCompatTextView.class, android.R.attr.textViewStyle)
                .setFontAttrId(R.attr.fontPath)
                .build()
        );
...`
activity layout xml code:
`<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/todayActivity_MainLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <fragment
        android:layout_width="250dp"
        android:layout_height="match_parent"
        android:id="@+id/fragment_navigation_drawer"
        android:name="com.janinban.janinban10.navigationDrawerFragment"
        app:layout="@layout/fragment_navigation_drawer"
        tools:layout="@layout/fragment_navigation_drawer"
        android:layout_gravity="start" />

    <RelativeLayout
        android:id="@+id/activity_main_1"
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
...`

**Comment by chrisjenx** [comment]
Which fonts aren't changing?

**Comment by mhmoafi** [comment]
all fonts in mainActivity (LuncherActivity), But after once tilt phone and orientation changed, all fonts be applyed

**Comment by chrisjenx** [comment]
You need to init Calligraphy in the APPLICATION class.
