### ISSUE TITLE
how to disable reflection in library ?

### ISSUE THREAD

**Issue by Mahdihp** [chrisjenx/Calligraphy#388]

**Comment by chrisjenx** [comment]
This is

**Comment by yangjieK** [comment]
CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                .disableCustomViewInflation()
                .build());

**Comment by OsmanYalin** [comment]
> CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
> .disableCustomViewInflation()
> .build());

this was the trick. thanks!

**Comment by chrisjenx** [comment]
I would upgrade to Caligraphy 3 if you haven't already. (https://github.com/InflationX/Calligraphy)
