### ISSUE TITLE
how to change font for whole application ?

### ISSUE THREAD

**Issue by baadillahnabil** [chrisjenx/Calligraphy#389]
change all fonts in application without setting `fontPath` in each component ?

**Comment by badoualy** [comment]
https://github.com/chrisjenx/Calligraphy#installation

The default font path will be applied by default.

**Comment by baadillahnabil** [comment]
yeah thanks i got it working..
init inside `onCreate()` Application class --> inject it to `attachBaseContext()` in each activites --> done! great!

and don't forget to set `android:name=".App"` inside application tag in manifest (because i forgot this and had me spinning for a while :D )

**Comment by spongyMongy** [comment]
Hi. Is it still possible to use this library with Android 8.0+ ? I couldn't transform this for the new devices with the old code, can you enlighten me what to do please.. thanks

**Comment by exutic** [comment]
i created a settings activity for my app . and i want to change the fonts in there not directly from style..... any ideas ?
