### ISSUE TITLE
App not running below API 23

### ISSUE THREAD

**Issue by HITESHGOEL08** [chrisjenx/Calligraphy#398]
I am latest Android Studio 2.3.3. I am using Facebook SDK with Firebase SDK and Adobe Creative SDK, due to which iI have to Multidex application which enables Multidex dependency.

I am trying to install app on lollipop 5.1 but it shows

com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/iid/zzc.class

I even tried with other OS when using API below 22 it shows this error but when using API 23 above its installed and is running perfectly.

how to solve this problem...

My gradle file is

      apply plugin: 'com.android.application'
       apply plugin: 'me.tatarka.retrolambda'
         android {
                  compileSdkVersion 25
                 buildToolsVersion '25.0.3'
                 defaultConfig {
                  applicationId "com.practice.android.moments"
                  minSdkVersion 18
                 targetSdkVersion 25
                  versionCode 1
                 versionName "1.0"
       
            multiDexEnabled true
    
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

            manifestPlaceholders = [appPackageName: "${applicationId}"]
           }

           buildTypes {
                   release {
                       minifyEnabled false
               proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
                }
                  }

             dexOptions {
                       jumboMode true
                    }
           compileOptions {
                             sourceCompatibility JavaVersion.VERSION_1_8
                             targetCompatibility JavaVersion.VERSION_1_8
                                     }

                 /* 3)(Creative SDK) Exclude duplicate licenses */
            packagingOptions {
                       exclude 'META-INF/LICENSE.txt'
                       exclude 'META-INF/LICENSE'
                       exclude 'META-INF/LICENSE-FIREBASE.txt'
                       exclude 'META-INF/NOTICE'
                       exclude 'META-INF/NOTICE.txt'
                       exclude 'META-INF/DEPENDENCIES'
                       pickFirst 'AndroidManifest.xml'
                   }
                   }

                   repositories {
                                          mavenCentral()
                                          }
                   dependencies {

                   compile fileTree(include: ['*.jar'], dir: 'libs')
                   androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
                       exclude group: 'com.android.support', module: 'support-annotations'
                   })
                   compile 'com.android.support:recyclerview-v7:25.3.1'
                   compile 'com.android.support:appcompat-v7:25.3.1'
                   compile 'com.android.support.constraint:constraint-layout:1.0.2'
                   compile 'com.android.support:cardview-v7:25.3.1'
                   compile 'com.google.android.gms:play-services-auth:11.0.1'
                   compile 'com.google.firebase:firebase-core:11.0.1'
                   compile 'com.google.firebase:firebase-messaging:11.0.1'
                   compile 'com.google.firebase:firebase-auth:11.0.1'
                   compile 'com.google.firebase:firebase-database:11.0.1'
                   compile 'com.google.firebase:firebase-storage:11.0.1'
                   compile 'com.google.firebase:firebase-ads:11.0.1'
                   compile 'com.google.firebase:firebase-invites:11.0.1'
                   compile 'com.google.firebase:firebase-appindexing:11.0.1'
                   compile 'com.google.firebase:firebase-crash:11.0.1'
                 
                   compile 'com.facebook.android:facebook-android-sdk:[4,5)'
                   compile 'com.android.support:support-v4:25.3.1'
                   compile 'com.android.support:design:25.3.1'
                   compile 'de.hdodenhof:circleimageview:2.1.0'
                   compile 'com.android.support:multidex:1.0.1'

                   compile 'com.adobe.creativesdk.foundation:auth:0.9.1251'
                   compile 'com.adobe.creativesdk:image:4.8.4'
                   compile 'com.localytics.android:library:3.8.0'

                   testCompile 'junit:junit:4.12'}

            configurations.all {
                   resolutionStrategy.force 'com.google.code.findbugs:jsr305:3.0.1'}
                   
                   apply plugin: 'com.google.gms.google-services'

**Comment by chrisjenx** [comment]
Update gradle and the plugin and try again.
