### ISSUE TITLE
Font does not apply to TextInputLayout error text

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [chrisjenx/Calligraphy#400]
Hi, Thanks for this awesome library.
I use it... Its very good.
But have missing some things like this:
![photo_2017-07-06_22-23-07](https://user-images.githubusercontent.com/17345129/27925361-b7169fc6-6299-11e7-83e8-8abf0616b58e.jpg)
In TextInputLayout when set Error enabled, Font does not apply to error text.
Thanks.

**Comment by behzadian** [comment]
this is my problem, is there any voting system in  here?

**Comment by AmirHosseinKarimi** [comment]
@behzadian Thanks for vote. There is some method to bypass this problem. You can find they in issues of this repository.

**Comment by chrisjenx** [comment]
The hintText isn't set by `setTypeface` you'll need to manually override the `setHintTypeface` annoyingly.

We have pretty much stopped development here in lieu of official support from Google and our github.com/InflationX efforts.
