### ISSUE TITLE
Doesn't work with TextClock

### ISSUE THREAD

**Issue by thanhbinh84** [chrisjenx/Calligraphy#406]
<android.widget.TextClock
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:format24Hour="kk:mm"
        android:textSize="50sp"
        fontPath="fonts/font.otf"
        />
-> doesn't work 
have to set by code 
mTimeTextView.setTypeface(Typeface.createFromAsset(mContext.getAssets(), "fonts/font.otf"));

**Comment by chrisjenx** [comment]
`TextClock` probably doesn't extend `TextView`? Also don't use `otf` use `ttf` if you can.
