### ISSUE TITLE
gradle error

### ISSUE THREAD

**Issue by derakhshanfar** [chrisjenx/Calligraphy#408]
my dependencies is 
```
compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha7'
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:design:25.0.1'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'uk.co.chrisjenx:calligraphy:2.3.0'
```
when i want to compile my project , i give this error:

> Error:Failed to resolve: com.android.support:appcompat-v7:25.3.1

**Comment by bigyanthapa** [comment]
seems like the support library version included in the dependency is "25.0.1" and somewhere in the code, versions "25.3.1" is being referenced. 
And by the way, the latest support library version "26.0.0" is released now which we can use.

**Comment by rogeriovalente** [comment]
I'm getting an error when trying to use the 2.3.0 version.
Error: (28, 13) Fail to resolve: uk.co.chrisjenx: calligraphy: 2.3.0

When I set up the 2.2.0 version, gradle sync with no problem.

**Comment by chrisjenx** [comment]
Try the latest versions, if issues please raise on V3 lib
