### ISSUE TITLE
Using Calligraphy changes background color of Recyclerview items

### ISSUE THREAD

**Issue by FelixEder** [chrisjenx/Calligraphy#409]
I'm using calligraphy to set a custom font and after following the installation guide it works well.
I wrap the context of my main activity and the custom font is set correctly to my textViews.

I do however get a strange side-effect, the background of cards in my RecyclerViews get a very dark grey background color. If I remove the wrapping of the context from the activity, the custom fonts disappear but also the dark background of the cards. Therefor I think it must be an issue with Calligraphy and how it interacts with the recyclerview somehow?

How do I fix this? I need to use custom fonts but also need my cards to have their original color

**Comment by azri92** [comment]
Hi @FelixEder, _I'm just passing by here_. I think you might have to provide code of how you implemented Calligraphy and code of the RecyclerView list items / card views.

Does adding a background attribute to the cards change anything?

**Comment by FelixEder** [comment]
Hi @azri92 , sorry for a late reply. I tried everything regarding background attributes to no luck. But since I didn't actually need the Recycler view I remade it into a GridView which had no problems with background of cards.

But I guess this would still be an issue if you really need to use a recycler view.

**Comment by azri92** [comment]
I see. Well, I had a hunch that it might be that the background attribute of the cardview item itself that may be missed. But it's good to know if it's not a problem for you anymore. Have a nice day! *flies off*

**Comment by chrisjenx** [comment]
This should be fixed in Callgraphy3 where we clone the theme context correctly now.
