### ISSUE TITLE
Custom font in Action bar & navigation drawer

### ISSUE THREAD

**Issue by EhsanMomeni81** [chrisjenx/Calligraphy#416]
Sorry if this has been asked, and answered, but I'm so new at this, and I have tried everything, with no luck.

How do I set a custom font for the action bar & navigation drawer? The base of my app is from [https://github.com/delaroy/SlidingMenuWebView](url) is a simple sliding drawer that opens a webview. I have managed to add the dependency, and add it to my theme (the loading dialog now has the correct font, but I haven't published it yet).

My problem is that I have no idea how to add the same font (PoiretOne.ttf) to the action bar and drawer.

Please help me (and explain like you would to a 5-year old). Thank you so much

My app: [https://play.google.com/store/apps/details?id=se.senastgaisvann.smguld](url)

**Comment by chrisjenx** [comment]
Hi @EhsanMomeni81 unless they use the `Toolbar` view you can't define it, you'd probably need to set it by hand.
