### ISSUE TITLE
Not working inside module

### ISSUE THREAD

**Issue by martinbaciga** [chrisjenx/Calligraphy#418]
Hi,

I'm trying to use the library inside a module of my project. I don't know how can i achieve this, i tried adding all configuration lines, but with no success. Is this posible?

Thanks!

Note: in my project i have this already working.

**Comment by chrisjenx** [comment]
It would only work in a lib project if you were serving activities they consumed. but there is no way to define it globally in a lib module

**Comment by afaucogney** [comment]
@chrisjenx why do you mean exactly by serving activities ?

**Comment by chrisjenx** [comment]
> @chrisjenx why do you mean exactly by serving activities ?

As you override baseContext in the Activity, you could only provide a calligraphy config for those activities, otherwise there is no shared config right now. 

Basically use ViewPump, it supports multiple configs - and this is depreciated for ViewPump or direct androidx support.
