### ISSUE TITLE
"android:textAllCaps" does not work

### ISSUE THREAD

**Issue by saguinav** [chrisjenx/Calligraphy#42]
Hi!

When I set the attribute "android:textAllCaps" to true on my xml it actually does nothing. 

Great library!

**Comment by twinkleSiya** [comment]
Hii, Good Afternoon.

I have implemented Tablayout with viewpager, when tab title text in .ttf font not working.

I have done Style code, but I'm facing the same problem.

see my xml code ->
 <android.support.design.widget.TabLayout
 android:id="@+id/tabs"
 android:layout_width="match_parent"
 android:layout_height="wrap_content"
 style="@style/CustomTabLayout"
 android:background="#eceff1"
 app:tabMode="fixed"
 app:tabGravity="fill"/>    

style code ->
<style name="CustomTabLayout" parent="Widget.Design.TabLayout">
 <item name="tabIndicatorColor">@color/iconGray</item>
 <item name="tabIndicatorHeight">3dp</item>
 <item name="tabBackground">?attr/selectableItemBackground</item>
 <item name="tabTextAppearance">@style/CustomTabTextAppearance</item>
 <item name="tabSelectedTextColor">@color/colorPrimary</item>
</style>

<style name="CustomTabTextAppearance" parent="TextAppearance.Design.Tab">
 <item name="android:textSize">@dimen/txt_15</item>
 <item name="android:textColor">#a4dbb2</item>
 <item name="android:fontFamily">@font/amaranth</item>
 <item name="textAllCaps">true</item>
</style>

Thank u in advance...
