### ISSUE TITLE
Crash in Samsung Devices

### ISSUE THREAD

**Issue by iad24** [chrisjenx/Calligraphy#420]
I noticed that my app crashed in most of Samsung devices:
- S1 5.0
- Note 4 6.0.1
- 

But not in
- S6 7.0
- Sony
- Asus

Is this a known issue that it has problem on Samsung devices?

**Comment by chrisfoulds** [comment]
I am seeing lots of crashes on Samsung S7 but fine on other devices, I see you closed this - did you discover the reason?
