### ISSUE TITLE
RadioButtons not affected by my custom font

### ISSUE THREAD

**Issue by hoseinit** [chrisjenx/Calligraphy#421]
Hi, 
I have added custom font to my base Activity and every view till now has been affected by my custom font.
Now I am creating an AlertDialog with a custom view which has radiogroup.
The problem is the texts of the radiobuttons has not affected and has default ugly font.
thanx

**Comment by Inzimam-Tariq** [comment]
This is the case when Radio Buttons created dynamically. Try this while they fix the issue.
`radioButton.setTypeface(Typeface.createFromAsset(context.getAssets(),
                                "fonts/DroidKufi-Regular.ttf"));`
Here `context` is the reference of `Activity`
