### ISSUE TITLE
textStyle="bold" no longer applies after setting a default font?

### ISSUE THREAD

**Issue by liuzhen2008** [chrisjenx/Calligraphy#423]
It occurs to me that after I use a font as the theme default.

```
        initDefault(new CalligraphyConfig.Builder()
                .setDefaultFontPath(getString(R.string.font_helvetica_neue))
                .setFontAttrId(R.attr.fontPath)
                .build());
```

For some reason textStyle="bold" no longer gets applied in my app. I had to change font to a bold version to apply bold style.

Is there some way i could automatically use a bold version of the font for textStyle="bold"?

**Comment by deshario** [comment]
Hey @liuzhen2008  Did u find the solution ?

**Comment by c0dehunter** [comment]
Is there any solution to this? I want to be able to use bold style too.

**Comment by tuandoan23** [comment]
Is there any solution? @liuzhen2008

**Comment by harryd-23** [comment]
@chrisjenx Do you have any solution?

**Comment by chrisjenx** [comment]
Same response as #438
