### ISSUE TITLE
Inject default TypeFace with support library downloadable fonts

### ISSUE THREAD

**Issue by mahmoud-elmorabea** [chrisjenx/Calligraphy#427]
Hello, thanks for the fantastic library!

I was wondering if there is a way to inject a default `TypeFace` instance (rather than path) into `Calligraphy`.

It would be nice to obtain the `TypeFace` instance from `res/fonts` folder or through the new downloadable fonts in support library and inject it into `Calligraphy` at runtime.

I was unable to find something that allows that to be done. Any suggestions?

**Comment by chrisjenx** [comment]
Not something we will support, V3 might look into it if requested allot.
