### ISSUE TITLE
android:maxLines and android:ellipsis results in ellipsis not displayed

### ISSUE THREAD

**Issue by bubbleguuum** [chrisjenx/Calligraphy#43]
A TextView defining both maxLine (whatever the value) and ellipsize results in the TextView applying the custom font but not displaying the ellipsis (...) for strings longer than maxLines.

``` xml
      <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        fontPath="@string/media_item_title_font"      
        android:maxLines="2"
        android:ellipsize="end"
        tools:ignore="MissingPrefix" />
```

With the following text:

this is line1
this is line2
this is line3

the TextView above will display:

this is line1
this is line2

instead of:

this is line1
this is line2...

Removing the fontPath element produces the expected result

**Comment by PankajChunchun** [comment]
Spannable in rare cases? No. Now a days, we use in many cases and this issue still exists...

**Comment by dinakarmaurya-innova** [comment]
Setting below attribute works(show ... at the end) only if the TextView width is match parent 
android:ellipsize="end"
 android:maxLines="1"
 android:singleLine="true"

**Comment by AnwarShahriar** [comment]
> Setting below attribute works(show ... at the end) only if the TextView width is match parent
> android:ellipsize="end"
> android:maxLines="1"
> android:singleLine="true"

Thanks @dinakarmaurya-innova this actually worked.
