### ISSUE TITLE
Use Calligraphy in everything except my custom TextView

### ISSUE THREAD

**Issue by MHKalantarian** [chrisjenx/Calligraphy#430]
Can I apply calligraphy to whole layout except a custom TextView with another typeface?

**Comment by OsmanYalin** [comment]
any answer?

**Comment by OsmanYalin** [comment]
https://github.com/chrisjenx/Calligraphy/issues/388#issuecomment-307311701

**Comment by chrisjenx** [comment]
That would disable all custom views (including AppCompatTextView etc). You would just override the `setTypeface` method in your custom view to not pass to super.
