### ISSUE TITLE
Load from font resource directory?

### ISSUE THREAD

**Issue by kassim** [chrisjenx/Calligraphy#431]
Is this possible with Calligraphy?

I want to use the native font support but don't want to refactor all my old code that I've been using Calligraphy with. Is it possible for me to move the font files to the `res/font` folder and somehow have them still loaded by Calligraphy?

**Comment by chrisjenx** [comment]
resources don't allow that kind of file, they would be "raw" files a best, but no, they shouldn't live in resources, they are assets.

**Comment by kassim** [comment]
resources do allow that kind of file https://developer.android.com/guide/topics/resources/font-resource - specifically in the `res/font` folder

or you meant something else?

**Comment by chrisjenx** [comment]
They were added in Android 8.0 (API level 26), if your min version is 26+ then I would 100% use that instead of Calligraphy as thats offically supported. Otherwise older versions just don't read it.
