### ISSUE TITLE
Add method to disable logging

### ISSUE THREAD

**Issue by Aditya94A** [chrisjenx/Calligraphy#436]
I use productFlavors to shave of everything I don't need in debug builds, things like languages other than english, multiple resolution drawables, ARM native dependencies and fonts.

So I don't care about fonts in most of my debug builds so I remove them and Calligraphy complains and clutters up my logcat. Would love an option disable this :)

**Comment by chrisjenx** [comment]
Won't fix here, but if it's still an issue in V3 please raise an issue over there.
