### ISSUE TITLE
Textview Style Not Working

### ISSUE THREAD

**Issue by deshario** [chrisjenx/Calligraphy#438]
After I use this library in MainApp ... My default textview style is not working anymore such as bold,italic and underline... How to fix it?

**Comment by c0dehunter** [comment]
I am interested too.

**Comment by busylee999** [comment]
The same behaviour, I used this in Base activity like this

```
    override fun attachBaseContext(newBase: Context?) {
        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase))
    }
```

and now text style for TextView does not work anymore.

Is there any solution or fix?

**Comment by chrisjenx** [comment]
When you set a typeface it overrides any "fontstyle" you set, you need to apply the bold/italic versions where applicable.
