### ISSUE TITLE
Failed to resolve calligraphy

### ISSUE THREAD

**Issue by sanjayitdesires** [chrisjenx/Calligraphy#444]
I recently upgraded to Android Studio 3.1 from Stable Channel. After this, I am getting an error like "Failed to resolve calligraphy". Anyone have the solution for this issue.

**Comment by chriswiesner** [comment]
Seems that jCenter is not hosting it anymore (at least recent versions) see https://jcenter.bintray.com/uk/co/chrisjenx/calligraphy/

you can still get it on mavenCentral (just make sure that `mavenCentral()` is on top of `jcenter()` in your build.gradle repositories)

**Comment by norrisboat** [comment]
@chriswiesner thanks a lot. Your suggestion worked for me

**Comment by pravingaikwad07** [comment]
google()
mavenCentral()
jcenter()


thanks it worked.
