### ISSUE TITLE
Will this work with AndroidX?

### ISSUE THREAD

**Issue by ghost** [chrisjenx/Calligraphy#450]
Since this library depends on the support library, will it break if i "Refactor to androidx"? And if so, is there plans to migrate this library to androidx?

**Comment by chrisjenx** [comment]
That is a very good question, and the answer is probably yes. 
I'll talk to one of the team about the best steps forward

**Comment by kibotu** [comment]
there is a pull request for calligraphy3 fork (https://github.com/InflationX/Calligraphy/pull/10)

(usable with jitpack atm https://jitpack.io/#kibotu/Calligraphy/v4.0.1)

**Comment by timc-mediamonks** [comment]
Yes, it works. Jetifier fixes all references except for generated code.

**Comment by chrisjenx** [comment]
This lib wont, v3+ will
