### ISSUE TITLE
Is it necessary to recreate activity after font change?

### ISSUE THREAD

**Issue by kilicpl** [chrisjenx/Calligraphy#460]
Hi. Thanks million times for such a great library bro! As a newbie my question would be is there a way we can continue using the new font without recreating the application upon changing. Thanks a lot again
Czesc

**Comment by chrisjenx** [comment]
Seen as you can't change xml at runtime you'd have to manually change it via setTypeface() anyway.
If you do any theme switching I'm fairly sure they require an activity restart.

Anyway, this is not really a Calligraphy limitation or feature this is something you need to think about how you design your app.
