### ISSUE TITLE
Change font on tab layout?

### ISSUE THREAD

**Issue by beingabstrac** [chrisjenx/Calligraphy#462]
How do I override Tab Layout font to my custom font? Can't do that.

**Comment by WaiYanMyintMyat** [comment]
me too....bro

**Comment by lesterlopez-dev** [comment]
@rishirD You are implementing TabLayout with ViewPager ? If you are implementing TabLayout with ViewPager with Pager Adapter, you can apply spannable string inside your adapter as your title.
