### ISSUE TITLE
Android 8 not working?

### ISSUE THREAD

**Issue by spongyMongy** [chrisjenx/Calligraphy#464]
Great library(thanks very much), it was working great up to now but with Oreo devices it's not working anymore and sadly there is no information on the net about how to correct the issue. Can anyone encountered and solved this problem  help on that please?

**Comment by ghost** [comment]
@danteshell I'm not related to this project. That said, you need to provide details to questions and issues. Think how you would react to someone coming up, saying you have a bug in your app and walking away.

**Comment by spongyMongy** [comment]
Thanks @Starwind0 but I believe it was quite clear for someone who knows what is going on about this project:) To be more precise, up to Android Oreo, it was possible to change the app-wide fonts when we configure the Application class correctly and select a new font (let say from a dialog box).  When the related class has 

protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(ViewPumpContextWrapper.wrap(newBase));
    }

method, all was working  seamlessly. As I said, after Oreo it doesn't change the fonts anymore (at least in my case), thanks for pointing out - hopefully there is a solution for it.

**Comment by chrisjenx** [comment]
This has been fixed in ViewPump upcoming version
