### ISSUE TITLE
Unresolved reference: fontPath

### ISSUE THREAD

**Issue by MahdiFarzami** [chrisjenx/Calligraphy#471]
ViewPump.init(
            ViewPump.builder()
                .addInterceptor(
                    CalligraphyInterceptor(
                        CalligraphyConfig.Builder()
                            .setDefaultFontPath(FONTS_ASSET_PATH + FONT_NAME_REGULAR)
                            .setFontAttrId(R.attr.fontPath)
                            .build()
                    )
                )
                .build()
The R.attr.fontPath not resolve.

Library using implementation 'io.github.inflationx:calligraphy3:3.1.1'

**Comment by chrisjenx** [comment]
Calligraphy3 is a fork of this for ViewPump. Head over to the examples over there.

**Comment by Cob007** [comment]
@chrisjenx Please how can I resolve this problem in my kotlin project

**Comment by iceberg1369** [comment]
I have the same issue

**Comment by retuner87** [comment]
Try to change configuration to:

`.setFontAttrId(io.github.inflationx.calligraphy3.R.attr.fontPath)`
