### ISSUE TITLE
unexpected namespace prefix "app" found for tag TextView

### ISSUE THREAD

**Issue by loeschg** [chrisjenx/Calligraphy#54]
IDE: Android Studio 0.8.2

Whenever I use the app:fontPath in a layout in Android Studio, I get a warning "unexpected namespace prefix "app" found for tag TextView." I'm adding `xmlns:app="http://schemas.android.com/apk/res-auto"` in my root layout. I have to add tools:ignore="MissingPrefix" to the view to remove the warning.

![screenshot 2014-07-16 11 16 17](https://cloud.githubusercontent.com/assets/766021/3600875/243ba6f6-0cfc-11e4-9fbb-44308a0d98f6.png)

I have the following in my values/attr.xml:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <attr name="fontPath" />
</resources>
```

**Edit:** To be clear, this does not break anything. It's just a slight irritant :grinning:

**Comment by ahrasis** [comment]
I think changing TextView to android.support.v7.widget.AppCompatTextView could fix the issue. Can anyone confirm this?

**Comment by Hack06** [comment]
ahrasis, I confirm that your solution works, thanks.
The authors of this lib need to figure out what's the difference between TextView and android.support.v7.widget.AppCompatTextView.
