### ISSUE TITLE
Possible Memory Leak on Calligraphy 0.7.x?

### ISSUE THREAD

**Issue by akohout** [chrisjenx/Calligraphy#55]
I'm still using the 0.7.x version of your library, but maybe the problem (if it is a real problem) still holds for the current version.

Currently, I'm investigating memory footprint and usage of my app. Via Android Studio, I can record the memory usage of my app with a pretty easy overview. This overview, among other stuff, also displays the allocation of assets. I load two custom fonts for my app using Calligraphy. When I start my app, these two fonts have two references each - so it allocates each font twice. After surfing around, I can see that one of the fonts is allocated 6 times in memory (while the other font keeps with 2).

```
Asset Allocations
    zip:/data/app/***.apk:/assets/fonts/GothamRnd-Medium.otf: 123K
    zip:/data/app/***.apk:/assets/fonts/GothamRnd-Medium.otf: 123K
    zip:/data/app/***.apk:/assets/fonts/GothamRnd-Book.otf: 133K
    zip:/data/app/***.apk:/assets/fonts/GothamRnd-Medium.otf: 123K
    zip:/data/app/***.apk:/assets/fonts/GothamRnd-Medium.otf: 123K
    zip:/data/app/***.apk:/assets/fonts/GothamRnd-Medium.otf: 123K
    zip:/data/app/***:/assets/fonts/GothamRnd-Medium.otf: 123K
    zip:/data/app/***:/assets/fonts/GothamRnd-Book.otf: 133K
```

What's going on there? I'm setting the font via styles in XML. But I'm not sure whether the memory leak is my fault (which I assume), or whether it's maybe a calligraphy bug.

**Comment by placebokid** [comment]
Please reopen the issue. There is definitely memory leak. https://dl.dropboxusercontent.com/s/2cw5r18q56xh5rm/2015-03-03%20at%202.14%20pm%20%281%29.png?dl=0

You should implement typeface cache to be safe from memory leak.
https://stackoverflow.com/questions/16901930/memory-leaks-with-custom-font-for-set-custom-font

**Comment by chrisjenx** [comment]
There is a typeface cache. If there is a memory leak then it's related to
resources not being released.

Are you able to rule out calligraphy first by disabling it then running mat
on your project?
