### ISSUE TITLE
Applying style programatically doesn't change fontPath

### ISSUE THREAD

**Issue by zsperske** [chrisjenx/Calligraphy#90]
So I've got some fonts such as:

<style name="Title">
        <item name="android:textSize">@dimen/title_text</item>
        <item name="fontPath">fonts/gotham_narrow_bold.OTF</item>
    </style>

Which uses a bold font, if I apply this via XML, I have no issues. However sometimes I'd like to programatically switch the style applied to a text view, in which case the text is no longer bolded and uses the default font, in this case <item name="fontPath">fonts/gotham_narrow_book.OTF</item>.

**Comment by mori-honest** [comment]
Please Add this to wiki or how to use section in the readme.
