### ISSUE TITLE
Calligraphy prevents onCreateView() (with a parent parameter) from being called

### ISSUE THREAD

**Issue by dlew** [chrisjenx/Calligraphy#92]
There's some tricky issues I'm trying to work around in app-compat, mostly around the custom tinted Views they insert during inflation. I've come up with a solution, but Calligraphy blocks it.

Here's the issue: app-compat implements some tinted views, for example TintSpinner. These tinted views, when given a context with app-compat theming, can automatically tint their colored elements. The way it injects these tinted views is by using `Activity.onCreateView()` (without the parent parameter) to inflate these views.

The issue I was running into was that these tinted `Views` were sometimes using the wrong context - they should take on the parent `Toolbar` context if there is one, but they always use the `Activity`'s. The only way I could find around it was to *stop* app-compat from creating these tinted Views automatically, then add them myself in `onCreateView()` (with a parent parameter, so I could detect if the parent is a `Toolbar`).

However, with Calligraphy this doesn't work, because Calligraphy practically guarantees that `onCreateView()` (without parent) returns an inflated `View`. Thus `onCreateView()` (with parent) is never called.

One solution would be to do some similar wrapping like `CalligraphyContextWrapper` to insert a `Factory2` into the `LayoutInflater` that creates the tinted views. But I think a proper solution would be to implement both `LayoutInflater.Factory` and `LayoutInflater.Factory2`, where `createViewOrFailQuietly()` is only called in `Factory2`. That way you still have the opportunity to automatically get to `onCreateView()` with a parent without having to implement your own `Factory2` interface.

I'm willing to submit a PR on this but I wanted a sanity check before jumping into the code.

**Comment by chrisjenx** [comment]
Closing this was handled "better" in #101
