### ISSUE TITLE
Interference with android:listChoiceIndicatorMultiple

### ISSUE THREAD

**Issue by aenain** [chrisjenx/Calligraphy#93]
Hey!

First of all many thanks for the great library, I didn't even know about Activity#attachBaseContext method :+1:

Unfortunately it looks like Calligraphy 1.2.0 interferes with android:listChoiceIndicatorMultiple on checkboxes.

I use Calligraphy to globally set custom font (Apex New) from OTF file. It works everywhere, even on checkboxes, but it somehow prevents custom graphics for checkboxes from being used. I call CalligraphyConfig.initDefault from Application#onCreate.

Device: LG Nexus 4
Android: 4.4.4

#### styles.xml

```
<style name="AppTheme" parent="android:Theme.Holo.Light">
        <item name="android:listChoiceIndicatorMultiple">@drawable/button_checkbox</item>
</style>

<style name="GettingStartedListCheckbox">
        <item name="android:layout_width">match_parent</item>
        <item name="android:layout_height">wrap_content</item>
        <item name="android:gravity">center_vertical</item>
        <item name="android:textColor">@color/text</item>
        <item name="android:textSize">@dimen/text_size</item>
        <item name="android:paddingTop">@dimen/activity_vertical_margin</item>
        <item name="android:paddingBottom">@dimen/activity_vertical_margin</item>
</style>
```

#### fragment_profile_interests_item.xml

```
<CheckBox
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/interest_toggle"
    android:text=""
    style="@style/GettingStartedListCheckbox">
</CheckBox>
```

Checkbox is rendered in a list view in a fragment from an activity that derives from android.app.Activity. I add the fragment when user clicks on a button with a transition created from a manager instantiated in Activity#onCreate method.

### Now the interesting part...

When I use the code below custom checkbox image does not work and the one from Theme.Holo.Light is used instead.

```
@Override
protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(new CalligraphyContextWrapper(newBase));
}
```

![screenshot_2014-11-04-15-59-19](https://cloud.githubusercontent.com/assets/349641/4902271/427e715a-6438-11e4-8ed3-964ebb5d711c.png)

When I comment the attachBaseContext function, I get the right images...

![screenshot_2014-11-04-15-58-29](https://cloud.githubusercontent.com/assets/349641/4902284/5689a048-6438-11e4-84a6-ae2bf05fe023.png)

*I am not sure if it is expected behaviour.*

## Workaround

My workaround of this issue is to use drawableLeft instead. One thing though.. it changes height of the checkbox.

```
<style name="WorkingCheckbox" parent="GettingStartedListCheckbox">
        <item name="android:button">@null</item>
        <item name="android:drawableLeft">@drawable/button_checkbox</item>
</style>
```

**Comment by chrisjenx** [comment]
@aenain can you confirm this is still an issue with 2.0.0-SNAPSHOT? If so please reopen the issue.
